import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {suite} from './agency-suite.js';
import {passwordAccess} from './password-access.js';
import {collaboratorAccess} from './collaborator-access.js';
import {budgetDocument} from './budget-document.js';
const pg=new PGlite();await pg.exec(await fs.readFile('schema.sql','utf8'));
for(const name of ['20260908_treasury_ledger.sql','20260908_people_commissions_comments.sql','20260908_operations_complete.sql','20260908_referral_discounts.sql','20260908_collaborator_profiles.sql','20260908_agency_suite.sql','20260908_daily_controls.sql'])await pg.exec(await fs.readFile('migrations/'+name,'utf8'));
const query=(sql,args)=>pg.query(sql,args),db={query,connect:async()=>({query,release(){}})};
await pg.exec(await fs.readFile('migrations/20260910_productivity.sql','utf8'));
await pg.exec(await fs.readFile('migrations/20260910_client_links.sql','utf8'));
for(const file of ['20260908_google_oauth.sql','20260910_profile_identity.sql','20260910_demo_sessions.sql','20260910_invite_links.sql','20260910_currencies.sql','20260910_company_currency.sql','20260910_global_identity.sql'])await pg.exec(await fs.readFile('migrations/'+file,'utf8'));
await pg.exec(await fs.readFile('migrations/20260911_drive_links.sql','utf8'));
const org=(await query("select id from organizations where slug='scale'")).rows[0].id;
const other=(await query("insert into organizations(slug,name) values('suite-other','Other') returning id")).rows[0].id;
const uid=(await query("insert into users(email,password_hash) values('suite-owner@example.invalid','unused') returning id")).rows[0].id;
const viewer=(await query("insert into users(email,password_hash) values('suite-viewer@example.invalid','unused') returning id")).rows[0].id;
await query("insert into organization_members(organization_id,user_id,role) values($1,$2,'owner'),($1,$3,'viewer')",[org,uid,viewer]);
const user={id:uid,organization_id:org,role:'owner',organization_name:'Scale'};
let resetToken='',sent=0;
async function call(path,method='GET',payload={},as=user,form=''){
 let result={status:0};const req={method,socket:{remoteAddress:'127.0.0.1'},async *[Symbol.asyncIterator](){yield form;}};
 const args={req,res:{writeHead(status,headers){result={status,headers};},end(content){result.content=content;}},url:new URL('https://test'+path),db,session:async()=>as,body:async()=>payload,send:(_,status,data)=>{result={status,...data};},sendInvitation:async()=>true,sendReset:async(_,token)=>{resetToken=token;sent++;return true;}};
 const handled=path.startsWith('/api/auth/password')?await passwordAccess(args):await suite(args);assert.equal(handled,true);return result;
}
const client=(await query("insert into agency_clients(organization_id,name) values($1,'Client') returning id",[org])).rows[0].id;
const project=(await query("insert into agency_projects(organization_id,client_id,name,approval_levels) values($1,$2,'Project',2) returning id",[org,client])).rows[0].id;
const order=(await query("insert into agency_work_orders(organization_id,project_id,title,status) values($1,$2,'Video','review') returning id",[org,project])).rows[0].id;
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{name:'Changed'})).record.name,'Changed');
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{social_links:{website:'https://example.com',instagram:'https://www.instagram.com/example/',whatsapp:'https://wa.me/595981000000',other:[{label:'Catálogo',url:'https://example.com/catalogo'}]}})).status,200);
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{name:'Renamed'})).record.social_links.website,'https://example.com');
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{social_links:{website:'javascript:alert(1)'}})).status,400);
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{social_links:{}},{...user,role:'editor'})).status,403);
assert.equal((await call(`/api/agency/clients/${client}`,'PATCH',{name:'Cross tenant'},{...user,organization_id:other})).status,404);
let linksResult=await call(`/api/agency/projects/${project}`,'PATCH',{drive_links:'https://drive.google.com/file/d/one\nhttps://drive.google.com/drive/folders/two'});assert.equal(linksResult.record.drive_url,'https://drive.google.com/file/d/one');assert.equal(linksResult.record.drive_links.length,2);
linksResult=await call(`/api/agency/work-orders/${order}`,'PATCH',{drive_links:'https://drive.google.com/file/d/order\nhttps://drive.google.com/drive/folders/assets'});assert.equal(linksResult.workOrder.drive_links.length,2);assert.equal(linksResult.workOrder.drive_url,'https://drive.google.com/file/d/order');
assert.equal((await call(`/api/agency/work-orders/${order}`,'PATCH',{drive_links:Array.from({length:11},(_,i)=>({url:`https://drive.google.com/${i}`}))})).status,400);
assert.equal((await call(`/api/agency/work-orders/${order}`,'PATCH',{status:'approved'})).status,400);
assert.equal((await call(`/api/agency/work-orders/${order}/approve`,'POST',{}, {...user,role:'editor'})).status,403);
assert.equal((await call(`/api/agency/work-orders/${order}/approve`,'POST')).status,200);
assert.equal((await call(`/api/agency/work-orders/${order}/approve`,'POST')).status,200);
assert.equal((await call(`/api/agency/work-orders/${order}/publish`,'POST')).status,200);
assert.equal((await call(`/api/agency/work-orders/${order}`,'PATCH',{status:'editing'}, {...user,role:'editor'})).workOrder.approval_step,0);
assert.equal((await call('/api/agency/dashboard','GET',{}, {...user,role:'sales'})).status,403);
assert.equal((await call(`/api/agency/members/${uid}`,'PATCH',{active:false})).status,400);
assert.equal((await call(`/api/agency/members/${viewer}`,'PATCH',{active:false})).status,200);
const access=await collaboratorAccess({query},{email:'suite-viewer@example.invalid',org,actorRole:'owner',active:true});assert.equal(access.status,'suspended');
let r=await call('/api/agency/leads','POST',{name:'Prospect',amount:1000,currency:'USD'});assert.equal(r.status,201);const lead=r.record.id;
const converted=await call(`/api/agency/leads/${lead}/convert`,'POST');assert.equal(converted.status,200);assert.equal((await call(`/api/agency/leads/${lead}/convert`,'POST')).clientId,converted.clientId);
assert.equal((await call('/api/agency/leads','GET',{}, {...user,organization_id:other})).records.length,0);
r=await call('/api/agency/inventory','POST',{name:'Camera',value:2000,currency:'USD'});assert.equal(r.status,201);
assert.equal((await call('/api/agency/plans','POST',{name:'Plan',items:[{description:'Video',quantity:2,unitPrice:100}],currency:'USD'})).status,201);
assert.equal((await call('/api/agency/plans','POST',{name:'Invalid',items:[]})).status,400);
assert.equal((await call('/api/agency/exchange-rates','POST',{rate_date:'2026-09-08',usd_to_pyg:7500})).status,200);
assert.equal((await call('/api/agency/dashboard')).inventory[0].total,'2000.00');
await query("insert into agency_user_profiles(organization_id,user_id,full_name,photo_url) values($1,$2,'Autor local','https://example.invalid/actor.png')",[org,uid]);
const activity=await call('/api/agency/activity');assert.equal(activity.status,200);assert.ok(activity.records.length>=5);
const authored=activity.records.find(row=>row.actor===String(uid));assert.equal(authored.actor_name,'Autor local');assert.equal(authored.actor_photo_url,'https://example.invalid/actor.png');assert.equal(authored.actor_verified,true);
assert.equal((await call('/api/agency/activity','GET',{}, {...user,role:'viewer'})).status,403);
assert.equal((await call('/api/agency/activity','GET',{},null)).status,401);
assert.equal((await call('/api/agency/activity','GET',{}, {...user,organization_id:other})).records.length,0);
const token='a'.repeat(32);const budget=(await query("insert into agency_budgets(organization_id,client_id,number,title,currency,subtotal,total,public_token) values($1,$2,'Q-TEST','Quote','USD',200,220,$3) returning id",[org,client,token])).rows[0].id;
await query("insert into agency_budget_items(budget_id,position,description,quantity,unit_price,total) values($1,1,'Video',2,100,200)",[budget]);
assert.equal((await call('/p/'+token)).status,404);
assert.equal((await call(`/api/agency/budgets/${budget}/share`,'POST')).status,200);
r=await call('/p/'+token);assert.equal(r.status,200);assert.ok(r.content.includes('Q-TEST'));
assert.equal((await call('/p/'+token+'/respond','POST',{},null,'name=Customer&action=accept&revision=1')).status,303);
assert.equal((await call('/p/'+token+'/respond','POST',{},null,'name=Customer&action=accept&revision=1')).status,409);
assert.equal((await call(`/api/agency/budgets/${budget}`,'PATCH',{title:'Changed',items:[{description:'Something',quantity:1,unitPrice:1}]})).status,400);
const invoice=await call(`/api/agency/budgets/${budget}/invoice`,'POST');assert.equal(invoice.status,200);assert.equal((await call(`/api/agency/budgets/${budget}/invoice`,'POST')).invoice.id,invoice.invoice.id);
assert.equal((await call(`/api/agency/budgets/${budget}/revoke`,'POST')).status,200);assert.equal((await call('/p/'+token)).status,404);
const escaped=budgetDocument({number:'T',title:'<script>alert(1)</script>',organization_name:'Test',client_name:'Client',currency:'USD',subtotal:10,total:11,tax_rate:.1},[]);assert.ok(!escaped.includes('<script>'));assert.ok(escaped.includes('&lt;script&gt;'));
r=await call('/api/auth/password/request','POST',{email:'unknown@example.invalid'});assert.equal(r.status,202);assert.equal(sent,0);
assert.equal((await call('/api/auth/password/request','POST',{email:'suite-owner@example.invalid'})).status,202);assert.equal(sent,1);assert.equal(resetToken.length,64);
assert.equal((await call('/api/auth/password/reset','POST',{token:resetToken,password:'new-test-password-1234'})).status,200);
assert.equal((await call('/api/auth/password/reset','POST',{token:resetToken,password:'new-test-password-1234'})).status,400);
await pg.close();console.log('PASS: approvals, member suspension, tenant isolation, pipeline conversion, plans, inventory, dashboard permissions, public quotes, invoice idempotency, audit and password reset');
