import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {rucLookup,normalizeRuc,rucRecord,assertUniqueClientRuc,createRucProvider} from './ruc-lookup.js';

assert.equal(normalizeRuc('80.168.807 - 8'),'80168807-8');assert.equal(normalizeRuc('1234567'),'1234567');assert.throws(()=>normalizeRuc('https://evil.example'));
const providerRecord={name:'Empresa de prueba',ruc:'80168807',dv:'8',fullRuc:'80168807-8',state:'ACTIVO'};
assert.equal(rucRecord(providerRecord,'80168807').tax_id,'80168807-8');assert.throws(()=>rucRecord(providerRecord,'1234567'));
const pg=new PGlite();await pg.exec(await fs.readFile('schema.sql','utf8'));for(const file of ['20260910_ruc_lookup.sql','20260913_ruc_collaboration.sql'])await pg.exec(await fs.readFile('migrations/'+file,'utf8'));
const query=(s,v)=>pg.query(s,v),db={connect:async()=>({query,release(){}})};
const org=(await query("select id from organizations where slug='scale'")).rows[0].id;
await query("update scale_ruc_usage set used=0 where month=date_trunc('month',current_date)::date");
let calls=0,result;const user={id:1,organization_id:org,role:'owner'};
const config={providerUrl:'https://provider.example/ruc',timeoutMs:1000,cacheTtlSeconds:3600,noResultTtlSeconds:3600,monthlyLimit:2};
const provider={lookup:async ruc=>{calls++;if(ruc==='00000000-0')return null;if(ruc==='99999999-9')throw Object.assign(Error('private upstream detail'),{status:503});return providerRecord;}};
async function call(path,b={ruc:'80168807-8'},as=user){await rucLookup({req:{method:'POST',socket:{}},res:{},url:new URL('https://test/api/agency/'+path),db,session:async()=>as,body:async()=>b,send:(_,status,data)=>{result={status,...data};},provider,config});return result;}
assert.equal((await call('ruc-lookup',undefined,null)).status,401);
assert.equal((await call('ruc-lookup',undefined,{...user,role:'editor'})).status,403);assert.equal(calls,0);
assert.equal((await call('ruc-lookup',undefined,{...user,demo_owner_user_id:1})).status,403);
let found=await call('ruc-lookup');assert.equal(found.status,200);assert.equal(found.record.tax_id,'80168807-8');assert.equal(found.cached,false);assert.equal(calls,1);
found=await call('ruc-lookup');assert.equal(found.cached,true);assert.equal(calls,1,'cache avoids provider and quota consumption');
found=await call('ruc-lookup',{ruc:'00000000-0'});assert.deepEqual(found.record,null);assert.equal(found.status,200);assert.equal(calls,2);
found=await call('ruc-lookup',{ruc:'00000000-0'});assert.equal(found.cached,true);assert.equal(calls,2,'no-result is safely cached');
found=await call('ruc-lookup',{ruc:'99999999-9'});assert.equal(found.status,429,'only uncached external calls consume the configured quota');
await query("update scale_ruc_usage set used=0 where month=date_trunc('month',current_date)::date");
found=await call('ruc-lookup',{ruc:'99999999-9'});assert.equal(found.status,503);assert(!found.error.includes('private upstream detail'),'provider details never reach callers');
await query("update scale_ruc_usage set used=0 where month=date_trunc('month',current_date)::date");
const payload={ruc:'80168807-8',name:'Cliente de prueba',legal_name:'Razón escrita por una persona'};
assert.equal((await call('clients/from-ruc',payload)).status,201);
assert.equal((await call('clients/from-ruc',payload)).status,409);
assert.equal((await call('clients/from-ruc',{...payload,ruc:'80168807'})).status,400);
const client=(await query('select * from agency_clients where organization_id=$1',[org])).rows[0];
let refresh=await call(`clients/${client.id}/ruc-refresh`,{});assert.equal(refresh.status,200);assert.equal(refresh.updated,false);assert.equal(refresh.client.legal_name,'Razón escrita por una persona','preview never overwrites user fields');
refresh=await call(`clients/${client.id}/ruc-refresh`,{apply:true});assert.equal(refresh.updated,true);assert.equal(refresh.client.legal_name,'Razón escrita por una persona');assert.equal(refresh.client.ruc_legal_name,'Empresa de prueba');assert.equal(calls,5,'explicit refresh bypasses cache');
await assert.rejects(()=>assertUniqueClientRuc({query},org,'80.168.807-8'),error=>error.status===409);
await assert.doesNotReject(()=>assertUniqueClientRuc({query},org,'80168807-8',client.id));
assert.equal(await createRucProvider({baseUrl:'https://provider.example/ruc',fetcher:async()=>new Response('',{status:404})}).lookup('123'),null);
await pg.close();console.log('PASS: configured provider abstraction, normalization, cache/no-result safety, quota, and explicit non-destructive client refresh');
