import React from 'react';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {act,create} from 'react-test-renderer';
import postcss from 'postcss';
Object.assign(globalThis,{React});
require.extensions['.css']=()=>{};
const {AssignedPeople}=require('../app/assigned-people') as typeof import('../app/assigned-people');
const {ActorIdentity}=require('../app/actor-identity') as typeof import('../app/actor-identity');
const people=Array.from({length:8},(_,i)=>({id:String(i+1),full_name:`Persona ${i+1} con nombre completo muy largo`,photo_url:`https://example.invalid/${i}.webp`,is_primary:i===0}));
const view=create(<AssignedPeople people={people.slice(0,5)}/>);
assert.equal(view.root.findAllByType('li').length,5,'five people remain visible');
assert.equal(view.root.findAllByType('img').length,5,'all five photos render');
assert.equal(view.root.findAllByType(ActorIdentity).length,5,'shared identity implementation');
for(const p of people.slice(0,5))assert.ok(JSON.stringify(view.toJSON()).includes(p.full_name));
assert.equal(view.root.findByType('section').props['aria-label'],'Responsables asignados');
assert.ok(view.root.findAllByType('img').every(img=>img.props.alt===''),'photos do not duplicate spoken names');
assert.equal(view.root.findAllByProps({className:'assigned-person-primary'}).length,1);
view.update(<AssignedPeople people={people}/>);
assert.equal(view.root.findAllByType('li').length,8,'additional people are not hidden behind a count');
assert.equal(view.root.findAllByType('button').length,0,'display does not add unrelated actions');
assert.equal(view.root.findAllByType('i').length,0,'assignment never adds presence indicators');
act(()=>view.root.findAllByType('img')[0].props.onError());
assert.equal(view.root.findAllByType('img').length,7,'failed image falls back without dropping its name');
view.update(<AssignedPeople people={[{id:'20',full_name:null,email:'verified@example.invalid',photo_url:'javascript:alert(1)',is_primary:false}]}/>);
assert.equal(view.root.findAllByType('img').length,0);assert.match(JSON.stringify(view.toJSON()),/verified@example.invalid/);
view.update(<AssignedPeople people={[{id:'21',is_primary:false}]}/>);
assert.match(JSON.stringify(view.toJSON()),/Integrante sin nombre/);assert.doesNotMatch(JSON.stringify(view.toJSON()),/Sistema/);
for(const people of [undefined,null]){view.update(<AssignedPeople people={people}/>);assert.match(JSON.stringify(view.toJSON()),/Responsables no disponibles/);assert.equal(view.root.findAllByType('li').length,0);}
view.update(<AssignedPeople people={[]}/>);assert.match(JSON.stringify(view.toJSON()),/Sin responsables/);
view.update(<AssignedPeople people={people} error="No se pudo comprobar la asignación."/>);
assert.match(JSON.stringify(view.toJSON()),/Responsables no disponibles/);assert.equal(view.root.findAllByType('li').length,0,'an error does not present stale identities as current');
view.update(<AssignedPeople people={people} loading/>);
assert.equal(view.root.findByType('section').props['aria-busy'],true);assert.match(JSON.stringify(view.toJSON()),/Cargando responsables/);
view.unmount();
const css=postcss.parse(readFileSync(new URL('../app/assigned-people.css',import.meta.url),'utf8'));
const declarations=(selector:string)=>{const values:Record<string,string>={};css.walkRules(rule=>{if(rule.selectors.includes(selector))rule.walkDecls(d=>{values[d.prop]=d.value;});});return values;};
assert.equal(declarations('.assigned-people .assigned-people-list')['flex-wrap'],'wrap');
assert.equal(declarations('.assigned-people .assigned-person')['min-width'],'0');
assert.equal(declarations('.assigned-people .actor-identity-name')['white-space'],'nowrap');
assert.equal(declarations('.assigned-people .actor-identity-name')['text-overflow'],'ellipsis');
css.walkDecls(d=>{assert.notEqual(d.prop,'max-height');assert.ok(!/#(?:[0-9a-f]{3}){1,2}\b/i.test(d.value),'semantic colors');});
console.log('PASS: five/all assigned people, full names, shared photos/fallback, honest states, no presence/actions and wrapping token-based CSS');
