import React from 'react';
import assert from 'node:assert/strict';
import {act,create,type ReactTestRenderer} from 'react-test-renderer';
require.extensions['.css']=()=>{};
Object.assign(globalThis,{React});
const operationsPath=require.resolve('../app/operations');
const writes:{path:string;body:any;method:string}[]=[];
let currentTerms:unknown=null,archived=false;
const mockApi=async(path:string,body?:unknown,method='POST')=>{
 if(body!==undefined){writes.push({path,body,method});return {clientId:'1',archived,terms:currentTerms,plans:[{id:'7',name:'Mensual',currency:'PYG'}],collaborators:[]};}
 if(path.endsWith('/commercial-terms'))return {clientId:'1',archived,terms:currentTerms,plans:[{id:'7',name:'Mensual',currency:'PYG'}],collaborators:[]};
 throw new Error('unexpected GET '+path);
};
require.cache[operationsPath]={id:operationsPath,filename:operationsPath,loaded:true,exports:{api:mockApi}} as NodeModule;
const {ClientPlanTerms}=require('../app/client-plan-terms') as typeof import('../app/client-plan-terms');
let renderer:ReactTestRenderer;
const termsFixture={clientId:'1',planId:'7',planName:'Mensual',recurringAmount:'1200000',currency:'PYG',startsOn:'2024-01-15',endsOn:null,invoiceRequired:true,commissionRecipientId:'9',commissionRecipientName:'Ana',commissionMode:'percentage',commissionValue:'10',updatedAt:'2026-09-10T12:00:00Z'};
const render=(role:string)=>act(async()=>{renderer=create(<ClientPlanTerms id="1" role={role} refresh={async()=>{}}/>);});
const flush=()=>act(async()=>{});
const selects=()=>renderer.root.findAllByType('select');
const inputs=()=>renderer.root.findAllByType('input');
const text=()=>JSON.stringify(renderer.toJSON());
const submit=()=>act(async()=>{await renderer.root.findByType('form').props.onSubmit({preventDefault(){}});});
async function run(){
 currentTerms=termsFixture;archived=false;
 for(const role of ['management','sales','finance','editor','viewer','production','']){await render(role);await flush();assert.equal(renderer.toJSON(),null,`${role} never sees plan and payment`);act(()=>renderer.unmount());}
 assert.equal(writes.length,0,'forbidden roles never fetch nor write');
 await render('owner');await flush();
 assert.equal(selects()[0].props.value,'7','the saved plan is preselected');
 const amount=inputs().find(input=>input.props.placeholder==='1.000.000')!;
 assert.equal(amount.props.value,'1.200.000','the saved amount renders with thousand separators');
 assert.equal(inputs().find(input=>input.props.type==='date')!.props.value,'2024-01-15');
 assert.match(text(),/Solo administración y finanzas pueden ver este importe/);
 act(()=>amount.props.onChange({target:{value:'2.500.000'}}));
 act(()=>selects()[3].props.onChange({target:{value:'false'}}));
 act(()=>inputs().filter(input=>input.props.type==='date')[1].props.onChange({target:{value:'2024-03-31'}}));
 await submit();
 assert.equal(writes.length,1);assert.equal(writes[0].path,'/api/agency/clients/1/commercial-terms');assert.equal(writes[0].method,'PATCH');
 assert.deepEqual(writes[0].body,{planId:'7',recurringAmount:'2500000',currency:'PYG',startsOn:'2024-01-15',endsOn:'2024-03-31',cadence:'monthly',intervalMonths:1,invoiceRequired:false,commissionRecipientId:'9',commissionMode:'percentage',commissionValue:'10'},'existing commission, cadence and dates are preserved');
 assert.match(text(),/Plan y pago guardados/);
 let before=writes.length;
 act(()=>selects()[0].props.onChange({target:{value:'abc'}}));
 await submit();
 assert.match(text(),/Elegí un plan/);assert.equal(writes.length,before,'invalid plan never reaches the API');
 act(()=>selects()[0].props.onChange({target:{value:'7'}}));
 act(()=>inputs().find(input=>input.props.placeholder==='1.000.000')!.props.onChange({target:{value:'0'}}));
 await submit();
 assert.match(text(),/entero positivo/);assert.equal(writes.length,before,'zero amount never reaches the API');
 act(()=>inputs().find(input=>input.props.placeholder==='1.000.000')!.props.onChange({target:{value:'100'}}));
 act(()=>inputs().filter(input=>input.props.type==='date')[1].props.onChange({target:{value:'2024-01-01'}}));
 await submit();
 assert.match(text(),/posterior al inicio/);assert.equal(writes.length,before,'an end before the start never reaches the API');
 act(()=>renderer.unmount());
 currentTerms=null;
 await render('owner');await flush();
 assert.equal(selects()[0].props.value,'');assert.equal(inputs().find(input=>input.props.placeholder==='1.000.000')!.props.value,'');
 act(()=>selects()[0].props.onChange({target:{value:'7'}}));
 act(()=>inputs().find(input=>input.props.placeholder==='1.000.000')!.props.onChange({target:{value:'800000'}}));
 act(()=>inputs().find(input=>input.props.type==='date')!.props.onChange({target:{value:'2026-09-01'}}));
 act(()=>selects()[3].props.onChange({target:{value:'false'}}));
 await submit();
 assert.deepEqual(writes.at(-1)!.body,{planId:'7',recurringAmount:'800000',currency:'PYG',startsOn:'2026-09-01',endsOn:null,cadence:'monthly',intervalMonths:1,invoiceRequired:false,commissionRecipientId:null,commissionMode:'none',commissionValue:null},'new terms start without commission');
 act(()=>renderer.unmount());
 currentTerms=termsFixture;archived=true;
 await render('owner');await flush();
 assert.match(text(),/solo lectura/i);assert.equal(renderer.root.findAllByType('form').length,0,'archived clients never render the form');
 act(()=>renderer.unmount());
 console.log('PASS client plan terms: role gating, canonical terms PATCH with preserved commission, validation, new-terms payload and archived read-only');
}
void run();
