import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {clientState,clientStatuses} from '../app/client-status';
assert.equal(clientState({active:true}).value,'active');
assert.equal(clientState({active:false}).value,'inactive');
for(const state of clientStatuses)assert.equal(clientState({active:false,lifecycle_status:state.value}).label,state.label);
const history=readFileSync('app/work-history.tsx','utf8');
assert(history.includes("useState('10')"));assert(history.includes('new URLSearchParams({limit,offset:String(offset)})'));assert(history.includes('[who,source,limit,offset,identityVersion]'));assert(!history.includes('Últimos 100'));
const sidebar=readFileSync('app/desktop-sidebar.tsx','utf8');assert(sidebar.includes('aria-expanded={!collapsed}'));assert(sidebar.includes('localStorage.setItem'));assert(sidebar.includes('Expandir barra lateral'));
assert(sidebar.includes('md:!w-[60px]')&&sidebar.includes('md:!w-48'),'the rail keeps its collapsed and expanded widths on the md frame breakpoint');
const shell=readFileSync('app/scale-workspace.tsx','utf8');assert(shell.includes('content flex min-h-dvh min-w-0 flex-1 flex-col'),'the content takes the remaining width by flex, independent of the rail state');assert(!shell.includes('max-w-[1600px]'),'the content no longer caps its width and leaves unused space');
console.log('PASS: client state labels/fallbacks, server pagination wiring, persistent accessible sidebar and mobile guard');
