import React from 'react';
import assert from 'node:assert/strict';
import {act,create,type ReactTestRenderer,type ReactTestInstance} from 'react-test-renderer';
import type {InventoryItem,InventoryReservation,StorageTemplate} from '../app/inventory-workspace';
const {SelectCustom}=require('../app/profile-controls') as typeof import('../app/profile-controls');
Object.assign(globalThis,{React});require.extensions['.css']=()=>{};
const intervals=new Map<number,()=>void>();let timerId=0;
const documentEvents=Object.assign(new EventTarget(),{visibilityState:'visible'});
Object.defineProperty(globalThis,'document',{configurable:true,value:documentEvents});
Object.defineProperty(globalThis,'window',{configurable:true,value:{setInterval(callback:()=>void,ms:number){assert.equal(ms,30000);intervals.set(++timerId,callback);return timerId;},clearInterval(id:number){intervals.delete(id);},dispatchEvent(){return true;}}});
const context={user_id:'10',role:'production',can_manage:false,can_reserve:true,time_zone:'America/Asuncion',members:[{id:'10',name:'Cámara'},{id:'11',name:'Sonido'}],projects:[{id:'20',name:'Proyecto de prueba'}]};
const equipment:InventoryItem[]=[{id:'1',name:'Memoria SD',category:'Memoria',category_id:'1',serial_number:null,value:'0',currency:'PYG',status:'available',storage_shelf:'Estante A',storage_row:'2',custodian_user_id:null,location_type:'storage'},{id:'2',name:'DJI Mic',category:'Audio',category_id:'2',serial_number:null,value:'100',currency:'USD',status:'available',storage_shelf:'Estante B',storage_row:'1',custodian_user_id:null,location_type:'storage'}];
const record:InventoryReservation={id:'30',title:'Rodaje de prueba',project_id:'20',project_name:'Proyecto de prueba',starts_at:'2026-09-10T12:00:00.000Z',ends_at:'2026-09-10T15:00:00.000Z',status:'reserved',created_by_user_id:'10',return_user_id:'11',return_user_name:'Sonido',custodian_user_id:null,custodian_name:null,responsible_members:context.members,items:equipment.map(i=>({id:i.id,name:i.name,storage_shelf:i.storage_shelf,storage_row:i.storage_row})),notes:'',version:0};
const writes:{path:string;body:any;method:string}[]=[];let reads=0,fail=false,delay=false;
const pending:(()=>void)[]=[];
let delayWrites=false;
const pendingWrites:(()=>void)[]=[];
let items=equipment,reservations=[record];
let categories=[{id:'1',name:'Memoria',active:true},{id:'2',name:'Audio',active:true}];
let storageTemplates:StorageTemplate[]=[{id:'storage-a',name:'Estante A',active:true,item_count:1},{id:'storage-b',name:'Estante B',active:true,item_count:0},{id:'storage-old',name:'Depósito anterior',active:false,item_count:2}];
const mockApi=async(path:string,body?:unknown,method='POST')=>{
 if(body!==undefined||method==='DELETE'){writes.push({path,body,method});if(delayWrites)await new Promise<void>(resolve=>pendingWrites.push(resolve));if(fail)throw new Error('Conflicto de reserva');if(path==='/api/agency/inventory-locations')return {location:{id:'storage-new',name:(body as {name:string}).name,active:true,item_count:0}};return {reservation:record};}
 reads++;if(delay)await new Promise<void>(resolve=>pending.push(resolve));if(fail)throw new Error('Sin conexión');
 if(path.endsWith('/inventory-context'))return context;
 if(path.endsWith('/inventory-categories'))return {categories};
 if(path.endsWith('/inventory-locations'))return {locations:storageTemplates};
 if(/\/inventory\/\d+$/.test(path))return {record:items.find(entry=>path.endsWith(`/${entry.id}`))||items[0],verifications:[],trace:[],maintenance:[]};
 if(path.endsWith('/inventory'))return {records:items};
 return {reservations};
};
// Dialog/editor behavior is covered by existing tests. Keep these tests focused
// on the inventory contract, reservation drafts, permissions and polling.
const operationsPath=require.resolve('../app/operations');
const MockEditor=()=>null;
const CloseContext=React.createContext<(()=>void)|undefined>(undefined);
const pendingStates:boolean[]=[];
function MockDialog({children,close,busy=false}:{children:React.ReactNode;close:()=>void;busy?:boolean}){return <CloseContext.Provider value={close}><section role="dialog" aria-busy={busy}>{children}</section></CloseContext.Provider>;}
require.cache[operationsPath]={id:operationsPath,filename:operationsPath,loaded:true,exports:{api:mockApi,money:(n:string,c:string)=>`${c} ${n}`,Dialog:MockDialog,Editor:MockEditor}} as NodeModule;
const dialogPath=require.resolve('../app/dialog');
require.cache[dialogPath]={id:dialogPath,filename:dialogPath,loaded:true,exports:{FormActions:({children}:{children:React.ReactNode})=><div>{children}</div>,useDialogClose:()=>React.useContext(CloseContext),useDialogPending:(value:boolean)=>{pendingStates.push(value);}}} as NodeModule;
const {InventoryWorkspace,InventoryItemForm,InventoryReservationForm,InventoryTransitionForm,InventoryCalendar,InventoryDetail}=require('../app/inventory-workspace') as typeof import('../app/inventory-workspace');
let renderer:ReactTestRenderer,done=0;
function text(node:ReactTestInstance|string):string{return typeof node==='string'?node:node.children.map(text).join('');}
const button=(label:string)=>renderer.root.findAllByType('button').find(node=>text(node)===label)!;
const byLabel=(value:string,tag:'input'|'select'|'textarea'='input'):ReactTestInstance|undefined=>{
 const label=renderer.root.findAllByType('label').find(node=>text(node).includes(value));
 if(!label)return undefined;
 const htmlFor=label.props.htmlFor;
 if(htmlFor){const found=renderer.root.findAll(node=>node.props?.id===htmlFor&&typeof node.type==='string');if(found.length)return found[0];}
 return label.findAllByType(tag)[0];
};
const select=(value:string)=>renderer.root.findAllByType(SelectCustom).find(node=>node.props.label===value)!;
const change=(label:string,value:string,tag:'input'|'select'|'textarea'='input')=>act(()=>{
 const field=byLabel(label,tag)||renderer.root.findAll(node=>node.props?.['aria-label']===label&&typeof node.type==='string'&&['input','textarea','select'].includes(String(node.type)))[0];
 if(field)return field.props.onChange({target:{value},currentTarget:{value,selectionStart:String(value).length}});
 return select(label).props.onChange(value);
});
// Identity chips now include avatar initials before the visible person name.
const check=(label:string)=>act(()=>renderer.root.findAllByType('label').find(node=>text(node).includes(label))!.findByType('input').props.onChange({target:{checked:true}}));
const tree=()=>JSON.stringify(renderer.toJSON());
const submit=()=>act(async()=>{await renderer.root.findByType('form').props.onSubmit({preventDefault(){}});});
const viewButton=(label:string)=>renderer.root.findAllByType('button').find(node=>node.props['aria-label']===label)!;
const listHeader=()=>renderer.root.findAll(node=>node.props?.['aria-hidden']==='true'&&text(node).includes('Artículo'));
async function run(){
 // Reservation drafts: validation, payload and error retention.
 await act(async()=>{renderer=create(<InventoryReservationForm context={context} items={equipment} record={null} done={()=>{done++;}}/>);});
 change('Producción o uso previsto','Rodaje de productos');change('Proyecto','20','select');change('Desde · Asunción','2026-09-10T09:00');change('Devolución prevista · Asunción','2026-09-10T12:00');
 await submit();assert.match(tree(),/Elegí al menos un equipo/);assert.equal(writes.length,0);
 check('Memoria SD');check('DJI Mic');check('Sonido');change('Responsable de devolución','11','select');
 await submit();assert.equal(done,1);assert.deepEqual(writes[0].body.inventory_ids,['1','2']);assert.deepEqual(writes[0].body.responsible_user_ids,['10','11']);assert.equal(writes[0].body.return_user_id,'11');assert.equal(writes[0].body.starts_at,'2026-09-10T12:00:00.000Z');
 fail=true;await submit();assert.match(tree(),/Conflicto de reserva/);assert.equal(byLabel('Producción o uso previsto')!.props.value,'Rodaje de productos');fail=false;
 check('Sonido');assert.equal(select('Responsable de devolución').props.value,'','removing assigned returner clears the assignment');
 const beforeInvalid=writes.length;await submit();assert.equal(writes.length,beforeInvalid,'invalid responsibility cannot submit');
 check('Sonido');change('Responsable de devolución','11','select');
 act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryReservationForm context={context} items={[equipment[0],{...equipment[1],status:'maintenance'}]} record={record} done={()=>{done++;}}/>);});
 assert.equal(byLabel('Producción o uso previsto')!.props.value,record.title);assert.equal(select('Responsable de devolución').props.value,'11');
 check('DJI Mic');
 const unavailable=renderer.root.findAllByType('label').find(node=>text(node).startsWith('DJI Mic'))!.findByType('input');
 assert.equal(unavailable.props.disabled,true,'unavailable equipment can be deselected from an old draft but not selected anew');
 await submit();assert.equal(writes.at(-1)!.method,'PATCH');assert.equal(writes.at(-1)!.body.expected_version,record.version);assert.deepEqual(writes.at(-1)!.body.inventory_ids,['1']);
 act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryTransitionForm action="checkout" record={record} done={()=>{done++;}}/>);});
 assert.deepEqual(select('Quién lleva los equipos (custodio)').props.choices.map((choice:{value:string})=>choice.value),['','10','11']);
 change('Quién lleva los equipos (custodio)','11','select');await submit();assert.equal(writes.at(-1)!.body.custodian_user_id,'11');assert.equal(writes.at(-1)!.path,'/api/agency/inventory-reservations/30/checkout');act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryTransitionForm action="return" record={{...record,status:'checked_out'}} done={()=>{done++;}}/>);});
 assert.equal(renderer.root.findAllByType('fieldset').length,2);
 assert.match(tree(),/devolución completa/,'partial return is not represented as supported');
 const returnFields=renderer.root.findAllByType('fieldset');
 act(()=>returnFields[0].findAllByType('input')[0].props.onChange({target:{value:'Estante nuevo'}}));
 act(()=>returnFields[1].findByType(SelectCustom).props.onChange('maintenance'));
 await submit();assert.equal(writes.at(-1)!.path,'/api/agency/inventory-reservations/30/return');assert.equal(writes.at(-1)!.body.locations.length,2);assert.equal(writes.at(-1)!.body.expected_version,0);
 assert.equal(writes.at(-1)!.body.locations[0].storage_shelf,'Estante nuevo');assert.equal(writes.at(-1)!.body.locations[1].status,'maintenance');
 fail=true;const beforeDone=done;await submit();assert.equal(done,beforeDone);assert.equal(returnFields[0].findAllByType('input')[0].props.value,'Estante nuevo','failed return retains recorded locations');fail=false;
 act(()=>renderer.unmount());
 // Exclusive end at midnight occupies only the preceding calendar day.
 await act(async()=>{renderer=create(<InventoryCalendar month="2026-09" reservations={[{...record,starts_at:'2026-09-10T23:00:00.000Z',ends_at:'2026-09-11T03:00:00.000Z'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2026-09-10'})),/Rodaje de prueba/);assert.doesNotMatch(text(renderer.root.findByProps({'aria-label':'2026-09-11'})),/Rodaje de prueba/);act(()=>renderer.unmount());
 const yearBoundary={...record,starts_at:'2033-01-01T01:00:00.000Z',ends_at:'2033-01-01T03:00:00.000Z'};
 await act(async()=>{renderer=create(<InventoryCalendar month="2032-12" reservations={[yearBoundary,{...yearBoundary,id:'31',status:'cancelled',title:'Cancelada invisible'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2032-12-31'})),/Rodaje de prueba/);assert.doesNotMatch(tree(),/Cancelada invisible/);act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryCalendar month="2033-01" reservations={[yearBoundary]}/>);});assert.doesNotMatch(tree(),/Rodaje de prueba/);act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryCalendar month="2032-02" reservations={[{...record,starts_at:'2032-02-29T12:00:00.000Z',ends_at:'2032-03-01T03:00:00.000Z'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2032-02-29'})),/Rodaje de prueba/);assert.equal(renderer.root.findAllByType('time').length,29);act(()=>renderer.unmount());
 // inventory.view covers every role, so sales and collaborators open the catalog too.
 const before=reads;await act(async()=>{renderer=create(<InventoryWorkspace role="sales"/>);});assert.notEqual(renderer.toJSON(),null,'sales reaches the inventory catalog');assert(reads>before,'the catalog is requested');act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryWorkspace role="collaborator"/>);});assert.notEqual(renderer.toJSON(),null,'collaborator reaches the inventory catalog');act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryWorkspace role="guest"/>);});assert.equal(renderer.toJSON(),null,'a role outside the capability renders nothing');act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryWorkspace role="production"/>);});
 assert.equal(intervals.size,1);assert.match(text(renderer.root),/Sincroniza cada 30 s/);assert.match(text(renderer.root),/Estante A/);assert.doesNotMatch(text(renderer.root),/Cargando inventario/);assert.doesNotMatch(text(renderer.root),/Ubicaciones de guardado/,'storage management controls stay hidden outside manager roles');
 const tabs=renderer.root.findByProps({'aria-label':'Vistas de inventario'}).findAllByType('button');assert.equal(tabs.length,2);assert.equal(tabs[0].props['aria-pressed'],true);assert.equal(tabs[1].props['aria-pressed'],false);
 const viewControl=renderer.root.findByProps({'aria-label':'Vista de inventario'});
 let viewButtons=viewControl.findAllByType('button');assert.equal(viewButtons.length,3,'grid, list and pipeline are the equipment views');assert(viewButtons.every(node=>node.props['aria-label']&&node.props['aria-pressed']!==undefined),'view controls retain accessible labels and selected state');
 act(()=>viewButton('Lista').props.onClick());assert.equal(listHeader().length,1,'the list shows a column header row');for(const col of ['Foto','Artículo','Detalles','Valor','Estado','Ubicación','Verificación','Acciones'])assert.match(text(listHeader()[0]),new RegExp(col),`${col} column header is present`);
 assert.equal(viewButton('Lista').props['aria-pressed'],true);
 act(()=>viewButton('Cuadrícula').props.onClick());assert.equal(listHeader().length,0,'the column header belongs to the list view only');
 assert.match(text(renderer.root),/2 equipos visibles/);change('Buscar equipo o ubicación','Mic');assert.match(text(renderer.root),/1 equipo visible/,'the compact count tracks the filter');change('Buscar equipo o ubicación','');
 act(()=>viewButton('Ubicaciones').props.onClick());
 assert.match(tree(),/Estante B/,'every active location appears in the pipeline even when empty');
 assert.match(tree(),/Depósito anterior/,'an archived location still appears while it holds equipment');
 assert.match(tree(),/Sin verificación física/);assert.match(tree(),/Sin registro de ingreso a esta ubicación/);
 assert.match(tree(),/Sin equipos/,'empty location columns render with their count at zero');
 assert.match(tree(),/Sin ubicación/,'the unassigned column always exists so items can move back');
 act(()=>{renderer.root.findAllByProps({'aria-label':'Ocultar columna Sin ubicación'})[0].props.onClick();});
 assert.doesNotMatch(tree(),/Sin ubicación/,'the unassigned column can be hidden from the pipeline');
 assert.match(tree(),/sin ubicación no se muestran/,'hiding reports how many unassigned items are out of view');
 act(()=>{button('Mostrar columna').props.onClick();});
 assert.match(tree(),/Sin ubicación/,'the unassigned column can be restored');
 items=[{...equipment[0],storage_location_id:'storage-a',storage_location_name:'Estante A',storage_shelf:'Estante A',location_changed_at:'2026-09-14T12:00:00.000Z',last_verified_at:'2026-09-15T10:00:00.000Z',last_verifier_name:'Rita Mical Herrera',last_verification_result:'confirmed'},equipment[1]];
 await act(async()=>{intervals.forEach(callback=>callback());});
 assert.match(tree(),/Control:/,'the verified icon keeps the control status accessible');
 assert.match(tree(),/Aquí desde/);assert.match(tree(),/Rita/,'cards show the verifier first name');
 assert.match(tree(),/07:00/,'the control stamp renders the Asunción time in 24-hour format');
 assert.doesNotMatch(tree(),/a\. m\.|p\. m\./,'no meridiem markers in the inventory stamps');
 items=equipment;await act(async()=>{intervals.forEach(callback=>callback());});
 act(()=>viewButton('Cuadrícula').props.onClick());
 act(()=>tabs[0].props.onClick());
 act(()=>button('Reservar equipos').props.onClick());change('Producción o uso previsto','Borrador que debe sobrevivir');check('Memoria SD');
 delay=true;const beforePoll=reads;
 act(()=>intervals.forEach(callback=>callback()));act(()=>intervals.forEach(callback=>callback()));
 assert.equal(reads,beforePoll+5,'a polling cycle waits for all five requests; a second tick cannot overlap');
 assert.doesNotMatch(text(renderer.root),/Cargando inventario/,'background updates retain visible content');
 items=[{...equipment[0],location_type:'checked_out',current_custodian_name:'Otra persona',production_name:'Otra producción'},equipment[1]];
 await act(async()=>{pending.splice(0).forEach(resolve=>resolve());});delay=false;
 assert.match(text(renderer.root),/Con Otra persona/);assert.equal(byLabel('Producción o uso previsto')!.props.value,'Borrador que debe sobrevivir');
 const selected=renderer.root.findAllByType('input').filter(node=>node.props.type==='checkbox'&&node.props.checked);assert(selected.length>=2,'selected equipment and own responsibility persist');
 documentEvents.visibilityState='hidden';const beforeHidden=reads;act(()=>intervals.forEach(callback=>callback()));assert.equal(reads,beforeHidden,'hidden tabs do not poll');
 documentEvents.visibilityState='visible';await act(async()=>{documentEvents.dispatchEvent(new Event('visibilitychange'));});assert.equal(reads,beforeHidden+5);
 fail=true;await act(async()=>{intervals.forEach(callback=>callback());});assert.match(text(renderer.root),/última información recibida/);assert.match(text(renderer.root),/Con Otra persona/);assert.equal(byLabel('Producción o uso previsto')!.props.value,'Borrador que debe sobrevivir');fail=false;
 act(()=>renderer.unmount());assert.equal(intervals.size,0,'polling stopped on unmount');
 // Assigned returners see Return but cannot edit/cancel another person's booking.
 context.user_id='11';reservations=[{...record,status:'checked_out',custodian_user_id:'11',custodian_name:'Sonido'}];
 await act(async()=>{renderer=create(<InventoryWorkspace role="production"/>);});act(()=>button('Calendario y reservas').props.onClick());
 assert(renderer.root.findAllByProps({'aria-label':'Registrar devolución: Rodaje de prueba'}).length,'the returner sees the return action');assert(!renderer.root.findAllByProps({'aria-label':'Editar reserva: Rodaje de prueba'}).length);assert(!renderer.root.findAllByProps({'aria-label':'Cancelar reserva: Rodaje de prueba'}).length);act(()=>renderer.unmount());
 // Bulk selection: one-line actions and the batch endpoint.
 context.role='management';context.can_manage=true;items=equipment;reservations=[record];
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 assert(renderer.root.findAllByProps({'aria-label':'Marcar verificado: Memoria SD'}).length,'the verify check lives with the card');
 act(()=>renderer.root.findAllByProps({'aria-label':'Seleccionar Memoria SD'})[0].props.onChange({target:{checked:true}}));
 assert.match(text(renderer.root),/1 de 50 seleccionado/,'the bulk bar counts the selection against the API batch cap');
 assert(button('Verificar'));assert(button('Mover ubicación'));assert(button('Reservar'));
 const beforeBatch=writes.length;
 await act(async()=>{await button('Verificar').props.onClick();});
 const batchWrite=writes.slice(beforeBatch).find(write=>write.path==='/api/agency/inventory/batch');
 assert(batchWrite,'bulk verify posts the batch endpoint');
 assert.deepEqual((batchWrite.body as {ids:string[]}).ids,['1']);
 assert.equal((batchWrite.body as {change:{verify:boolean}}).change.verify,true);
 assert.doesNotMatch(text(renderer.root),/seleccionado/,'a successful batch clears the selection');
 act(()=>renderer.unmount());
 // The API caps a batch at 50 records: the selection stops there and the counter shows the limit.
 items=Array.from({length:51},(_,index)=>({...equipment[0],id:String(100+index),name:`Equipo ${100+index}`}));
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 act(()=>button('Seleccionar visibles').props.onClick());
 assert.match(text(renderer.root),/50 de 50 seleccionados/,'the selection stops at the API batch cap');
 const beforeCap=writes.length;
 await act(async()=>{await button('Verificar').props.onClick();});
 const capWrite=writes.slice(beforeCap).find(write=>write.path==='/api/agency/inventory/batch');
 assert(capWrite,'the capped selection still posts one batch');
 assert.equal((capWrite.body as {ids:string[]}).ids.length,50,'the request never exceeds the API cap');
 act(()=>renderer.unmount());
 // CategoryForm owns name, availability and icon without the shared Editor.
 context.role='management';context.can_manage=true;items=equipment;
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 act(()=>button('Agregar categoría').props.onClick());
 categories=[...categories,{id:'3',name:'Accesorios nuevos',active:true}];
 change('Nombre de la categoría','Accesorios nuevos');
 await submit();
 assert.equal(writes.at(-1)!.path,'/api/agency/inventory-categories');assert.equal(writes.at(-1)!.method,'POST');assert.deepEqual(writes.at(-1)!.body,{name:'Accesorios nuevos',active:true,icon:null});assert(button('Accesorios nuevos'));
 act(()=>button('Accesorios nuevos').props.onClick());categories=categories.map(c=>c.id==='3'?{...c,name:'Accesorios archivados',active:false}:c);
 change('Nombre de la categoría','Accesorios archivados');
 act(()=>renderer.root.findAllByType('label').find(node=>text(node).includes('Disponible para nuevos equipos'))!.findByType('input').props.onChange({target:{checked:false}}));
 await submit();
 assert.equal(writes.at(-1)!.path,'/api/agency/inventory-categories/3');assert.equal(writes.at(-1)!.method,'PATCH');assert.equal(writes.at(-1)!.body.active,false);assert(button('Accesorios archivados · archivada'));
 assert.match(text(renderer.root),/Ubicaciones de guardado/);assert.match(text(renderer.root),/Estante A/);assert(renderer.root.findAllByType('small').some(node=>text(node)==='1 equipo'));assert(button('Renombrar'));assert(button('Archivar'));
 const deleteButtons=renderer.root.findAllByType('button').filter(node=>text(node)==='Eliminar');assert.equal(deleteButtons[0].props.disabled,true,'referenced templates cannot be deleted');assert.equal(deleteButtons[1].props.disabled,false,'unreferenced templates stay deletable');
 act(()=>button('Renombrar').props.onClick());change('Nombre de la ubicación','Estante A principal');const availability=renderer.root.findAllByType('label').find(node=>text(node).includes('Disponible para nuevas asignaciones'))!.findByType('input');act(()=>availability.props.onChange({target:{checked:false}}));await submit();assert.equal(writes.at(-1)!.path,'/api/agency/inventory-locations/storage-a');assert.deepEqual(writes.at(-1)!.body,{name:'Estante A principal',active:false,responsible_user_id:null});act(()=>renderer.unmount());
 let itemSaved=0;
 await act(async()=>{renderer=create(<InventoryItemForm item={null} categories={categories} members={context.members} storageTemplates={storageTemplates} canManageStorage createStorageTemplate={async name=>(await mockApi('/api/agency/inventory-locations',{name},'POST') as {location:StorageTemplate}).location} done={()=>{itemSaved++;}}/>);});
 assert.deepEqual(select('Ubicación').props.choices.map((choice:{value:string})=>choice.value),['','storage-a','storage-b'],'active templates plus custom fallback are selectable');
 assert.deepEqual(select('Categoría').props.choices.map((choice:{value:string})=>choice.value),['1','2'],'archived categories are excluded from new inventory forms');
 change('Ubicación','storage-a','select');assert.doesNotMatch(tree(),/placeholder="Estante, depósito o lugar"/);change('Fila / posición','7');
 change('Crear lugar','Rack C');await act(async()=>{await button('Crear lugar').props.onClick();});assert.equal(select('Ubicación').props.value,'storage-new','new place is selected in context');assert.equal(byLabel('Fila / posición')!.props.value,'7','storage row remains free text when a template changes');
 change('Ubicación','','select');assert(button('Crear lugar'));change('Ubicación personalizada','Depósito temporal');change('Fila / posición','libre');await submit();assert.equal(itemSaved,1);assert.equal(writes.at(-1)!.path,'/api/agency/inventory');assert.deepEqual(writes.at(-1)!.body.storage_location_id,null);assert.equal(writes.at(-1)!.body.storage_shelf,'Depósito temporal');assert.equal(writes.at(-1)!.body.storage_row,'libre');act(()=>renderer.unmount());assert.equal(intervals.size,0);
 // Consume the real shared SaveActions. Only dialog hooks/portal are mocked;
 // pending registration and cancellation wiring must follow each actual form.
 let closed=0;
 await act(async()=>{renderer=create(<MockDialog close={()=>{closed++;}}><InventoryReservationForm context={{...context,projects:[]}} items={equipment} record={null} done={()=>{}}/></MockDialog>);});
 assert.equal(button('Guardar reserva').props.disabled,true);
 assert.equal(pendingStates.at(-1),false,'missing projects is not an in-flight save');
 assert.equal(button('Cancelar').props.disabled,false);assert.equal(button('Cancelar').props.type,'button');
 act(()=>button('Cancelar').props.onClick());assert.equal(closed,1);act(()=>renderer.unmount());
 for(const kind of ['reservation','checkout','return','cancel'] as const){
  const form=kind==='reservation'?<InventoryReservationForm context={context} items={equipment} record={record} done={()=>{done++;}}/>:<InventoryTransitionForm action={kind} record={record} done={()=>{done++;}}/>;
  await act(async()=>{renderer=create(<MockDialog close={()=>{closed++;}}>{form}</MockDialog>);});
  if(kind==='checkout')change('Quién lleva los equipos (custodio)','11','select');
  delayWrites=true;const completedBefore:number=done,closedBefore:number=closed,writesBefore:number=writes.length;
  let saving!:Promise<void>;
  act(()=>{saving=renderer.root.findByType('form').props.onSubmit({preventDefault(){}});});
  assert.equal(pendingStates.at(-1),true);assert.equal(button('Guardando…').props.disabled,true);assert.equal(button('Cancelar').props.disabled,true);
  act(()=>button('Cancelar').props.onClick());assert.equal(closed,closedBefore,'cancel cannot dismiss an in-flight save');
  await submit();assert.equal(writes.length,writesBefore+1,'busy form does not submit again');
  fail=true;await act(async()=>{pendingWrites.splice(0).forEach(resolve=>resolve());await saving;});delayWrites=false;fail=false;
  assert.equal(done,completedBefore);assert.equal(pendingStates.at(-1),false);assert.equal(button('Cancelar').props.disabled,false);
  assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/,'save errors stay inside the dialog');
  await submit();assert.equal(done,completedBefore+1,'failed save can be retried');
  act(()=>button('Cancelar').props.onClick());assert.equal(closed,closedBefore+1);act(()=>renderer.unmount());
 }
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 const archiveCardButton=()=>renderer.root.findAllByType('button').find(node=>String(node.props['aria-label']||'').startsWith('Archivar equipo'))!;
 act(()=>archiveCardButton().props.onClick());
 let archiving!:Promise<void>;delayWrites=true;
 act(()=>{archiving=button('Archivar equipo').props.onClick();});
 assert.equal(renderer.root.findByType(MockDialog).props.busy,true);assert.equal(button('Archivando…').props.disabled,true);
 assert.equal(button('Cancelar').props.disabled,true);act(()=>renderer.root.findByType(MockDialog).props.close());
 assert.equal(renderer.root.findAllByType(MockDialog).length,1,'archive cannot close while pending');
 fail=true;await act(async()=>{pendingWrites.splice(0).forEach(resolve=>resolve());await archiving;});delayWrites=false;fail=false;
 assert.equal(renderer.root.findByType(MockDialog).props.busy,false);
 assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/);
 // Background refresh must not clear the archive failure or remove its draft.
 await act(async()=>{intervals.forEach(callback=>callback());});
 assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/);
 act(()=>button('Cancelar').props.onClick());assert.equal(renderer.root.findAllByType(MockDialog).length,0);
 act(()=>archiveCardButton().props.onClick());assert.equal(renderer.root.findAllByProps({role:'alert'}).length,0,'reopening has no stale archive error');
 await act(async()=>{await button('Archivar equipo').props.onClick();});
 assert.equal(renderer.root.findAllByType(MockDialog).length,0);assert.match(text(renderer.root),/Equipo archivado/);
 assert.equal(writes.at(-1)!.method,'DELETE');act(()=>renderer.unmount());assert.equal(intervals.size,0);
 // El detalle y la trazabilidad abren el drawer con la lectura real del API.
 await act(async()=>{renderer=create(<InventoryDetail item={equipment[0]} members={context.members} canManage={false}/>);});
 await act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});
 assert.match(text(renderer.root),/Identificación física/);assert.match(text(renderer.root),/Sin valor de compra registrado/);assert.match(text(renderer.root),/Sin mantenimientos registrados/);act(()=>renderer.unmount());
 console.log('PASS: inventario v2 — borradores de reserva, retornos completos, polling, permisos, lote con topes, vistas y drawer intactos. API/Editor simulados; el layout se mide con el harness visual.');
}
void run();
