import React from 'react';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {act,create,type ReactTestRenderer,type ReactTestInstance} from 'react-test-renderer';
import type {InventoryItem,InventoryReservation} from '../app/inventory-workspace';
Object.assign(globalThis,{React});require.extensions['.css']=()=>{};
const intervals=new Map<number,()=>void>();let timerId=0;
const documentEvents=Object.assign(new EventTarget(),{visibilityState:'visible'});
Object.defineProperty(globalThis,'document',{configurable:true,value:documentEvents});
Object.defineProperty(globalThis,'window',{configurable:true,value:{setInterval(callback:()=>void,ms:number){assert.equal(ms,30000);intervals.set(++timerId,callback);return timerId;},clearInterval(id:number){intervals.delete(id);}}});
const context={user_id:'10',role:'production',can_manage:false,can_reserve:true,time_zone:'America/Asuncion',members:[{id:'10',name:'Cámara'},{id:'11',name:'Sonido'}],projects:[{id:'20',name:'Proyecto de prueba'}]};
const equipment:InventoryItem[]=[{id:'1',name:'Memoria SD',category:'Memoria',category_id:'1',serial_number:null,value:'0',currency:'PYG',status:'available',storage_shelf:'Estante A',storage_row:'2',custodian_user_id:null,location_type:'storage'},{id:'2',name:'DJI Mic',category:'Audio',category_id:'2',serial_number:null,value:'100',currency:'USD',status:'available',storage_shelf:'Estante B',storage_row:'1',custodian_user_id:null,location_type:'storage'}];
const record:InventoryReservation={id:'30',title:'Rodaje de prueba',project_id:'20',project_name:'Proyecto de prueba',starts_at:'2026-09-10T12:00:00.000Z',ends_at:'2026-09-10T15:00:00.000Z',status:'reserved',created_by_user_id:'10',return_user_id:'11',return_user_name:'Sonido',custodian_user_id:null,custodian_name:null,responsible_members:context.members,items:equipment.map(i=>({id:i.id,name:i.name,storage_shelf:i.storage_shelf,storage_row:i.storage_row})),notes:'',version:0};
const writes:{path:string;body:any;method:string}[]=[];let reads=0,fail=false,delay=false;
const pending:(()=>void)[]=[];
let delayWrites=false;
const pendingWrites:(()=>void)[]=[];
let items=equipment,reservations=[record];
let categories=[{id:'1',name:'Memoria',active:true},{id:'2',name:'Audio',active:true}];
const mockApi=async(path:string,body?:unknown,method='POST')=>{
 if(body!==undefined){writes.push({path,body,method});if(delayWrites)await new Promise<void>(resolve=>pendingWrites.push(resolve));if(fail)throw new Error('Conflicto de reserva');return {reservation:record};}
 reads++;if(delay)await new Promise<void>(resolve=>pending.push(resolve));if(fail)throw new Error('Sin conexión');
 if(path.endsWith('/inventory-context'))return context;
 if(path.endsWith('/inventory-categories'))return {categories};
 if(path.endsWith('/inventory'))return {records:items};
 return {reservations};
};
// Dialog/editor behavior is covered by existing tests. Keep these tests focused
// on the inventory contract, reservation drafts, permissions and polling.
const operationsPath=require.resolve('../app/operations');
const MockEditor=()=>null;
const CloseContext=React.createContext<(()=>void)|undefined>(undefined);
const pendingStates:boolean[]=[];
function MockDialog({children,close,busy=false}:{children:React.ReactNode;close:()=>void;busy?:boolean}){return <CloseContext.Provider value={close}><section role="dialog" aria-busy={busy}>{children}</section></CloseContext.Provider>;}
require.cache[operationsPath]={id:operationsPath,filename:operationsPath,loaded:true,exports:{api:mockApi,money:(n:string,c:string)=>`${c} ${n}`,Dialog:MockDialog,Editor:MockEditor}} as NodeModule;
const dialogPath=require.resolve('../app/dialog');
require.cache[dialogPath]={id:dialogPath,filename:dialogPath,loaded:true,exports:{FormActions:({children}:{children:React.ReactNode})=><div>{children}</div>,useDialogClose:()=>React.useContext(CloseContext),useDialogPending:(value:boolean)=>{pendingStates.push(value);}}} as NodeModule;
const {InventoryWorkspace,InventoryReservationForm,InventoryTransitionForm,InventoryCalendar,inventoryUtcTime,inventoryLocalTime,inventoryMonthRange,inventoryLocation,inventoryCanReturn,inventoryCanManageReservation}=require('../app/inventory-workspace') as typeof import('../app/inventory-workspace');
let renderer:ReactTestRenderer,done=0;
function text(node:ReactTestInstance|string):string{return typeof node==='string'?node:node.children.map(text).join('');}
const button=(label:string)=>renderer.root.findAllByType('button').find(node=>text(node)===label)!;
const field=(label:string,tag:'input'|'select'|'textarea'='input')=>renderer.root.findAllByType('label').find(node=>node.children.some(c=>c===label))!.findByType(tag);
const change=(label:string,value:string,tag:'input'|'select'|'textarea'='input')=>act(()=>field(label,tag).props.onChange({target:{value}}));
const check=(label:string)=>act(()=>renderer.root.findAllByType('label').find(node=>text(node).startsWith(label))!.findByType('input').props.onChange());
const tree=()=>JSON.stringify(renderer.toJSON());
const submit=()=>act(async()=>{await renderer.root.findByType('form').props.onSubmit({preventDefault(){}});});
async function run(){
 assert.equal(inventoryUtcTime('2026-09-10T09:00'),'2026-09-10T12:00:00.000Z');
 assert.equal(inventoryLocalTime('2026-10-01T02:59:00Z'),'2026-09-30T23:59');
 assert.equal(inventoryMonthRange('2026-12').to,'2027-01-01T03:00:00.000Z');
 assert.throws(()=>inventoryUtcTime('2026-02-30T09:00'));
 assert.equal(inventoryLocation(equipment[0]),'Estante A · fila 2');
 assert.match(inventoryLocation({...equipment[0],location_type:'checked_out',current_custodian_name:'Sonido',production_name:'Rodaje'}),/Con Sonido · Rodaje/);
 assert.match(inventoryLocation({...equipment[0],storage_shelf:'',storage_row:''}),/sin registrar/);
 assert.equal(inventoryCanManageReservation({...context,user_id:'11'},record),false);
 assert.equal(inventoryCanReturn({...context,user_id:'11'},record),true);
 assert.equal(inventoryCanReturn({...context,user_id:'12'},{...record,custodian_user_id:'12'}),true);
 for(const role of ['viewer','editor','finance'])assert.equal(inventoryCanReturn({...context,user_id:'11',role,can_reserve:false},record),false);
 await act(async()=>{renderer=create(<InventoryReservationForm context={context} items={equipment} record={null} done={()=>{done++;}}/>);});
 change('Producción o uso previsto','Rodaje de productos');change('Proyecto','20','select');change('Desde · Asunción','2026-09-10T09:00');change('Devolución prevista · Asunción','2026-09-10T12:00');
 await submit();assert.match(tree(),/Elegí al menos un equipo/);assert.equal(writes.length,0);
 check('Memoria SD');check('DJI Mic');check('Sonido');change('Responsable de devolución','11','select');
 await submit();assert.equal(done,1);assert.deepEqual(writes[0].body.inventory_ids,['1','2']);assert.deepEqual(writes[0].body.responsible_user_ids,['10','11']);assert.equal(writes[0].body.return_user_id,'11');assert.equal(writes[0].body.starts_at,'2026-09-10T12:00:00.000Z');
 fail=true;await submit();assert.match(tree(),/Conflicto de reserva/);assert.equal(field('Producción o uso previsto').props.value,'Rodaje de productos');fail=false;
 check('Sonido');assert.equal(field('Responsable de devolución','select').props.value,'','removing assigned returner clears the assignment');
 const beforeInvalid=writes.length;await submit();assert.equal(writes.length,beforeInvalid,'invalid responsibility cannot submit');
 check('Sonido');change('Responsable de devolución','11','select');
 act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryReservationForm context={context} items={[equipment[0],{...equipment[1],status:'maintenance'}]} record={record} done={()=>{done++;}}/>);});
 assert.equal(field('Producción o uso previsto').props.value,record.title);assert.equal(field('Responsable de devolución','select').props.value,'11');
 check('DJI Mic');
 const unavailable=renderer.root.findAllByType('label').find(node=>text(node).startsWith('DJI Mic'))!.findByType('input');
 assert.equal(unavailable.props.disabled,true,'unavailable equipment can be deselected from an old draft but not selected anew');
 await submit();assert.equal(writes.at(-1)!.method,'PATCH');assert.equal(writes.at(-1)!.body.expected_version,record.version);assert.deepEqual(writes.at(-1)!.body.inventory_ids,['1']);
 act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryTransitionForm action="checkout" record={record} done={()=>{done++;}}/>);});
 assert.deepEqual(field('Quién lleva los equipos (custodio)','select').findAllByType('option').map(o=>o.props.value),['','10','11']);
 change('Quién lleva los equipos (custodio)','11','select');await submit();assert.equal(writes.at(-1)!.body.custodian_user_id,'11');assert.equal(writes.at(-1)!.path,'/api/agency/inventory-reservations/30/checkout');act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryTransitionForm action="return" record={{...record,status:'checked_out'}} done={()=>{done++;}}/>);});
 assert.equal(renderer.root.findAllByType('fieldset').length,2);
 assert.match(tree(),/devolución completa/,'partial return is not represented as supported');
 const returnFields=renderer.root.findAllByType('fieldset');
 act(()=>returnFields[0].findAllByType('input')[0].props.onChange({target:{value:'Estante nuevo'}}));
 act(()=>returnFields[1].findByType('select').props.onChange({target:{value:'maintenance'}}));
 await submit();assert.equal(writes.at(-1)!.path,'/api/agency/inventory-reservations/30/return');assert.equal(writes.at(-1)!.body.locations.length,2);assert.equal(writes.at(-1)!.body.expected_version,0);
 assert.equal(writes.at(-1)!.body.locations[0].storage_shelf,'Estante nuevo');assert.equal(writes.at(-1)!.body.locations[1].status,'maintenance');
 fail=true;const beforeDone=done;await submit();assert.equal(done,beforeDone);assert.equal(returnFields[0].findAllByType('input')[0].props.value,'Estante nuevo','failed return retains recorded locations');fail=false;
 act(()=>renderer.unmount());
 // Exclusive end at midnight occupies only the preceding calendar day.
 await act(async()=>{renderer=create(<InventoryCalendar month="2026-09" reservations={[{...record,starts_at:'2026-09-10T23:00:00.000Z',ends_at:'2026-09-11T03:00:00.000Z'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2026-09-10'})),/Rodaje de prueba/);assert.doesNotMatch(text(renderer.root.findByProps({'aria-label':'2026-09-11'})),/Rodaje de prueba/);act(()=>renderer.unmount());
 const yearBoundary={...record,starts_at:'2033-01-01T01:00:00.000Z',ends_at:'2033-01-01T03:00:00.000Z'};
 await act(async()=>{renderer=create(<InventoryCalendar month="2032-12" reservations={[yearBoundary,{...yearBoundary,id:'31',status:'cancelled',title:'Cancelada invisible'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2032-12-31'})),/Rodaje de prueba/);assert.doesNotMatch(tree(),/Cancelada invisible/);act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryCalendar month="2033-01" reservations={[yearBoundary]}/>);});assert.doesNotMatch(tree(),/Rodaje de prueba/);act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryCalendar month="2032-02" reservations={[{...record,starts_at:'2032-02-29T12:00:00.000Z',ends_at:'2032-03-01T03:00:00.000Z'}]}/>);});
 assert.match(text(renderer.root.findByProps({'aria-label':'2032-02-29'})),/Rodaje de prueba/);assert.equal(renderer.root.findAllByType('time').length,29);act(()=>renderer.unmount());
 const before=reads;await act(async()=>{renderer=create(<InventoryWorkspace role="sales"/>);});assert.equal(renderer.toJSON(),null);assert.equal(reads,before);act(()=>renderer.unmount());
 await act(async()=>{renderer=create(<InventoryWorkspace role="production"/>);});
 assert.equal(intervals.size,1);assert.match(tree(),/actualiza cada 30 s/);assert.match(tree(),/Estante A/);assert.doesNotMatch(tree(),/Cargando inventario/);
 act(()=>button('Reservar equipos').props.onClick());change('Producción o uso previsto','Borrador que debe sobrevivir');check('Memoria SD');
 delay=true;const beforePoll=reads;
 act(()=>intervals.forEach(callback=>callback()));act(()=>intervals.forEach(callback=>callback()));
 assert.equal(reads,beforePoll+4,'a polling cycle waits for all four requests; a second tick cannot overlap');
 assert.doesNotMatch(tree(),/Cargando inventario/,'background updates retain visible content');
 items=[{...equipment[0],location_type:'checked_out',current_custodian_name:'Otra persona',production_name:'Otra producción'},equipment[1]];
 await act(async()=>{pending.splice(0).forEach(resolve=>resolve());});delay=false;
 assert.match(tree(),/Con Otra persona/);assert.equal(field('Producción o uso previsto').props.value,'Borrador que debe sobrevivir');
 const selected=renderer.root.findAllByType('input').filter(node=>node.props.type==='checkbox'&&node.props.checked);assert(selected.length>=2,'selected equipment and own responsibility persist');
 documentEvents.visibilityState='hidden';const beforeHidden=reads;act(()=>intervals.forEach(callback=>callback()));assert.equal(reads,beforeHidden,'hidden tabs do not poll');
 documentEvents.visibilityState='visible';await act(async()=>{documentEvents.dispatchEvent(new Event('visibilitychange'));});assert.equal(reads,beforeHidden+4);
 fail=true;await act(async()=>{intervals.forEach(callback=>callback());});assert.match(tree(),/última información recibida/);assert.match(tree(),/Con Otra persona/);assert.equal(field('Producción o uso previsto').props.value,'Borrador que debe sobrevivir');fail=false;
 act(()=>renderer.unmount());assert.equal(intervals.size,0,'polling stopped on unmount');
 // Assigned returners see Return but cannot edit/cancel another person's booking.
 context.user_id='11';reservations=[{...record,status:'checked_out',custodian_user_id:'11',custodian_name:'Sonido'}];
 await act(async()=>{renderer=create(<InventoryWorkspace role="production"/>);});act(()=>button('Calendario y reservas').props.onClick());
 assert(button('Registrar devolución'));assert(!button('Editar reserva'));assert(!button('Cancelar reserva'));act(()=>renderer.unmount());
 // Exercise category editor wiring and subsequent reload without shared Editor
 // implementation or HTTP. API/database persistence is tested in the API suite.
 context.role='management';context.can_manage=true;items=equipment;
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 act(()=>button('Agregar categoría').props.onClick());
 categories=[...categories,{id:'3',name:'Accesorios nuevos',active:true}];
 await act(async()=>{await renderer.root.findByType(MockEditor).props.save({name:'Accesorios nuevos',active:'true'});});
 assert.equal(writes.at(-1)!.path,'/api/agency/inventory-categories');assert.equal(writes.at(-1)!.method,'POST');assert.equal(writes.at(-1)!.body.active,true);assert(button('Accesorios nuevos'));
 act(()=>button('Accesorios nuevos').props.onClick());categories=categories.map(c=>c.id==='3'?{...c,name:'Accesorios archivados',active:false}:c);
 await act(async()=>{await renderer.root.findByType(MockEditor).props.save({name:'Accesorios archivados',active:'false'});});
 assert.equal(writes.at(-1)!.path,'/api/agency/inventory-categories/3');assert.equal(writes.at(-1)!.method,'PATCH');assert.equal(writes.at(-1)!.body.active,false);assert(button('Accesorios archivados · archivada'));
 act(()=>button('Agregar equipo').props.onClick());
 const categoryField=renderer.root.findByType(MockEditor).props.fields.find((f:{key:string})=>f.key==='category_id');
 assert.deepEqual(categoryField.choices.map((c:{value:string})=>c.value),['1','2'],'archived categories excluded from new inventory forms');act(()=>renderer.unmount());assert.equal(intervals.size,0);
 // Consume the real shared SaveActions. Only dialog hooks/portal are mocked;
 // pending registration and cancellation wiring must follow each actual form.
 let closed=0;
 await act(async()=>{renderer=create(<MockDialog close={()=>{closed++;}}><InventoryReservationForm context={{...context,projects:[]}} items={equipment} record={null} done={()=>{}}/></MockDialog>);});
 assert.equal(button('Guardar reserva').props.disabled,true);
 assert.equal(pendingStates.at(-1),false,'missing projects is not an in-flight save');
 assert.equal(button('Cancelar').props.disabled,false);assert.equal(button('Cancelar').props.type,'button');
 act(()=>button('Cancelar').props.onClick());assert.equal(closed,1);act(()=>renderer.unmount());
 for(const kind of ['reservation','checkout','return','cancel'] as const){
  const form=kind==='reservation'?<InventoryReservationForm context={context} items={equipment} record={record} done={()=>{done++;}}/>:<InventoryTransitionForm action={kind} record={record} done={()=>{done++;}}/>;
  await act(async()=>{renderer=create(<MockDialog close={()=>{closed++;}}>{form}</MockDialog>);});
  if(kind==='checkout')change('Quién lleva los equipos (custodio)','11','select');
  delayWrites=true;const completedBefore:number=done,closedBefore:number=closed,writesBefore:number=writes.length;
  let saving!:Promise<void>;
  act(()=>{saving=renderer.root.findByType('form').props.onSubmit({preventDefault(){}});});
  assert.equal(pendingStates.at(-1),true);assert.equal(button('Guardando…').props.disabled,true);assert.equal(button('Cancelar').props.disabled,true);
  act(()=>button('Cancelar').props.onClick());assert.equal(closed,closedBefore,'cancel cannot dismiss an in-flight save');
  await submit();assert.equal(writes.length,writesBefore+1,'busy form does not submit again');
  fail=true;await act(async()=>{pendingWrites.splice(0).forEach(resolve=>resolve());await saving;});delayWrites=false;fail=false;
  assert.equal(done,completedBefore);assert.equal(pendingStates.at(-1),false);assert.equal(button('Cancelar').props.disabled,false);
  assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/,'save errors stay inside the dialog');
  await submit();assert.equal(done,completedBefore+1,'failed save can be retried');
  act(()=>button('Cancelar').props.onClick());assert.equal(closed,closedBefore+1);act(()=>renderer.unmount());
 }
 await act(async()=>{renderer=create(<InventoryWorkspace role="management"/>);});
 act(()=>button('Archivar').props.onClick());
 let archiving!:Promise<void>;delayWrites=true;
 act(()=>{archiving=button('Archivar equipo').props.onClick();});
 assert.equal(renderer.root.findByType(MockDialog).props.busy,true);assert.equal(button('Archivando…').props.disabled,true);
 assert.equal(button('Cancelar').props.disabled,true);act(()=>renderer.root.findByType(MockDialog).props.close());
 assert.equal(renderer.root.findAllByType(MockDialog).length,1,'archive cannot close while pending');
 fail=true;await act(async()=>{pendingWrites.splice(0).forEach(resolve=>resolve());await archiving;});delayWrites=false;fail=false;
 assert.equal(renderer.root.findByType(MockDialog).props.busy,false);
 assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/);
 // Background refresh must not clear the archive failure or remove its draft.
 await act(async()=>{intervals.forEach(callback=>callback());});
 assert.match(text(renderer.root.findByProps({role:'dialog'})),/Conflicto de reserva/);
 act(()=>button('Cancelar').props.onClick());assert.equal(renderer.root.findAllByType(MockDialog).length,0);
 act(()=>button('Archivar').props.onClick());assert.equal(renderer.root.findAllByProps({role:'alert'}).length,0,'reopening has no stale archive error');
 await act(async()=>{await button('Archivar equipo').props.onClick();});
 assert.equal(renderer.root.findAllByType(MockDialog).length,0);assert.match(tree(),/Equipo archivado/);
 assert.equal(writes.at(-1)!.method,'DELETE');act(()=>renderer.unmount());assert.equal(intervals.size,0);
 const css=readFileSync(new URL('../app/inventory-workspace.css',import.meta.url),'utf8');assert.match(css,/repeat\(2,minmax/);assert.match(css,/repeat\(3,minmax/);assert.match(css,/@media\(max-width:620px\)/);
 console.log('PASS: inventory UI category create/rename/archive wiring, multi-equipment/responsible editing, unavailable stock, custodian checkout, complete-return payload and retry, assigned permissions, leap/year/midnight calendar boundaries, recorded location, visible 30-second polling, no overlap/flicker/draft reset and offline staleness. API/Editor mocked; browser layout not visually inspected.');
}
void run();
