import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
const workspace=read('../app/inventory-workspace.tsx');
assert(workspace.includes('className="icon-button"'),'inventory card actions render icon-only buttons');
assert(workspace.includes('title='),'inventory card actions expose native tooltips');
assert(workspace.includes('categoryIconMap'),'category icon registry is defined');
const iconKeys=['camera','video','mic','lamp','lightbulb','monitor','laptop','speaker','hard-drive','battery-charging','package','home'];
assert(iconKeys.filter(key=>workspace.includes(`'${key}'`)).length>=8,'at least 8 of the 12 category icon keys are registered');
assert(workspace.includes("'pipeline'")&&workspace.includes('inventory-pipeline'),'inventory pipeline view is wired');
const identity=read('../app/actor-identity.tsx');
assert(identity.includes('export function ActorAvatar'),'ActorAvatar is exported for the verifier mini-avatar');
console.log('PASS: icon-only card actions with tooltips, category icon registry, pipeline view, exported ActorAvatar');
