import React from 'react';
import assert from 'node:assert/strict';
import {act,create} from 'react-test-renderer';

Object.assign(globalThis,{React});
const {AmountInput}=require('../app/profile-controls') as typeof import('../app/profile-controls');
const changed:string[]=[];
let renderer=create(<AmountInput value="4000000" currency="PYG" onChange={value=>changed.push(value)}/>);
let input=renderer.root.findByType('input');
assert.equal(input.props.value,'4.000.000');
assert.equal(input.props.inputMode,'numeric');
assert.equal(input.props.placeholder,'1.000.000');
act(()=>input.props.onChange({currentTarget:{value:'4.000.000,50',selectionStart:12}}));
assert.equal(changed.at(-1),'4000000');
act(()=>input.props.onChange({currentTarget:{value:'1.234',selectionStart:5}}));
assert.equal(changed.at(-1),'1234');
renderer.update(<AmountInput value="1250" currency="USD" onChange={value=>changed.push(value)}/>);
input=renderer.root.findByType('input');
assert.equal(input.props.value,'1.250');
assert.equal(input.props.inputMode,'decimal');
assert.equal(input.props.placeholder,'1.250,50');
act(()=>input.props.onChange({currentTarget:{value:'1,234.50',selectionStart:8}}));
assert.equal(changed.at(-1),'1234.50');
act(()=>input.props.onChange({currentTarget:{value:'1,234',selectionStart:5}}));
assert.equal(changed.at(-1),'1234');
renderer.update(<AmountInput value="0" currency="PYG" required onChange={value=>changed.push(value)}/>);
input=renderer.root.findByType('input');
assert.equal(input.props.required,true);
renderer.unmount();
console.log('PASS: shared money input keeps locale grouping, cents, integer keyboards, grouped paste and required');
