import React from 'react';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {create} from 'react-test-renderer';
import ts from 'typescript';
Object.assign(globalThis,{React});
require.extensions['.css']=()=>{};
const {AssignedPeople}=require('../app/assigned-people') as typeof import('../app/assigned-people');
const {UrgencyBadge}=require('../app/urgency') as typeof import('../app/urgency');
const source=readFileSync(new URL('../app/scale-workspace.tsx',import.meta.url),'utf8');
const file=ts.createSourceFile('scale-workspace.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const card=file.statements.find((n):n is ts.FunctionDeclaration=>ts.isFunctionDeclaration(n)&&n.name?.text==='DraggableOrder');
assert.ok(card);
const compiled=ts.transpileModule(card.getText(file),{compilerOptions:{jsx:ts.JsxEmit.React,target:ts.ScriptTarget.ES2022}}).outputText;
let dragDisabled=false;
const scope={React,AssignedPeople,UrgencyBadge,useDraggable:({disabled}:{disabled:boolean})=>{dragDisabled=disabled;return {setNodeRef:()=>{},transform:null,isDragging:false};},identityColor:()=> 'violet',ClientIdentity:()=>null,LinkIcon:()=>null,RecordEditor:()=>null,DueDate:()=>null,Eye:()=>null,ProjectCardPresence:({projectId}:{projectId:string})=><div data-project={projectId}>Viendo ahora: Visitante sin asignar</div>};
const Card=new Function(...Object.keys(scope),`${compiled};return DraggableOrder;`)(...Object.values(scope)) as React.ComponentType<any>;
const people=Array.from({length:5},(_,i)=>({id:String(i+1),full_name:`Responsable ${i+1}`,photo_url:`https://example.invalid/${i}.webp`,is_primary:i===0}));
const order={id:'77',title:'Pieza',project_id:'12',client_name:'Cliente',project_name:'Proyecto',description:null,drive_url:null,assignees:people,effective_assignees:people,assignee_source:'direct',assigned_user_ids:people.map(p=>p.id)};
const props={order,role:'viewer',refresh:async()=>{},openOrder:()=>{}};
const view=create(<Card {...props}/>);
assert.equal(view.root.findByType(UrgencyBadge).props.value,undefined);
assert.match(JSON.stringify(view.toJSON()),/No disponible/,'missing urgency is not inferred');
view.update(<Card {...props} order={{...order,urgency:5}}/>);
assert.equal(view.root.findByType(UrgencyBadge).props.value,5);
assert.match(JSON.stringify(view.toJSON()),/Crítica/);
assert.equal(view.root.findByType(AssignedPeople).props.people,people,'uses the order payload directly without lookup or inferred aliases');
assert.equal(view.root.findByType(AssignedPeople).props.source,'direct');
assert.equal(view.root.findAllByType('li').length,5);assert.equal(view.root.findAllByType('img').length,5);
assert.equal(dragDisabled,true,'read-only role remains unable to drag');
assert.equal(view.root.findAllByProps({'data-project':'12'}).length,1,'project viewers remain a separate block');
assert.equal(view.root.findByType(AssignedPeople).findAllByProps({'data-project':'12'}).length,0,'live viewers never appear inside the assigned people block');
view.update(<Card {...props} order={{...order,assignees:[],effective_assignees:people,assignee_source:'project'}}/>);
assert.equal(view.root.findAllByType('li').length,5,'all inherited project people remain visible even with no direct assignments');
assert.equal(view.root.findByType(AssignedPeople).props.source,'project');
assert.match(JSON.stringify(view.toJSON()),/Responsables del proyecto/);
assert.equal(view.root.findByProps({className:'assigned-person-primary'}).children.join(''),'Principal del proyecto','inherited principal is not presented as a direct principal');
view.update(<Card {...props} order={{...order,effective_assignees:undefined,assignee_email:'legacy-alias@example.invalid'}}/>);
assert.match(JSON.stringify(view.toJSON()),/Responsables no disponibles/);assert.doesNotMatch(JSON.stringify(view.toJSON()),/legacy-alias@example.invalid/);
view.update(<Card {...props} order={{...order,assignees:[],effective_assignees:[],assignee_source:null}}/>);
assert.match(JSON.stringify(view.toJSON()),/Sin responsables/);assert.match(JSON.stringify(view.toJSON()),/Viendo ahora/);
view.unmount();
console.log('PASS: real production card renders five assigned people from payload, distinct project viewers, honest missing data and unchanged drag permissions');
