import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sectionPath,parentSection,childSections} from '../app/navigation';
import {visibleModule} from '../app/workspace-access';
const css=readFileSync('app/production-focus.css','utf8');
const kanban=css.slice(css.indexOf('.control-shell .production-focus .kanban{')).split('}')[0];
assert(kanban.includes('height:auto'));
const column=css.slice(css.indexOf('.control-shell .production-focus .column{')).split('}')[0];
assert(column.includes('max-height:none;overflow:visible'));
assert(css.includes('overflow-x:auto;overflow-y:hidden'));
const columnTitle=css.slice(css.indexOf('.control-shell .production-focus .column-title{')).split('}')[0];
assert(columnTitle.includes('border-radius'));
const ui=readFileSync('app/scale-workspace.tsx','utf8');
assert(!ui.includes('Enlace directo a Producción'));
assert(!ui.includes('<summary>Detalles y acciones</summary>'));
assert(ui.includes('Ver más'));
assert.equal(sectionPath('Actividad'),'/equipo/actividad');
assert.equal(sectionPath('Historial de trabajo'),'/equipo/historial');
assert.equal(parentSection('Actividad'),'Equipo');
assert(childSections('Equipo').includes('Historial de trabajo'));
assert(!visibleModule('Actividad','editor'));
assert(!visibleModule('Historial de trabajo','editor'));
console.log('PASS: page-scrolling production, rounded headers, visible editing and permission-preserving team tabs');
