import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {sectionPath,parentSection,childSections} from '../app/navigation';
import {visibleModule} from '../app/workspace-access';
const css=readFileSync('app/production-focus.css','utf8');
assert(css.includes('height:auto;max-height:none;overflow:visible'));
assert(css.includes('overflow-x:auto;overflow-y:hidden'));
assert(css.includes('border-radius:999px'));
const ui=readFileSync('app/scale-workspace.tsx','utf8');
assert(!ui.includes('Enlace directo a Producción'));
assert(!ui.includes('<summary>Detalles y acciones</summary>'));
assert(ui.includes('Ver detalle completo'));
assert.equal(sectionPath('Actividad'),'/equipo/actividad');
assert.equal(sectionPath('Historial de trabajo'),'/equipo/historial');
assert.equal(parentSection('Actividad'),'Equipo');
assert(childSections('Equipo').includes('Historial de trabajo'));
assert(!visibleModule('Actividad','editor'));
assert(!visibleModule('Historial de trabajo','editor'));
console.log('PASS: page-scrolling production, rounded headers, visible editing and permission-preserving team tabs');
