import React from 'react';
import assert from 'node:assert/strict';
import {act,create} from 'react-test-renderer';
Object.assign(globalThis,{React});
const listeners=new Set<()=>void>();
const location={hash:''};
Object.assign(globalThis,{window:{location,addEventListener:(name:string,listener:()=>void)=>{assert.equal(name,'hashchange');listeners.add(listener);},removeEventListener:(name:string,listener:()=>void)=>{assert.equal(name,'hashchange');listeners.delete(listener);}}});
require.extensions['.css']=()=>{};
const {ProjectCard}=require('../app/project-card') as typeof import('../app/project-card');
const {AssignedPeople}=require('../app/assigned-people') as typeof import('../app/assigned-people');
const project={id:'42',name:'Proyecto de campaña',client_name:'Cliente',status:'active',work_order_count:4,drive_url:null,assignees:[{id:'1',full_name:'Ana',photo_url:'https://example.invalid/ana.webp',is_primary:true},{id:'2',full_name:'Luis',is_primary:false}]};
const view=create(<ProjectCard project={project}><button>Editar detalles</button></ProjectCard>);
const rendered=JSON.stringify(view.toJSON());
assert.match(rendered,/Ana/);assert.match(rendered,/Luis/);assert.match(rendered,/Principal/);assert.match(rendered,/Activo/);
assert.equal(view.root.findAllByType('img').length,1,'principal photo and secondary fallback');
assert.equal(view.root.findByType('article').children.length,4,'list groups title, status, assignees and actions into four cells');
const five=Array.from({length:5},(_,index)=>({id:String(index+1),full_name:`Responsable ${index+1} Nombre completo`,photo_url:`https://example.invalid/${index}.webp`,is_primary:index===0}));
view.update(<ProjectCard project={{...project,assignees:five}}><button>Editar detalles</button></ProjectCard>);
assert.equal(view.root.findByType(AssignedPeople).props.people,five,'project uses the same assigned people component and server payload');
assert.equal(view.root.findAllByType('li').length,5);assert.equal(view.root.findAllByType('img').length,5);
for(const person of five)assert.ok(JSON.stringify(view.toJSON()).includes(person.full_name),'every full name is visible');
view.update(<ProjectCard project={{...project,assignees:[]}}><button>Editar detalles</button></ProjectCard>);
assert.match(JSON.stringify(view.toJSON()),/Sin responsables/);
view.update(<ProjectCard project={{...project,assignees:undefined}}><button>Editar detalles</button></ProjectCard>);
assert.match(JSON.stringify(view.toJSON()),/Responsables no disponibles/,'missing data is not reported as no assignments');
act(()=>view.unmount());
assert.equal(listeners.size,0,'listener removed on unmount');
let scrolls=0,focuses=0;
const createNodeMock=(element:React.ReactElement)=>element.type==='article'?{scrollIntoView:(options:ScrollIntoViewOptions)=>{assert.equal(options.block,'center');assert.equal(options.behavior,'instant');scrolls++;},focus:(options:FocusOptions)=>{assert.equal(options.preventScroll,true);focuses++;}}:null;
// Fragment exists before the async result mounts its target card.
location.hash='#project-42';
let target:ReturnType<typeof create>;
act(()=>{target=create(<ProjectCard project={project}>Details</ProjectCard>,{createNodeMock});});
assert.equal(target!.root.findByType('article').props.id,'project-42');
assert.equal(target!.root.findByType('article').props.tabIndex,-1);
assert.equal(scrolls,1);assert.equal(focuses,1);
act(()=>target!.update(<ProjectCard project={{...project,name:'Refreshed'}}>Details</ProjectCard>));
assert.equal(scrolls,1,'ordinary refresh does not steal focus or scroll');
location.hash='#project-420';act(()=>listeners.forEach(listener=>listener()));
assert.equal(scrolls,1,'unrelated/prefix IDs are not a match');
location.hash='#project-42';act(()=>listeners.forEach(listener=>listener()));
assert.equal(scrolls,2,'hash navigation works after mount too');
act(()=>target!.unmount());assert.equal(listeners.size,0);
console.log('PASS: project row grouping, status, assignment names/photos/principal and missing data');
