import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const cache=file('../app/data-cache.ts');
const workspace=file('../app/scale-workspace.tsx');
const mobile=file('../app/mobile-navigation.css');
const platform=file('../app/superadmin/page.tsx');
const platformCss=file('../app/superadmin/platform-admin.css');
assert(cache.includes('expires:Date.now()+15000'),'shared read cache must remain bounded to 15 seconds');
for(const endpoint of ['/members','/team','/settings','/activity','/notifications','/inventory-context','/inventory-reservations'])assert(cache.includes(endpoint),'permission-bearing and live endpoints must bypass cache: '+endpoint);
assert(workspace.includes('setDataScope(operationalAccess&&user?`${user.id}:${user.organization_id}:${user.role}`:\'\')'),'cache scope must include user, organization and role');
assert(workspace.includes("if(label==='Inventario'&&!['owner','admin','management','production','finance','editor','viewer','collaborator'].includes(user.role))return;"),'inventory preload must respect the same role boundary as the feature');
assert(mobile.includes('height:100dvh')&&mobile.includes('min-height:44px'),'mobile drawer must cover the viewport and preserve touch targets');
assert(platform.includes("'/api/platform/overview'")&&platform.includes("credentials:'include'")&&platform.includes("cache:'no-store'"),'global panel must use its dedicated, authenticated no-store API');
assert(!platform.includes('ScaleWorkspace')&&!platform.includes('DesktopSidebar'),'global panel must not mount the agency workspace');
assert(platformCss.includes('@media(max-width:760px)'),'global panel must keep an explicit mobile layout contract');
// Ronda 20-09 (SOS-PLT): riel, encabezado y listas densas dentro de su contenedor.
const rail=file('../app/desktop-sidebar.css');
assert(rail.includes('.control-shell .desktop-sidebar nav>a,.control-shell .desktop-sidebar nav>button{'),'rail logout button shares the link geometry');
const density=file('../app/workspace-density.css');
assert(density.includes('.topbar-company>.workspace .company-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'),'long company names truncate in the topbar');
const operationsCss=file('../app/operations.css');
assert(operationsCss.includes('.ops-grid-list{grid-template-columns:minmax(0,1fr);overflow-x:auto'),'the team list scrolls instead of overflowing its panel');
assert(operationsCss.includes('.company-choice-row{display:flex'),'the company switcher row wraps instead of overflowing the dialog');
const portalCss=file('../app/cliente/portal.css');
assert(portalCss.includes('.delivery-activity{list-style:none'),'the portal activity feed drops the native bullets');
const companyCss=file('../app/company-settings.css');
assert(companyCss.includes('.company-settings-row.is-current{'),'the open company is marked in Configuración');
console.log('PASS: rail, topbar, company switcher and dense lists keep their content inside the container.');
