import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const cache=file('../app/data-cache.ts');
const workspace=file('../app/scale-workspace.tsx');
const mobile=file('../app/mobile-navigation.css');
const platform=file('../app/superadmin/page.tsx');
const platformCss=file('../app/superadmin/platform-admin.css');
assert(cache.includes('expires:Date.now()+15000'),'shared read cache must remain bounded to 15 seconds');
for(const endpoint of ['/members','/team','/settings','/activity','/notifications','/inventory-context','/inventory-reservations'])assert(cache.includes(endpoint),'permission-bearing and live endpoints must bypass cache: '+endpoint);
assert(workspace.includes('setDataScope(operationalAccess&&user?`${user.id}:${user.organization_id}:${user.role}`:\'\')'),'cache scope must include user, organization and role');
assert(workspace.includes("if(label==='Inventario'&&!['owner','admin','management','production','finance','editor','viewer','collaborator'].includes(user.role))return;"),'inventory preload must respect the same role boundary as the feature');
assert(mobile.includes('height:100dvh')&&mobile.includes('min-height:44px'),'mobile drawer must cover the viewport and preserve touch targets');
assert(platform.includes("'/api/platform/overview'")&&platform.includes("credentials:'include'")&&platform.includes("cache:'no-store'"),'global panel must use its dedicated, authenticated no-store API');
assert(!platform.includes('ScaleWorkspace')&&!platform.includes('DesktopSidebar'),'global panel must not mount the agency workspace');
assert(platformCss.includes('@media(max-width:760px)'),'global panel must keep an explicit mobile layout contract');
// Ronda 20-09 (SOS-PLT): riel, encabezado y listas densas dentro de su contenedor.
const rail=file('../app/desktop-sidebar.css');
assert(rail.includes('.control-shell .desktop-sidebar nav>a,.control-shell .desktop-sidebar nav>button{'),'rail logout button shares the link geometry');
assert(rail.includes('.sidebar-collapse{position:static'),'the collapsed rail keeps the toggle out of the brand');
const density=file('../app/workspace-density.css');
assert(density.includes('.topbar-company>.workspace .company-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'),'long company names truncate in the topbar');
assert(density.includes('.topbar-utility-actions>.theme-toggle{width:40px;min-width:40px;min-height:40px'),'the theme toggle matches its toolbar neighbours');
assert(file('../app/control-center.css').includes('@media(max-width:760px){.control-shell>.content{padding:16px 16px 28px}'),'mobile content padding matches the pulled topbar');
const operationsCss=file('../app/operations.css');
assert(operationsCss.includes('.ops-grid-list{grid-template-columns:minmax(0,1fr);overflow-x:auto'),'the team list scrolls instead of overflowing its panel');
assert(operationsCss.includes('.company-choice-row{display:flex'),'the company switcher row wraps instead of overflowing the dialog');
assert(operationsCss.includes('.person-hub-card.is-list :is(.ops-person img,.avatar){width:32px'),'team list rows keep a thin identity');
assert(operationsCss.includes('.person-hub-card:not(.is-list)>.person-hub-tail{display:flex'),'team cards anchor their actions to the foot');
assert(operationsCss.includes('.person-hub-actions .ops-card-actions{margin:0;padding:0;border:0'),'no empty or double-bordered action block in the team cards');
assert(operationsCss.includes('.person-hub-card.is-list>.person-hub-tail>.form-note'),'the ambiguous-profile note spans the row');
const portalCss=file('../app/cliente/portal.css');
assert(portalCss.includes('.delivery-activity{list-style:none'),'the portal activity feed drops the native bullets');
const companyCss=file('../app/company-settings.css');
assert(companyCss.includes('.company-settings-row.is-current{'),'the open company is marked in Configuración');
const ui=file('../app/ui-system.css');
assert(ui.includes('.ops-select-options{position:absolute')&&ui.includes('.ops-select-options.ops-select-floating{position:fixed'),'SelectCustom keeps its geometry in the shared sheet (superadmin and portal do not load operations.css)');
assert(ui.includes('overflow-x:hidden;overflow-y:auto'),'the select menu scrolls its options instead of clipping them');
assert(file('../app/globals.css').includes('.sr-only{position:absolute'),'the app has one global visually-hidden utility (deletion countdown, search labels, Google button)');
assert(file('../app/workspace-density.css').includes(':is(.control-shell,.unified-dialog,.photo-dialog) .phone-input{display:grid'),'the phone field lays out inside portaled dialogs too');
assert(file('../app/settings-slice.css').includes('.trash-info{grid-column:1/-1;grid-row:2}'),'trash rows keep the name out of the checkbox column on mobile');
assert(file('../app/subscription-panel.css').includes('.subscription-notice.subscription-status--trialing .subscription-secondary{'),'the trial notice keeps its own tone instead of the danger palette');
assert(file('../app/registro/registration.css').includes('.registration-card{display:flex;flex-direction:column;width:min(468px,100%)'),'the verification card keeps the access width and scroll caps');
assert(file('../app/platform-access.css').includes('.platform-access-list{display:grid;gap:2px;margin:0;padding:0;list-style:none}'),'platform lists drop the native indentation');
assert(file('../app/invite-links.css').includes('.invite-link-actions{display:flex'),'invite row actions lay out with the shared gap');
assert(file('../app/superadmin/platform-admin.css').includes('margin-bottom: 0;'),'the global admin header resets the leaking global header margin');
assert(file('../app/superadmin/page.tsx').includes('title={JSON.stringify(entry.metadata)}'),'audit metadata keeps the full value reachable');
console.log('PASS: rail, topbar, company switcher and dense lists keep their content inside the container.');
