import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const file=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const cache=file('../app/data-cache.ts');
const workspace=file('../app/scale-workspace.tsx');
const mobile=file('../app/mobile-navigation.css');
const platform=file('../app/superadmin/page.tsx');
const platformCss=file('../app/superadmin/platform-admin.css');
assert(cache.includes('expires:Date.now()+15000'),'shared read cache must remain bounded to 15 seconds');
for(const endpoint of ['/members','/team','/settings','/activity','/notifications','/inventory-context','/inventory-reservations'])assert(cache.includes(endpoint),'permission-bearing and live endpoints must bypass cache: '+endpoint);
assert(workspace.includes('setDataScope(operationalAccess&&user?`${user.id}:${user.organization_id}:${user.role}`:\'\')'),'cache scope must include user, organization and role');
assert(workspace.includes("if(['Inventario','Estudio'].includes(label)&&!roleCan(user.role,'inventory.view'))return;"),'inventory and studio preload respect the same capability as the feature');
assert(mobile.includes('height:100dvh')&&mobile.includes('min-height:44px'),'mobile drawer must cover the viewport and preserve touch targets');
assert(platform.includes("'/api/platform/overview'")&&platform.includes("credentials:'include'")&&platform.includes("cache:'no-store'"),'global panel must use its dedicated, authenticated no-store API');
assert(!platform.includes('ScaleWorkspace')&&!platform.includes('DesktopSidebar'),'global panel must not mount the agency workspace');
assert(platformCss.includes('@media(max-width:760px)'),'global panel must keep an explicit mobile layout contract');
// Ronda 20-09 (SOS-PLT): riel, encabezado y listas densas dentro de su contenedor.
const rail=file('../app/desktop-sidebar.css');
assert(rail.includes('.control-shell .desktop-sidebar nav>a,.control-shell .desktop-sidebar nav>button{'),'rail logout button shares the link geometry');
assert(rail.includes('.sidebar-collapse{position:static'),'the collapsed rail keeps the toggle out of the brand');
const density=file('../app/workspace-density.css');
assert(density.includes('.topbar-company>.workspace .company-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'),'long company names truncate in the topbar');
assert(density.includes('.topbar-utility-actions>.theme-toggle{width:40px;min-width:40px;min-height:40px'),'the theme toggle matches its toolbar neighbours');
assert(file('../app/control-center.css').includes('@media(max-width:760px){.control-shell>.content{padding:16px 16px 28px}'),'mobile content padding matches the pulled topbar');
const operationsCss=file('../app/operations.css');
assert(operationsCss.includes('.control-shell .ops-grid.ops-grid-list{grid-template-columns:minmax(0,1fr);overflow-x:auto'),'the team list wins over the card grid and scrolls instead of overflowing its panel');
assert(operationsCss.includes('.company-choice-row{display:flex'),'the company switcher row wraps instead of overflowing the dialog');
assert(operationsCss.includes('.person-hub-card.is-list :is(.ops-person img,.avatar){width:32px'),'team list rows keep a thin identity');
assert(operationsCss.includes('.person-hub-card:not(.is-list)>.person-hub-tail{display:flex'),'team cards anchor their actions to the foot');
assert(operationsCss.includes('.person-hub-actions .ops-card-actions{margin:0;padding:0;border:0'),'no empty or double-bordered action block in the team cards');
assert(operationsCss.includes('.person-hub-card.is-list>.person-hub-tail>.form-note'),'the ambiguous-profile note spans the row');
assert(operationsCss.includes('.person-hub-head-row span:first-child{padding-left:26px}'),'the team header aligns with the row identity');
assert(operationsCss.includes('.person-hub-card.is-list{grid-template-columns:minmax(0,1fr);gap:12px;padding:16px'),'the stacked team list returns to card density without growing past its column');
assert(file('../app/operations.tsx').includes('visiblePayouts.length?<div className="finance-row-head"'),'the payout header only renders with visible rows');
const portalCss=file('../app/cliente/portal.css');
assert(portalCss.includes('.delivery-activity{list-style:none'),'the portal activity feed drops the native bullets');
assert(portalCss.includes('.portal-date,.delivery-activity small{white-space:nowrap'),'portal dates never break mid-value');
assert(portalCss.includes('.client-portal :is(h1,h2){min-width:0;overflow-wrap:anywhere}'),'long portal titles wrap instead of being clipped');
for(const route of ['../app/cliente/entregas/page.tsx','../app/cliente/entregas/[id]/page.tsx']){
  assert(!file(route).includes('${listDateFull'),`${route} never interpolates a nullable date`);
}
const companyCss=file('../app/company-settings.css');
assert(companyCss.includes('.company-settings-row.is-current{'),'the open company is marked in Configuración');
const ui=file('../app/ui-system.css');
assert(ui.includes('.ops-select-options{position:absolute')&&ui.includes('.ops-select-options.ops-select-floating{position:fixed'),'SelectCustom keeps its geometry in the shared sheet (superadmin and portal do not load operations.css)');
assert(ui.includes('overflow-x:hidden;overflow-y:auto'),'the select menu scrolls its options instead of clipping them');
assert(file('../app/globals.css').includes('.sr-only{position:absolute'),'the app has one global visually-hidden utility (deletion countdown, search labels, Google button)');
const dialogCss=file('../app/dialog.css');
assert(dialogCss.includes('.ops-overlay{position:fixed;inset:0;z-index:60;display:grid;place-items:center;padding:20px'),'dialog.css owns the dialog overlay geometry');
assert(!file('../app/operations.css').includes('.ops-overlay {\n  display: grid'),'no module redefines the overlay centering (the mobile sheet keeps its bottom anchor)');
assert(dialogCss.includes('@media(max-width:540px){.ops-overlay{align-items:end;padding:0}'),'the mobile dialog stays anchored to the bottom');
assert(file('../app/workspace-density.css').includes(':is(.control-shell,.unified-dialog,.photo-dialog) .phone-input{display:grid'),'the phone field lays out inside portaled dialogs too');
assert(file('../app/archive-controls.tsx').includes("const TRASH_TEMPLATE='grid-cols-[2rem_7rem_minmax(16rem,2.4fr)_7rem]'"),'trash rows share the v2 template with their header');
assert(file('../app/subscription-panel.css').includes('.subscription-notice.subscription-status--trialing .subscription-secondary{'),'the trial notice keeps its own tone instead of the danger palette');
assert(file('../app/registro/registration.css').includes('.registration-card{display:flex;flex-direction:column;width:min(468px,100%)'),'the verification card keeps the access width and scroll caps');
assert(file('../app/invite-links.tsx').includes('REQUESTS_TEMPLATE=')&&file('../app/invite-links.tsx').includes('LINKS_TEMPLATE='),'invite rows keep a shared v2 template for header and rows');
assert(file('../app/superadmin/platform-admin.css').includes('margin-bottom: 0;'),'the global admin header resets the leaking global header margin');
assert(file('../app/superadmin/page.tsx').includes('title={JSON.stringify(entry.metadata)}'),'audit metadata keeps the full value reachable');
assert(file('../app/superadmin/platform-admin.css').includes('.platform-admin-subscription-form label:has(textarea)'),'subscription notes span the full row');
assert(file('../app/actor-identity.css').includes('.actor-identity-time{white-space:nowrap'),'author timestamps never break mid-value');
assert(file('../app/status/status.css').includes('.status-hero{display:flex;align-items:flex-start;gap:14px;min-width:0;flex-wrap:wrap;margin-bottom:0}'),'the public status hero resets the global header margin');
// Ronda 21-09 (SOS-DSN): las primitivas exponen el texto completo y permiten elipsis sin perderlo (#31).
assert(file('../app/profile-controls.tsx').includes('title={selectedLabel}'),'SelectCustom exposes the selected label as title');
assert(file('../app/actor-identity.tsx').includes('title={label}'),'ActorIdentity exposes the full name as title');
assert(file('../app/actor-identity.css').includes('.actor-identity-name{display:block;min-width:0;max-width:100%'),'ActorIdentity name is a block so caller ellipsis applies');
console.log('PASS: rail, topbar, company switcher and dense lists keep their content inside the container.');
