import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(name:string)=>readFileSync('app/'+name,'utf8');
const workspace=read('scale-workspace.tsx'),toolbar=read('demo-toolbar.tsx'),sidebar=read('desktop-sidebar.css');
assert.equal((workspace.match(/<DemoToolbar/g)||[]).length,1);
assert(workspace.indexOf('<div className="workspace-context">')<workspace.indexOf('<DemoToolbar'));
assert(!toolbar.includes('demo-session-note'));
assert(toolbar.includes('aria-label="Información de la demo"'));
assert(toolbar.includes('Sin dinero real'));
assert(toolbar.includes('disabled={busy}'));
assert(sidebar.includes('grid-template-columns:minmax(0,1fr) 36px'));
assert(sidebar.includes('overflow:hidden;text-overflow:ellipsis;white-space:nowrap'));
assert(workspace.includes('aria-label="Abrir mi perfil" onClick={()=>setMyProfile(true)}'));
assert(workspace.includes('onClick={logout} aria-label="Cerrar sesión"'));
const fields=read('operations.tsx'),css=read('operations.css');
assert(fields.includes('columns = true'));
// Additional wide fields are intentional; do not couple this contract to array order.
const wideFields=fields.match(/\[([^\]]+)\]\.includes\(f\.key\)/)?.[1];
assert(wideFields,'Editor must identify fields that span the form');
const wideKeys=new Set(Array.from(wideFields.matchAll(/['"]([^'"]+)['"]/g),match=>match[1]));
for(const key of ['title','description','drive_url','drive_links','address','notes','legal_name'])assert(wideKeys.has(key),`${key} must remain full width`);
assert(css.includes('repeat(auto-fit,minmax(min(100%,220px),1fr))'));
assert(css.includes('.ops-form-grid>.dialog-actions'));
assert(css.includes('@media (max-width:540px)'));
console.log('PASS: one compact demo toolbar, separate profile/logout, bounded sidebar footer and responsive form columns (visual QA separate)');
