"use client";
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {WorkspaceBrand} from '../workspace-brand';
import {WorkspaceFooter} from '../workspace-footer';
import './platform-admin.css';
import {platformApi,subscriptionExpiry} from '../platform-admin-api';

type Overview={agencies:{total:number;active:number};users:{total:number};subscriptions:{status:string;total:number}[];coupons:{total:number;active:number}};
type Agency={id:number;name:string;slug:string;active:boolean;active_users:number;subscription_status:string|null;subscription_currency:string|null;subscription_amount:string|null;trial_ends_at:string|null;due_at:string|null;internal_subscription_state?:'active'|'suspended'|null;internal_subscription_expires_at?:string|null};
type Subscription={internal_state:'active'|'suspended'|null;internal_reason:string|null;internal_expires_at:string|null;provider_status?:string|null;currency?:string|null};
type Person={id:number;email:string;active_agencies:number;platform_admin:boolean};
type Coupon={id:number;code:string;discount_type:'percent'|'fixed';discount_value:string;currency:string|null;active:boolean;max_redemptions:number|null};
type State={overview:Overview;agencies:Agency[];users:Person[];coupons:Coupon[]};
type BootstrapStatus={configured:boolean;valid:boolean;initialized:boolean;state:'initialized'|'not_configured'|'invalid_configuration'|'awaiting_eligible_user'};
const money=(value:string|null,currency:string|null)=>value===null?'—':new Intl.NumberFormat('es-PY',{style:'currency',currency:currency||'USD',maximumFractionDigits:currency==='PYG'?0:2}).format(Number(value));
export default function PlatformAdmin(){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[coupon,setCoupon]=useState({code:'',discount_value:'10',discount_type:'percent' as 'percent'|'fixed',currency:'USD'});
 const [bootstrap,setBootstrap]=useState<BootstrapStatus|null>(null),[subscriptionAgency,setSubscriptionAgency]=useState<Agency|null>(null),[subscription,setSubscription]=useState<Subscription|null>(null),[subscriptionLoaded,setSubscriptionLoaded]=useState(false),[subscriptionState,setSubscriptionState]=useState<'active'|'suspended'|'clear'>('active'),[subscriptionReason,setSubscriptionReason]=useState(''),[subscriptionExpiryValue,setSubscriptionExpiryValue]=useState('');
 async function load(){setBusy(true);setError('');try{const [overview,agencies,users,coupons]=await Promise.all([platformApi<Overview>('/api/platform/overview',{credentials:'include',cache:'no-store'}),platformApi<{agencies:Agency[]}>('/api/platform/agencies?limit=50'),platformApi<{users:Person[]}>('/api/platform/users?limit=50'),platformApi<{coupons:Coupon[]}>('/api/platform/coupons?limit=50')]);setState({overview,agencies:agencies.agencies,users:users.users,coupons:coupons.coupons});}catch(cause){setState(null);setError(cause instanceof Error?cause.message:'No se pudo cargar el panel.');}finally{setBusy(false);}}
 async function loadBootstrap(){try{setBootstrap(await platformApi<BootstrapStatus>('/api/platform/bootstrap-status'));}catch{setBootstrap(null);}}
 useEffect(()=>{void load();void loadBootstrap();},[]);
 async function manageSubscription(agency:Agency){setError('');setSubscriptionAgency(agency);setSubscription(null);setSubscriptionLoaded(false);try{const data=await platformApi<{subscription:Subscription|null}>(`/api/platform/agencies/${agency.id}/subscription`);setSubscription(data.subscription);setSubscriptionLoaded(true);setSubscriptionState(data.subscription?.internal_state||'active');setSubscriptionReason(data.subscription?.internal_reason||'');setSubscriptionExpiryValue(data.subscription?.internal_expires_at?data.subscription.internal_expires_at.slice(0,16):'');}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo cargar el estado manual.');}}
 async function saveSubscription(event:FormEvent){event.preventDefault();if(!subscriptionAgency)return;setBusy(true);setError('');try{const body=subscriptionState==='clear'?{state:null}:{state:subscriptionState,reason:subscriptionReason,expires_at:subscriptionExpiry(subscriptionExpiryValue)};await platformApi(`/api/platform/agencies/${subscriptionAgency.id}/subscription`,{method:'PATCH',body:JSON.stringify(body)});setSubscriptionAgency(null);setSubscription(null);setSubscriptionLoaded(false);await load();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo guardar el estado manual.');setBusy(false);}}
 async function toggleCoupon(item:Coupon){setBusy(true);setError('');try{await platformApi(`/api/platform/coupons/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});await load();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo actualizar el cupón.');setBusy(false);}}
 async function createCoupon(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await platformApi('/api/platform/coupons',{method:'POST',body:JSON.stringify({...coupon,currency:coupon.discount_type==='percent'?null:coupon.currency})});setCoupon({code:'',discount_value:'10',discount_type:'percent',currency:'USD'});await load();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo crear el cupón.');setBusy(false);}}
 return <main className="platform-admin-page"><header className="platform-admin-header"><Link href="/" aria-label="Scale OS"><WorkspaceBrand/></Link><div><p className="eyebrow">ADMINISTRACIÓN GLOBAL</p><h1>Control de Scale OS</h1></div><div className="platform-admin-actions"><button type="button" className="secondary" onClick={()=>void load()} disabled={busy}>Actualizar</button><Link className="text-button" href="/">Volver al panel</Link></div></header>
  <section className="platform-admin-notice"><strong>Acceso separado por plataforma.</strong><span>Ser dueño de una agencia no habilita este panel ni sus datos.</span></section>
  {bootstrap&&!bootstrap.initialized?<section className="platform-admin-bootstrap" role="status"><strong>Primer acceso global pendiente.</strong><span>{bootstrap.state==='not_configured'?'Falta definir la configuración inicial del administrador en el servidor.':bootstrap.state==='invalid_configuration'?'La configuración inicial del administrador no tiene un formato válido.':bootstrap.state==='awaiting_eligible_user'?'La cuenta configurada debe existir, tener correo verificado y acceso activo a una agencia.':'Estado de configuración pendiente.'}</span><small>Este diagnóstico no expone correos ni secretos.</small></section>:null}
  {error?<section className="platform-admin-error" role="alert"><h2>No pudimos abrir la administración global</h2><p>{error}</p><p>El acceso se concede por separado de los permisos de cada agencia. Si es el primer administrador, revisá el diagnóstico de configuración del servidor.</p></section>:null}
  {busy&&!state?<p role="status">Cargando control global…</p>:null}
  {state?<><section className="platform-admin-stats" aria-label="Resumen de plataforma"><article><small>Agencias activas</small><strong>{state.overview.agencies.active} / {state.overview.agencies.total}</strong></article><article><small>Usuarios registrados</small><strong>{state.overview.users.total}</strong></article><article><small>Cupones activos</small><strong>{state.overview.coupons.active} / {state.overview.coupons.total}</strong></article><article><small>Suscripciones</small><strong>{state.overview.subscriptions.map(row=>`${row.total} ${row.status}`).join(' · ')||'Sin datos'}</strong></article></section>
   <section className="platform-admin-section"><div className="platform-admin-section-heading"><div><p className="eyebrow">AGENCIAS</p><h2>Suscripciones y uso</h2></div><small>Hasta 50 registros recientes</small></div><div className="platform-admin-table-wrap"><table><thead><tr><th>Agencia</th><th>Estado</th><th>Plan</th><th>Usuarios</th><th>Prueba / vencimiento</th></tr></thead><tbody>{state.agencies.map(agency=><tr key={agency.id}><td><b>{agency.name}</b><small>{agency.slug}</small></td><td>{agency.active?'Activa':'Inactiva'} · {agency.internal_subscription_state==='active'?'Acceso manual activo':agency.internal_subscription_state==='suspended'?'Acceso manual suspendido':'Sin cambio manual'}</td><td>{money(agency.subscription_amount,agency.subscription_currency)}</td><td>{agency.active_users}</td><td>{agency.internal_subscription_expires_at||agency.trial_ends_at||agency.due_at||'—'}<br/><button type="button" className="text-button" disabled={busy} onClick={()=>void manageSubscription(agency)}>Gestionar estado manual</button></td></tr>)}</tbody></table></div></section>
   <section className="platform-admin-two-columns"><section className="platform-admin-section"><div className="platform-admin-section-heading"><div><p className="eyebrow">USUARIOS</p><h2>Accesos entre agencias</h2></div></div><ul className="platform-admin-list">{state.users.map(person=><li key={person.id}><span><b>{person.email}</b><small>{person.active_agencies} agencias activas</small></span>{person.platform_admin?<em>Admin global</em>:null}</li>)}</ul></section>
    <section className="platform-admin-section"><div className="platform-admin-section-heading"><div><p className="eyebrow">CUPONES</p><h2>Catálogo comercial</h2></div></div><form className="platform-admin-coupon" onSubmit={createCoupon}><input value={coupon.code} onChange={event=>setCoupon({...coupon,code:event.target.value.toUpperCase()})} placeholder="SCALE10" aria-label="Código de cupón" required minLength={3} maxLength={40}/><select value={coupon.discount_type} onChange={event=>setCoupon({...coupon,discount_type:event.target.value as 'percent'|'fixed'})}><option value="percent">Porcentaje</option><option value="fixed">Monto fijo</option></select><input value={coupon.discount_value} inputMode="decimal" onChange={event=>setCoupon({...coupon,discount_value:event.target.value})} aria-label="Valor del cupón" required/>{coupon.discount_type==='fixed'?<select value={coupon.currency} onChange={event=>setCoupon({...coupon,currency:event.target.value})}><option value="USD">USD</option><option value="PYG">PYG</option></select>:null}<button className="primary" disabled={busy}>Crear cupón</button></form><p className="form-note">Crear un cupón no inicia cobros ni activa un proveedor de pagos. Su aplicación comercial se habilita en una entrega posterior.</p><ul className="platform-admin-list">{state.coupons.map(item=><li key={item.id}><span><b>{item.code}</b><small>{item.discount_type==='percent'?`${item.discount_value}%`:money(item.discount_value,item.currency)} · {item.max_redemptions?`${item.max_redemptions} usos máximos`:'Sin límite de usos'}</small></span><span><em data-active={item.active}>{item.active?'Activo':'Pausado'}</em><button type="button" className="text-button" disabled={busy} onClick={()=>void toggleCoupon(item)}>{item.active?'Pausar':'Reactivar'}</button></span></li>)}</ul></section></section></>:null}
  {subscriptionAgency?<section className="platform-admin-section platform-admin-subscription" role="dialog" aria-label={`Estado manual de ${subscriptionAgency.name}`}><div className="platform-admin-section-heading"><div><p className="eyebrow">ACCESO MANUAL</p><h2>{subscriptionAgency.name}</h2></div><button type="button" className="text-button" disabled={busy} onClick={()=>setSubscriptionAgency(null)}>Cerrar</button></div>{!subscriptionLoaded?<p role="status">Cargando estado manual…</p>:subscription===null?<p className="form-note">Esta agencia no tiene una suscripción interna administrable. No se aplicó ningún cambio.</p>:<form className="platform-admin-subscription-form" onSubmit={saveSubscription}><p className="form-note">Este control es un override manual y auditado de acceso. No cobra, no guarda secretos y no confirma pagos.</p><label>Estado<select value={subscriptionState} disabled={busy} onChange={event=>setSubscriptionState(event.target.value as typeof subscriptionState)}><option value="active">Acceso manual activo</option><option value="suspended">Acceso manual suspendido</option><option value="clear">Quitar estado manual</option></select></label>{subscriptionState!=='clear'?<><label>Motivo<textarea value={subscriptionReason} disabled={busy} minLength={3} maxLength={280} required onChange={event=>setSubscriptionReason(event.target.value)} placeholder="Motivo de la intervención manual"/></label><label>Vence (opcional)<input type="datetime-local" value={subscriptionExpiryValue} disabled={busy} onChange={event=>setSubscriptionExpiryValue(event.target.value)}/></label></>:null}<button className="primary" disabled={busy||subscriptionState!=='clear'&&subscriptionReason.trim().length<3}>{busy?'Guardando…':'Guardar estado manual'}</button></form>}</section>:null}
  <WorkspaceFooter/>
 </main>;
}
