"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api,Dialog,Editor,money} from './operations';
import {SaveActions} from './save-actions';
import {ActorIdentity} from './actor-identity';
import {currencyChoices} from './currencies';
import {useCompanyCurrency} from './currency-provider';
import {ViewToggle} from './view-toggle';
import {InventoryBarcode,inventoryCode,printInventoryLabel} from './inventory-label';
import './inventory-workspace.css';

type Person={id:string;name:string;photo_url?:string|null};
type Category={id:string;name:string;active:boolean};
export type StorageTemplate={id:string;name:string;active:boolean;item_count:number};
export type InventoryItem={id:string;name:string;inventory_code?:string;category:string;category_id:string|null;category_name?:string;serial_number:string|null;value:string;currency:string;status:string;storage_shelf:string;storage_row:string;storage_location_id?:string|null;storage_location_name?:string|null;custodian_user_id:string|null;location_type?:string;current_custodian_name?:string;production_name?:string;project_name?:string;return_user_name?:string;expected_return_at?:string;last_verified_at?:string|null;last_verified_by_user_id?:string|null;last_verification_result?:'confirmed'|'difference'|'missing'|null;last_verification_differences?:string;last_verifier_name?:string|null;last_verifier_photo_url?:string|null;[key:string]:unknown};
type ItemReference={id:string;name:string;inventory_code?:string;storage_shelf:string;storage_row:string};
type ReservationActors={actor_name?:string;actor_photo_url?:string;actor_verified?:boolean;checkout_actor_name?:string;checkout_actor_photo_url?:string;checkout_actor_verified?:boolean;return_actor_name?:string;return_actor_photo_url?:string;return_actor_verified?:boolean};
export type InventoryReservation=ReservationActors&{id:string;title:string;project_id:string;project_name:string;starts_at:string;ends_at:string;status:'reserved'|'checked_out'|'returned'|'cancelled';created_by_user_id:string;return_user_id:string;return_user_name:string;custodian_user_id:string|null;custodian_name:string|null;responsible_members:Person[];items:ItemReference[];notes:string;version:number};
type Context={user_id:string;role:string;time_zone:string;can_manage:boolean;can_reserve:boolean;members:Person[];projects:Person[]};
type InventoryVerification={id:string;result:'confirmed'|'difference'|'missing';differences?:string;note?:string;verified_at:string;verifier_name?:string;verifier_photo_url?:string|null};
type InventoryTrace={id:string;event_type:string;event_at:string;actor_name?:string;event_data?:Record<string,unknown>};
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'No se pudo completar la operación';
const statusLabels={reserved:'Reservado',checked_out:'Retirado',returned:'Devuelto',cancelled:'Cancelado'};
const itemStatuses=[{value:'available',label:'Disponible'},{value:'maintenance',label:'Mantenimiento'},{value:'retired',label:'Dado de baja'}];
const zone='America/Asuncion';
const dateTime=(value:string)=>new Intl.DateTimeFormat('es-PY',{timeZone:zone,day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const itemCode=(item:Pick<InventoryItem,'id'|'inventory_code'>)=>item.inventory_code||inventoryCode(item.id);
const verificationLabel=(result:InventoryItem['last_verification_result'])=>({confirmed:'Confirmado',difference:'Con diferencias',missing:'No encontrado'} as Record<string,string>)[result||'']||'Sin control';
export function inventoryLocalTime(value:string|Date){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));
 const part=(type:string)=>parts.find(p=>p.type===type)!.value;
 return `${part('year')}-${part('month')}-${part('day')}T${part('hour')}:${part('minute')}`;
}
// Resolve local wall time using the IANA zone; do not assume the browser's zone.
export function inventoryUtcTime(local:string){
 if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(local))throw new Error('Completá fecha y hora');
 const base=new Date(local+'Z').getTime();if(!Number.isFinite(base))throw new Error('Fecha inválida');
 let candidate=base;
 for(let i=0;i<3;i++)candidate+=base-new Date(inventoryLocalTime(new Date(candidate))+'Z').getTime();
 if(inventoryLocalTime(new Date(candidate))!==local)throw new Error('Esa hora no existe en la zona de Asunción');
 return new Date(candidate).toISOString();
}
export function inventoryMonthRange(month:string){
 const [year,m]=month.split('-').map(Number);
 const next=new Date(Date.UTC(year,m,1)).toISOString().slice(0,7);
 return {from:inventoryUtcTime(`${month}-01T00:00`),to:inventoryUtcTime(`${next}-01T00:00`)};
}
export function inventoryLocation(item:InventoryItem){
 if(item.location_type==='checked_out')return `Con ${item.current_custodian_name||'custodio registrado'} · ${item.production_name||'Producción'}${item.project_name?` · ${item.project_name}`:''}`;
 if(item.location_type==='legacy_in_use')return `En uso · ${item.current_custodian_name||'Custodio sin registrar'} · sin reserva vinculada`;
 return item.storage_shelf?`${item.storage_shelf}${item.storage_row?` · fila ${item.storage_row}`:''}`:'Ubicación sin registrar';
}
export function inventoryCanManageReservation(context:Pick<Context,'user_id'|'role'|'can_manage'|'can_reserve'>,row:InventoryReservation){return context.can_manage||context.can_reserve&&String(row.created_by_user_id)===String(context.user_id);}
export function inventoryCanReturn(context:Pick<Context,'user_id'|'role'|'can_manage'|'can_reserve'>,row:InventoryReservation){return context.can_reserve&&['owner','admin','management','production'].includes(context.role)&&(inventoryCanManageReservation(context,row)||[row.return_user_id,row.custodian_user_id].some(id=>String(id)===String(context.user_id)));}

export function InventoryWorkspace({role}:{role:string}){
 const allowed=['owner','admin','management','production','finance','editor','viewer'].includes(role);
 return allowed?<InventoryPanel key={role}/>:null;
}
function InventoryPanel(){
 const [context,setContext]=useState<Context|null>(null),[items,setItems]=useState<InventoryItem[]>([]),[categories,setCategories]=useState<Category[]>([]),[storageTemplates,setStorageTemplates]=useState<StorageTemplate[]>([]),[reservations,setReservations]=useState<InventoryReservation[]>([]);
 const [month,setMonth]=useState(()=>inventoryLocalTime(new Date()).slice(0,7)),[view,setView]=useState<'equipment'|'reservations'>('equipment'),[equipmentView,setEquipmentView]=useState<'grid'|'list'>('grid'),[selectedItems,setSelectedItems]=useState<string[]>([]),[reserveIds,setReserveIds]=useState<string[]>([]),[search,setSearch]=useState(''),[categoryFilter,setCategoryFilter]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [refreshError,setRefreshError]=useState(''),[lastUpdated,setLastUpdated]=useState<Date|null>(null);
 const hasData=useRef(false);
 const [editItem,setEditItem]=useState<InventoryItem|'new'|null>(null),[editReservation,setEditReservation]=useState<InventoryReservation|'new'|null>(null),[editCategory,setEditCategory]=useState<Category|'new'|null>(null),[editStorageTemplate,setEditStorageTemplate]=useState<StorageTemplate|'new'|null>(null),[verification,setVerification]=useState<InventoryItem|null>(null),[detail,setDetail]=useState<InventoryItem|null>(null);
 const [action,setAction]=useState<{kind:'checkout'|'return'|'cancel';row:InventoryReservation}|null>(null);
 const [archive,setArchive]=useState<InventoryItem|null>(null),[busy,setBusy]=useState(false),[archiveError,setArchiveError]=useState('');
 useEffect(()=>{
  let active=true,running=false;
  const {from,to}=inventoryMonthRange(month);
  async function load(background=false){
   if(!active||running||background&&document.visibilityState==='hidden')return;
   running=true;if(!hasData.current)setLoading(true);
   try{
    // Wait for every request to settle before permitting another polling cycle.
    const results=await Promise.allSettled([api<Context>('/api/agency/inventory-context'),api<{records:InventoryItem[]}>('/api/agency/inventory'),api<{categories:Category[]}>('/api/agency/inventory-categories'),api<{locations:StorageTemplate[]}>('/api/agency/inventory-locations'),api<{reservations:InventoryReservation[]}>(`/api/agency/inventory-reservations?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`)]);
    if(!active)return;
    const [c,i,cat,templates,r]=results;
    if(c.status==='rejected')throw c.reason;if(i.status==='rejected')throw i.reason;if(cat.status==='rejected')throw cat.reason;if(templates.status==='rejected')throw templates.reason;if(r.status==='rejected')throw r.reason;
    setContext(c.value);setItems(i.value.records);setCategories(cat.value.categories);setStorageTemplates(templates.value.locations);setReservations(r.value.reservations);
    hasData.current=true;setLastUpdated(new Date());setError('');setRefreshError('');
   }catch(error){if(active){if(hasData.current)setRefreshError(errorMessage(error));else setError(errorMessage(error));}}
   finally{running=false;if(active)setLoading(false);}
  }
  void load();
  const timer=window.setInterval(()=>{void load(true);},30000);
  const visible=()=>{if(document.visibilityState==='visible')void load(true);};
  document.addEventListener('visibilitychange',visible);
  return ()=>{active=false;window.clearInterval(timer);document.removeEventListener('visibilitychange',visible);};
 },[month,refresh]);
 function saved(message='Cambios guardados.'){setEditItem(null);setEditReservation(null);setEditCategory(null);setEditStorageTemplate(null);setVerification(null);setAction(null);setArchive(null);setSelectedItems([]);setReserveIds([]);setNotice(message);setRefresh(n=>n+1);}
 // Editors own their successful close so their footer form association is
 // released before the same dialog can be opened again. This only refreshes
 // the workspace after a persisted inventory/category mutation.
 function refreshed(message:string){setNotice(message);setRefresh(n=>n+1);}
 const visible=items.filter(item=>(!categoryFilter||String(item.category_id)===categoryFilter)&&`${itemCode(item)} ${item.name} ${item.serial_number||''} ${item.category_name||item.category} ${inventoryLocation(item)}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="ops-stack inventory-workspace">
  <section className="panel"><div className="inventory-toolbar"><div className="panel-heading inventory-title-block"><div><h2>Inventario y reservas</h2><p className="form-note">Ubicación registrada y préstamo de equipos por producción.</p></div></div><div className="inline-actions inventory-header-actions">{context?.can_manage?<button className="secondary" onClick={()=>setEditItem('new')}>Agregar equipo</button>:null}{context?.can_reserve&&selectedItems.length?<button className="primary" onClick={()=>{setReserveIds(selectedItems);setEditReservation('new');}}>Reservar {selectedItems.length} seleccionado{selectedItems.length===1?'':'s'}</button>:context?.can_reserve?<button className="primary" onClick={()=>{setReserveIds([]);setEditReservation('new');}}>Reservar equipos</button>:null}</div>
   <div className="inventory-toolbar-meta"><div className="inline-actions inventory-tabs" role="group" aria-label="Vistas de inventario"><button className={view==='equipment'?'secondary':'text-button'} aria-pressed={view==='equipment'} onClick={()=>setView('equipment')}>Equipos</button><button className={view==='reservations'?'secondary':'text-button'} aria-pressed={view==='reservations'} onClick={()=>setView('reservations')}>Calendario y reservas</button></div><p className="form-note inventory-refresh-note" role="status">Sincroniza cada 30 s mientras esta pestaña esté visible.{lastUpdated?` Actualizado ${lastUpdated.toLocaleTimeString('es-PY',{hour:'2-digit',minute:'2-digit'})}`:''}</p></div>
   {view==='equipment'?<div className="inventory-toolbar-controls"><div className="inventory-form-grid inventory-filters"><label>Buscar equipo o ubicación<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Memoria, DJI Mic, estante…"/></label><label>Categoría<select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Todas</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}{c.active?'':' · archivada'}</option>)}</select></label></div><div className="inventory-collection-toolbar"><p className="directory-summary" aria-live="polite">{visible.length} equipo{visible.length===1?'':'s'} visibles</p><ViewToggle label="Vista de inventario" value={equipmentView} onChange={setEquipmentView}/></div></div>:null}</div>
   {refreshError?<p role="status" className="inventory-late">No se pudo actualizar: {refreshError}. Se muestra la última información recibida.</p>:null}
   {notice?<p role="status">{notice}</p>:null}{error?<p className="error" role="alert">{error} <button className="text-button" onClick={()=>setRefresh(n=>n+1)}>Reintentar</button></p>:null}
   {loading?<p role="status">Cargando inventario…</p>:error?null:view==='equipment'?<>
    <div className={`inventory-equipment-grid ${equipmentView==='list'?'inventory-equipment-list':''}`}>{visible.map(item=>{const selectable=context?.can_reserve&&!['maintenance','retired'].includes(item.status);const chosen=selectedItems.includes(String(item.id)),code=itemCode(item),location=inventoryLocation(item);return <article className="inventory-equipment" key={item.id}><div className="panel-heading"><div className="inventory-item-title">{selectable&&<label className="inventory-item-select"><input type="checkbox" aria-label={`Seleccionar ${item.name} para reservar`} checked={chosen} onChange={()=>setSelectedItems(current=>chosen?current.filter(id=>id!==String(item.id)):[...current,String(item.id)])}/></label>}<div><h3>{item.name}</h3><code className="inventory-code">{code}</code></div></div><span>{({available:'Disponible',in_use:'En uso',maintenance:'Mantenimiento',retired:'Dado de baja'} as Record<string,string>)[item.status]||item.status}</span></div><div className="inventory-item-meta"><small>{item.category_name||item.category||'Sin categoría'}{item.serial_number?` · Serie / IMEI: ${item.serial_number}`:''}</small><span className="inventory-location">{location}</span>{item.last_verified_at?<span>Control: {verificationLabel(item.last_verification_result)} · {dateTime(item.last_verified_at)}{item.last_verifier_name?` · ${item.last_verifier_name}`:''}</span>:<span>Sin verificación física</span>}{item.return_user_name?<span>Devuelve: {item.return_user_name}{item.expected_return_at?` · previsto ${dateTime(item.expected_return_at)}`:''}</span>:null}<small>{money(item.value,item.currency)}</small></div><div className="inline-actions inventory-item-actions"><button className="text-button" onClick={()=>setDetail(item)}>Detalle y trazabilidad</button><button className="text-button" onClick={()=>printInventoryLabel({code,name:item.name,category:item.category_name||item.category||'Sin categoría',serial:item.serial_number,location})}>Etiqueta</button>{context?.can_manage?<><button className="text-button" onClick={()=>setVerification(item)}>Verificar</button><button className="text-button" onClick={()=>setEditItem(item)}>Editar equipo</button><button className="text-button" onClick={()=>setArchive(item)}>Archivar</button></>:null}</div></article>;})}</div>
    {!visible.length?<p className="empty-copy">No hay equipos que coincidan. {items.length?'Probá otra búsqueda.':'Agregá el equipo disponible antes de reservar.'}</p>:null}
   </>:<><label className="inventory-month">Mes del calendario<input type="month" value={month} min="1900-01" max="9998-12" onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value))setMonth(e.target.value);}}/></label><p className="form-note">Horarios de Asunción. Se incluyen retiros pendientes de devolución aunque sean de otro mes.</p><InventoryCalendar month={month} reservations={reservations}/><div className="inventory-reservation-list">{reservations.map(row=><article key={row.id} className="inventory-reservation"><div className="panel-heading"><h3>{row.title}</h3><span className={`inventory-status inventory-status-${row.status}`}>{statusLabels[row.status]}</span></div><p>{row.project_name} · {dateTime(row.starts_at)} → {dateTime(row.ends_at)}</p><p>{row.items.map(i=>i.name).join(' · ')}</p><div className="ops-stack">{row.actor_name&&<span>Reservado por <ActorIdentity name={row.actor_name} photoUrl={row.actor_photo_url} verified={row.actor_verified===true}/></span>}{row.checkout_actor_name&&<span>Retiro registrado por <ActorIdentity name={row.checkout_actor_name} photoUrl={row.checkout_actor_photo_url} verified={row.checkout_actor_verified===true}/></span>}{row.return_actor_name&&<span>Devolución registrada por <ActorIdentity name={row.return_actor_name} photoUrl={row.return_actor_photo_url} verified={row.return_actor_verified===true}/></span>}</div><p>Responsables: {row.responsible_members.map(p=>p.name).join(', ')}</p><p>Devuelve: {row.return_user_name}{row.status==='checked_out'?` · Custodio: ${row.custodian_name||'Sin registrar'}`:''}</p>{row.status==='checked_out'&&new Date(row.ends_at)<new Date()?<p className="inventory-late">Devolución pendiente desde {dateTime(row.ends_at)}.</p>:null}{context&&(inventoryCanManageReservation(context,row)||row.status==='checked_out'&&inventoryCanReturn(context,row))?<div className="inline-actions">{row.status==='reserved'?<><button className="text-button" onClick={()=>setEditReservation(row)}>Editar reserva</button><button className="secondary" onClick={()=>setAction({kind:'checkout',row})}>Registrar retiro</button><button className="text-button" onClick={()=>setAction({kind:'cancel',row})}>Cancelar reserva</button></>:row.status==='checked_out'?<button className="primary" onClick={()=>setAction({kind:'return',row})}>Registrar devolución</button>:null}</div>:null}</article>)}</div>{!reservations.length?<p className="empty-copy">Sin reservas en este mes. Elegí equipos y fechas para planificar una producción.</p>:null}</>}
  </section>
  {context?.can_manage?<section className="panel inventory-manager"><details><summary>Ubicaciones de guardado</summary><p className="form-note">Las ubicaciones archivadas dejan de estar disponibles para equipos nuevos. No se puede eliminar una ubicación con equipos asociados.</p><div className="inventory-template-list">{storageTemplates.map(template=><div className="inventory-template-row" key={template.id}><div><b>{template.name}</b><small>{template.item_count} equipo{template.item_count===1?'':'s'}{template.active?'':' · archivada'}</small></div><div className="inline-actions"><button className="text-button" onClick={()=>setEditStorageTemplate(template)}>Renombrar</button>{template.active?<button className="text-button" onClick={async()=>{try{await api(`/api/agency/inventory-locations/${template.id}`,{name:template.name,active:false},'PATCH');refreshed('Ubicación archivada.');}catch(error){setError(errorMessage(error));}}}>Archivar</button>:null}<button className="text-button" disabled={template.item_count>0} title={template.item_count>0?'No se puede eliminar: hay equipos asociados.':'Eliminar ubicación'} onClick={async()=>{if(template.item_count>0)return;try{await api(`/api/agency/inventory-locations/${template.id}`,undefined,'DELETE');refreshed('Ubicación eliminada.');}catch(error){setError(errorMessage(error));}}}>Eliminar</button></div></div>)}{!storageTemplates.length?<p className="form-note">Todavía no hay ubicaciones guardadas.</p>:null}<button className="text-button" onClick={()=>setEditStorageTemplate('new')}>Crear ubicación</button></div></details></section>:null}
  {context?.can_manage?<section className="panel"><details><summary>Categorías de equipos</summary><p className="form-note">Renombrar actualiza la categoría de sus equipos. Archivar la quita de nuevas selecciones.</p><div className="inventory-categories">{categories.map(c=><button className="secondary" key={c.id} onClick={()=>setEditCategory(c)}>{c.name}{c.active?'':' · archivada'}</button>)}<button className="text-button" onClick={()=>setEditCategory('new')}>Agregar categoría</button></div></details></section>:null}
  {editItem&&context?.can_manage?<Dialog title={editItem==='new'?'Nuevo equipo':editItem.name} close={()=>setEditItem(null)}><InventoryItemForm item={editItem==='new'?null:editItem} categories={categories} members={context.members} storageTemplates={storageTemplates} canManageStorage={context.can_manage} createStorageTemplate={async name=>{const result=await api<{location:StorageTemplate}>('/api/agency/inventory-locations',{name},'POST');setStorageTemplates(current=>[...current,result.location]);setRefresh(current=>current+1);return result.location;}} done={()=>refreshed('Equipo guardado.')}/></Dialog>:null}
  {editStorageTemplate&&context?.can_manage?<Dialog title={editStorageTemplate==='new'?'Nueva ubicación':'Editar ubicación'} close={()=>setEditStorageTemplate(null)}><StorageTemplateForm template={editStorageTemplate==='new'?null:editStorageTemplate} done={message=>saved(message)}/></Dialog>:null}
   {verification&&context?.can_manage?<Dialog title={`Verificación · ${verification.name}`} close={()=>setVerification(null)}><InventoryVerificationForm item={verification} done={()=>saved('Verificación física registrada.')}/></Dialog>:null}
  {detail?<Dialog title={`Inventario · ${detail.name}`} close={()=>setDetail(null)}><InventoryDetail item={detail}/></Dialog>:null}
  {editCategory&&context?.can_manage?<Dialog title={editCategory==='new'?'Nueva categoría':'Editar categoría'} close={()=>setEditCategory(null)}><Editor closeOnSave fields={[{key:'name',label:'Nombre de la categoría'},{key:'active',label:'Disponibilidad',choices:[{value:'true',label:'Activa'},{value:'false',label:'Archivada'}]}]} defaults={{name:editCategory==='new'?'':editCategory.name,active:String(editCategory==='new'||editCategory.active)}} save={async values=>{await api(`/api/agency/inventory-categories${editCategory==='new'?'':`/${editCategory.id}`}`,{name:values.name,active:values.active==='true'},editCategory==='new'?'POST':'PATCH');refreshed('Categoría guardada.');}}/></Dialog>:null}
  {editReservation&&context?.can_reserve?<Dialog title={editReservation==='new'?'Reservar equipos':'Editar reserva'} close={()=>setEditReservation(null)}><InventoryReservationForm key={editReservation==='new'?`new-${reserveIds.join('-')}`:editReservation.id} context={context} items={items} initialSelected={reserveIds} record={editReservation==='new'?null:editReservation} done={()=>saved('Reserva guardada. El retiro se registra por separado.')}/></Dialog>:null}
  {action?<Dialog title={{checkout:'Registrar retiro',return:'Registrar devolución',cancel:'Cancelar reserva'}[action.kind]} close={()=>setAction(null)}><InventoryTransitionForm action={action.kind} record={action.row} done={()=>saved({checkout:'Retiro registrado.',return:'Devolución registrada.',cancel:'Reserva cancelada.'}[action.kind])}/></Dialog>:null}
  {archive?<Dialog title={`Archivar ${archive.name}`} busy={busy} close={()=>{if(!busy){setArchive(null);setArchiveError('');}}}><p>El equipo quedará en Papelera. No se puede archivar mientras tenga reservas abiertas.</p>{archiveError?<p className="error" role="alert">{archiveError}</p>:null}<SaveActions pending={busy}><button type="button" className="primary" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);setArchiveError('');try{await api(`/api/agency/inventory/${archive.id}`,{},'DELETE');saved('Equipo archivado. Se puede restaurar desde Papelera.');}catch(error){setArchiveError(errorMessage(error));}finally{setBusy(false);}}}>{busy?'Archivando…':'Archivar equipo'}</button></SaveActions></Dialog>:null}
 </div>;
}

export function InventoryItemForm({item,categories,members,storageTemplates,canManageStorage,createStorageTemplate,done}:{item:InventoryItem|null;categories:Category[];members:Person[];storageTemplates:StorageTemplate[];canManageStorage:boolean;createStorageTemplate:(name:string)=>Promise<StorageTemplate>;done:()=>void}){
 const {currency:companyCurrency}=useCompanyCurrency();
 const [values,setValues]=useState(()=>({name:item?.name||'',category_id:String(item?.category_id||categories.find(c=>c.active)?.id||''),serial_number:item?.serial_number||'',storage_shelf:item?.storage_shelf||'',storage_row:item?.storage_row||'',value:item?.value||'0',currency:item?.currency||companyCurrency,status:item?.status||'available',custodian_user_id:String(item?.custodian_user_id||''),acquired_on:String(item?.acquired_on||'').slice(0,10),notes:String(item?.notes||'')}));
 const initialTemplate=String(item?.storage_location_id||'');
 const [templateId,setTemplateId]=useState(initialTemplate),[newPlace,setNewPlace]=useState(''),[creatingPlace,setCreatingPlace]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const availableTemplates=storageTemplates.filter(template=>template.active||template.id===initialTemplate);
 function change(key:keyof typeof values,value:string){setValues(current=>({...current,[key]:value}));}
 async function createPlace(){const name=newPlace.trim();if(!name||creatingPlace)return;setCreatingPlace(true);setError('');try{const template=await createStorageTemplate(name);setTemplateId(template.id);change('storage_shelf',template.name);setNewPlace('');}catch(error){setError(errorMessage(error));}finally{setCreatingPlace(false);}}
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/agency/inventory${item?`/${item.id}`:''}`,{...values,storage_location_id:templateId||null},item?'PATCH':'POST');done();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
 return <form className="inventory-form-grid inventory-item-form" onSubmit={submit}><p className="form-note inventory-wide">Un registro por unidad reservable. Al guardar se asigna un código único Scale OS, imprimible como etiqueta. Para un kit, indicá sus componentes en el nombre o las notas.</p>{item?<p className="form-note inventory-wide">Código de inventario: <code className="inventory-code">{itemCode(item)}</code></p>:null}
  <label className="inventory-wide">Nombre del equipo<input value={values.name} onChange={event=>change('name',event.target.value)} required minLength={2} maxLength={160}/></label>
  <label>Categoría<select value={values.category_id} onChange={event=>change('category_id',event.target.value)}>{categories.filter(c=>c.active||String(c.id)===String(item?.category_id)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  <label>Serie, IMEI o identificador<input value={values.serial_number} onChange={event=>change('serial_number',event.target.value)} maxLength={160}/></label>
  <fieldset className="inventory-wide inventory-storage-field"><legend>Ubicación de guardado</legend><label>Ubicación<select value={templateId} onChange={event=>{const id=event.target.value;setTemplateId(id);const template=availableTemplates.find(candidate=>candidate.id===id);if(template)change('storage_shelf',template.name);}}><option value="">Custom location…</option>{availableTemplates.map(template=><option key={template.id} value={template.id}>{template.name}{template.active?'':' · archivada'}</option>)}</select></label>{!templateId?<label>Ubicación personalizada<input value={values.storage_shelf} onChange={event=>change('storage_shelf',event.target.value)} maxLength={100} placeholder="Estante, depósito o lugar"/></label>:<p className="form-note">Se guarda como {availableTemplates.find(template=>template.id===templateId)?.name||values.storage_shelf}.</p>}{canManageStorage?<div className="inventory-create-place"><label>Crear lugar<input value={newPlace} onChange={event=>setNewPlace(event.target.value)} maxLength={100} placeholder="Ej.: Depósito · Rack A"/></label><button type="button" className="text-button" disabled={!newPlace.trim()||creatingPlace} onClick={()=>void createPlace()}>{creatingPlace?'Creando…':'Crear lugar'}</button></div>:null}<label>Fila / posición<input value={values.storage_row} onChange={event=>change('storage_row',event.target.value)} maxLength={80}/></label></fieldset>
  <label>Valor del equipo<input type="number" min="0" step="0.01" value={values.value} onChange={event=>change('value',event.target.value)} required/></label>
  <label>Moneda<select value={values.currency} onChange={event=>change('currency',event.target.value)}>{currencyChoices.map(choice=><option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label>
  <label>Estado<select value={values.status} onChange={event=>change('status',event.target.value)}>{(item?.status==='in_use'?[{value:'in_use',label:'En uso (registrar devolución)'}]:itemStatuses).map(choice=><option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label>
  <label>Custodio registrado<select value={values.custodian_user_id} onChange={event=>change('custodian_user_id',event.target.value)}><option value="">Sin custodio</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label>
  <label>Fecha de adquisición<input type="date" value={values.acquired_on} onChange={event=>change('acquired_on',event.target.value)}/></label><label className="inventory-wide">Notas<textarea value={values.notes} onChange={event=>change('notes',event.target.value)} maxLength={2000}/></label>
  {error?<p className="error inventory-wide" role="alert">{error}</p>:null}<SaveActions pending={busy}><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar equipo'}</button></SaveActions>
 </form>;
}

function StorageTemplateForm({template,done}:{template:StorageTemplate|null;done:(message:string)=>void}){
 const [name,setName]=useState(template?.name||''),[active,setActive]=useState(template?.active??true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="inventory-form-grid" onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/agency/inventory-locations${template?`/${template.id}`:''}`,{name,active},template?'PATCH':'POST');done(template?'Ubicación actualizada.':'Ubicación creada.');}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}}><label className="inventory-wide">Nombre de la ubicación<input value={name} onChange={event=>setName(event.target.value)} required minLength={2} maxLength={100}/></label>{template?<label className="inventory-wide inventory-check"><input type="checkbox" checked={active} onChange={event=>setActive(event.target.checked)}/><span>Disponible para nuevas asignaciones</span></label>:null}{error?<p className="error inventory-wide" role="alert">{error}</p>:null}<SaveActions pending={busy}><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar ubicación'}</button></SaveActions></form>;
}

const traceLabel=(event:string)=>({
 'inventory.created':'Equipo registrado','inventory.updated':'Ficha actualizada','stock.verified':'Verificación física','reservation.reserved':'Reserva creada','reservation.updated':'Reserva actualizada','reservation.cancelled':'Reserva cancelada','loan.checked_out':'Retiro registrado','loan.checked_in':'Devolución registrada'
} as Record<string,string>)[event]||event.replace(/[._]/g,' ');
export function InventoryDetail({item}:{item:InventoryItem}){
 const [data,setData]=useState<{record:InventoryItem;verifications:InventoryVerification[];trace:InventoryTrace[]}|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;void api<{record:InventoryItem;verifications:InventoryVerification[];trace:InventoryTrace[]}>(`/api/agency/inventory/${item.id}`).then(result=>{if(alive)setData(result);}).catch(cause=>{if(alive)setError(errorMessage(cause));});return()=>{alive=false;};},[item.id]);
 const record=data?.record||item,code=itemCode(record);
 return <div className="inventory-detail"><section className="inventory-code-payload"><div><p className="eyebrow">IDENTIFICACIÓN FÍSICA</p><code className="inventory-code">{code}</code><p>{record.name} · {record.serial_number||'Sin serie registrada'}</p><p className="form-note">{inventoryLocation(record)}</p></div><InventoryBarcode code={code}/></section>{error?<p className="error" role="alert">{error}</p>:null}{!data&&!error?<p role="status">Cargando trazabilidad…</p>:<><section><h3>Verificación física</h3>{record.last_verified_at?<p><b>{verificationLabel(record.last_verification_result)}</b> · {dateTime(record.last_verified_at)}{record.last_verifier_name?` · ${record.last_verifier_name}`:''}</p>:<p>Sin verificación física registrada.</p>}{data?.verifications.map(row=><article className="inventory-trace-row" key={`verification-${row.id}`}><b>{verificationLabel(row.result)}</b><span>{dateTime(row.verified_at)} · {row.verifier_name||'Usuario registrado'}</span>{row.differences?<p>{row.differences}</p>:null}{row.note?<p>{row.note}</p>:null}</article>)}</section><section><h3>Rastro de préstamo y cambios</h3>{data?.trace.map(row=><article className="inventory-trace-row" key={row.id}><b>{traceLabel(row.event_type)}</b><span>{dateTime(row.event_at)} · {row.actor_name||'Sistema'}</span>{row.event_data?.title?<p>{String(row.event_data.title)}</p>:null}</article>)}{!data?.trace.length?<p>Sin eventos registrados todavía.</p>:null}</section></>}</div>;
}

function InventoryVerificationForm({item,done}:{item:InventoryItem;done:()=>void}){
 const [result,setResult]=useState<'confirmed'|'difference'|'missing'>('confirmed'),[differences,setDifferences]=useState(''),[note,setNote]=useState(''),[adjust,setAdjust]=useState(false),[status,setStatus]=useState(item.status),[shelf,setShelf]=useState(item.storage_shelf),[row,setRow]=useState(item.storage_row),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/agency/inventory/${item.id}/verify`,{result,differences,note,...(adjust?{adjustment:{status,storage_shelf:shelf,storage_row:row}}:{})},'POST');done();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
 return <form className="inventory-form-grid" onSubmit={submit}><p className="form-note inventory-wide">Código: <code className="inventory-code">{itemCode(item)}</code>. El control queda fechado, asociado a tu usuario y no cambia reservas existentes.</p><label>Resultado<select value={result} onChange={event=>setResult(event.target.value as typeof result)}><option value="confirmed">Coincide con el registro</option><option value="difference">Hay una diferencia</option><option value="missing">No encontrado</option></select></label><label>Observación<textarea value={note} maxLength={2000} onChange={event=>setNote(event.target.value)} placeholder="Ej.: revisión mensual"/></label>{result!=='confirmed'?<label className="inventory-wide">Diferencias encontradas<textarea value={differences} required maxLength={2000} onChange={event=>setDifferences(event.target.value)} placeholder="Qué no coincide con el registro"/></label>:null}<label className="inventory-wide inventory-check"><input type="checkbox" checked={adjust} disabled={item.location_type==='checked_out'} onChange={event=>setAdjust(event.target.checked)}/><span>Ajustar estado o ubicación registrada{item.location_type==='checked_out'?' (no disponible mientras esté retirado)':''}</span></label>{adjust?<><label>Estado real<select value={status} onChange={event=>setStatus(event.target.value)}>{itemStatuses.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>Ubicación real<input value={shelf} maxLength={100} required onChange={event=>setShelf(event.target.value)}/></label><label>Fila / posición<input value={row} maxLength={80} onChange={event=>setRow(event.target.value)}/></label></>:null}{error?<p className="error inventory-wide" role="alert">{error}</p>:null}<SaveActions pending={busy}><button className="primary" disabled={busy}>{busy?'Registrando…':'Registrar verificación'}</button></SaveActions></form>;
}

export function InventoryReservationForm({context,items,record,done,initialSelected=[]}:{context:Context;items:InventoryItem[];record:InventoryReservation|null;done:()=>void;initialSelected?:string[]}){
 const [title,setTitle]=useState(record?.title||''),[project,setProject]=useState(String(record?.project_id||'')),[start,setStart]=useState(record?inventoryLocalTime(record.starts_at):''),[end,setEnd]=useState(record?inventoryLocalTime(record.ends_at):'');
 const [selected,setSelected]=useState<string[]>(record?.items.map(i=>String(i.id))||initialSelected),[responsibles,setResponsibles]=useState<string[]>(record?.responsible_members.map(p=>String(p.id))||(context.role==='production'?[context.user_id]:[])),[returnPerson,setReturnPerson]=useState(String(record?.return_user_id||'')),[notes,setNotes]=useState(record?.notes||''),[search,setSearch]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const toggle=(id:string,list:string[],set:(list:string[])=>void)=>set(list.includes(id)?list.filter(value=>value!==id):[...list,id]);
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setError('');setBusy(true);try{
  if(!selected.length)throw new Error('Elegí al menos un equipo');if(!responsibles.length)throw new Error('Elegí al menos un responsable');if(!responsibles.includes(returnPerson))throw new Error('Elegí quién se encarga de devolver los equipos');
  const starts=inventoryUtcTime(start),ends=inventoryUtcTime(end);if(ends<=starts)throw new Error('La devolución prevista debe ser posterior al inicio');
  await api(`/api/agency/inventory-reservations${record?`/${record.id}`:''}`,{title,project_id:project,starts_at:starts,ends_at:ends,inventory_ids:selected,responsible_user_ids:responsibles,return_user_id:returnPerson,notes,...(record?{expected_version:record.version}:{})},record?'PATCH':'POST');done();
 }catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
 return <form className="inventory-form-grid" onSubmit={submit}>
  <label className="inventory-wide">Producción o uso previsto<input value={title} onChange={e=>setTitle(e.target.value)} required minLength={2} maxLength={160} placeholder="Rodaje de contenidos · cliente"/></label>
  <label className="inventory-wide">Proyecto<select value={project} onChange={e=>setProject(e.target.value)} required><option value="">Elegí un proyecto activo</option>{context.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
  <label>Desde · Asunción<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>Devolución prevista · Asunción<input type="datetime-local" value={end} min={start||undefined} onChange={e=>setEnd(e.target.value)} required/></label>
  <fieldset className="inventory-wide"><legend>Equipos · {selected.length} seleccionados</legend><label>Buscar equipos<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Memoria, DJI Mic…"/></label><div className="inventory-options">{items.filter(i=>`${i.name} ${i.category_name||i.category}`.toLowerCase().includes(search.toLowerCase())).map(i=><label className="inventory-check" key={i.id}><input type="checkbox" checked={selected.includes(String(i.id))} disabled={['maintenance','retired'].includes(i.status)&&!selected.includes(String(i.id))} onChange={()=>toggle(String(i.id),selected,setSelected)}/><span>{i.name}<small>{i.status==='in_use'?'Actualmente en uso; el retiro depende de su devolución':i.status==='maintenance'?'En mantenimiento':i.status==='retired'?'Dado de baja':i.category_name||i.category}</small></span></label>)}</div><small>Se verifica que los equipos no tengan otra reserva en el horario elegido.</small></fieldset>
  <fieldset className="inventory-wide"><legend>Responsables · {responsibles.length}</legend><div className="inventory-options">{context.members.map(p=><label className="inventory-check inventory-person-check" key={p.id}><input type="checkbox" checked={responsibles.includes(String(p.id))} onChange={()=>{toggle(String(p.id),responsibles,setResponsibles);if(returnPerson===String(p.id))setReturnPerson('');}}/><ActorIdentity name={p.name} photoUrl={p.photo_url} verified/></label>)}</div></fieldset>
  <label className="inventory-wide">Responsable de devolución<select value={returnPerson} onChange={e=>setReturnPerson(e.target.value)} required><option value="">Elegí entre los responsables</option>{context.members.filter(p=>responsibles.includes(String(p.id))).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>{returnPerson&&context.members.find(p=>String(p.id)===returnPerson)&&<span className="inventory-return-person"><ActorIdentity name={context.members.find(p=>String(p.id)===returnPerson)!.name} photoUrl={context.members.find(p=>String(p.id)===returnPerson)!.photo_url} verified/></span>}</label>
  <label className="inventory-wide">Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label>
  <p className="form-note inventory-wide">Reservar no registra el retiro. Al retirar se indica quién lleva físicamente los equipos; al devolver se registra dónde quedan.</p>
  {error?<p className="error inventory-wide" role="alert">{error}</p>:null}<SaveActions pending={busy}><button className="primary" disabled={busy||!context.projects.length}>{busy?'Guardando…':'Guardar reserva'}</button></SaveActions>
 </form>;
}

export function InventoryTransitionForm({action,record,done}:{action:'checkout'|'return'|'cancel';record:InventoryReservation;done:()=>void}){
 const [custodian,setCustodian]=useState(''),[locations,setLocations]=useState(record.items.map(i=>({inventory_id:String(i.id),storage_shelf:i.storage_shelf||'',storage_row:i.storage_row||'',status:'available'}))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 function location(index:number,key:'storage_shelf'|'storage_row'|'status',value:string){setLocations(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));}
 return <form className="inventory-form-grid" onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(`/api/agency/inventory-reservations/${record.id}/${action}`,{expected_version:record.version,...(action==='checkout'?{custodian_user_id:custodian}:action==='return'?{locations}:{})});done();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}}>
  <p className="inventory-wide">{record.title} · {record.items.map(i=>i.name).join(', ')}</p>
  {action==='checkout'?<><label className="inventory-wide">Quién lleva los equipos (custodio)<select value={custodian} onChange={e=>setCustodian(e.target.value)} required><option value="">Elegí al custodio real</option>{record.responsible_members.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="form-note inventory-wide">Responsable de devolución: {record.return_user_name}. Confirmá el retiro cuando los equipos se entreguen físicamente, dentro del horario reservado.</p></>:action==='return'?<><p className="form-note inventory-wide">Registrá la devolución completa y revisá dónde queda cada equipo. No se libera ninguno hasta guardar todos.</p>{locations.map((row,index)=><fieldset className="inventory-wide inventory-form-grid" key={row.inventory_id}><legend>{record.items[index].name}</legend><label>Estante o lugar de guardado<input value={row.storage_shelf} maxLength={100} required onChange={e=>location(index,'storage_shelf',e.target.value)}/></label><label>Fila / posición<input value={row.storage_row} maxLength={80} onChange={e=>location(index,'storage_row',e.target.value)}/></label><label>Estado al devolver<select value={row.status} onChange={e=>location(index,'status',e.target.value)}><option value="available">Disponible</option><option value="maintenance">Necesita mantenimiento</option></select></label></fieldset>)}</>:<p className="inventory-wide">Cancelar libera todos los equipos de esta reserva. Solo aplica si todavía no se retiraron.</p>}
  {error?<p className="error inventory-wide" role="alert">{error}</p>:null}<SaveActions pending={busy}><button className="primary" disabled={busy}>{busy?'Guardando…':{checkout:'Confirmar retiro',return:'Confirmar devolución completa',cancel:'Confirmar cancelación'}[action]}</button></SaveActions>
 </form>;
}

export function InventoryCalendar({month,reservations}:{month:string;reservations:InventoryReservation[]}){
 const [year,m]=month.split('-').map(Number),days=new Date(Date.UTC(year,m,0)).getUTCDate(),offset=(new Date(Date.UTC(year,m-1,1)).getUTCDay()+6)%7;
 return <div className="inventory-calendar" aria-label="Calendario mensual de reservas"><div className="inventory-weekdays" aria-hidden="true">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(day=><span key={day}>{day}</span>)}</div><div className="inventory-calendar-grid">{Array.from({length:offset},(_,index)=><div className="inventory-calendar-blank" key={`blank-${index}`}/>)}{Array.from({length:days},(_,index)=>{
  const day=`${month}-${String(index+1).padStart(2,'0')}`,start=inventoryUtcTime(day+'T00:00'),nextDay=new Date(Date.UTC(year,m-1,index+2)).toISOString().slice(0,10),end=inventoryUtcTime(nextDay+'T00:00');
  const rows=reservations.filter(r=>r.status!=='cancelled'&&r.starts_at<end&&r.ends_at>start);
  return <div className="inventory-calendar-day" key={day} aria-label={day}><time dateTime={day}>{index+1}</time>{rows.map(r=><div className={`inventory-calendar-event inventory-status-${r.status}`} key={r.id}><b>{r.title}</b><small>{r.items.length} equipo(s) · {statusLabels[r.status]}</small></div>)}</div>;
 })}</div></div>;
}
