"use client";
import {useEffect,useState} from 'react';
import {api,Editor} from './operations';
import {teamRoleLabels} from './team-directory';
import {Link2,UserCheck,Copy,X} from 'lucide-react';
import {ActorIdentity} from './actor-identity';
import './invite-links.css';
type ActorFields={actor_name?:string;actor_photo_url?:string;actor_verified?:boolean};
type LinkRow=ActorFields&{id:string;role:string;mode:string;expires_at:string;revoked_at:string|null;used_at:string|null;click_count:number;account_count:number;url:string|null;created_by_email:string;joined_users:Array<ActorFields&{email:string;full_name:string;joined_at:string}>};
type RequestRow=ActorFields&{id:string;full_name:string;email:string;role:string;created_at:string;status:'pending'|'unavailable';unavailableReason:string|null};
const unavailableLabels:Record<string,string>={revoked:'El enlace fue revocado.',expired:'El enlace venció.',used:'El enlace ya fue utilizado.',organization_unavailable:'La empresa no está disponible.',existing_access:'La persona ya tiene un registro de acceso. Administralo desde Equipo.'};
export function InviteLinks({role}:{role:string}){
 const [links,setLinks]=useState<LinkRow[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[created,setCreated]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState('');
 async function load(){try{const [a,b]=await Promise.all([api<{links:LinkRow[]}>('/api/agency/invite-links'),api<{requests:RequestRow[]}>('/api/agency/access-requests')]);setLinks(a.links);setRequests(b.requests);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar');}}
 useEffect(()=>{void load();},[]);
 async function act(path:string,data:unknown,method='POST'){setBusy(true);try{await api(path,data,method);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}}
 return <section className="panel ops-stack invite-links"><header className="invite-links-header"><div><p className="invite-links-kicker">Acceso de equipo</p><h2><Link2 size={20} aria-hidden="true"/> Invitaciones por enlace</h2><p className="form-note">Creá un acceso temporal, copiá el enlace y revocalo cuando ya no haga falta.</p></div></header>
 {error&&<p role="alert">{error}</p>}
 <div className="invite-link-create"><h3>Crear enlace</h3><Editor columns fields={[{key:'role',label:'Permiso del enlace',choices:Object.entries(teamRoleLabels).filter(([value])=>value!=='owner'||role==='owner').map(([value,label])=>({value,label}))},{key:'mode',label:'Tipo de invitación',choices:[{value:'single',label:'Una persona · un solo uso'},{value:'approval',label:'Varias personas · requiere aprobación'}]}]} defaults={{role:'viewer',mode:'single'}} label="Generar enlace" save={async values=>{const result=await api<{url:string}>('/api/agency/invite-links',values);setCreated(result.url);setCopied('');await load();}}/></div>
 {created&&<div className="invite-link-created" role="status"><label>Enlace generado<input readOnly value={created} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(created);setCopied(created);setTimeout(()=>setCopied(''),1800);}catch{setError('Seleccioná el enlace y copialo manualmente.');}}}><Copy size={16} aria-hidden="true"/>{copied===created?'Copiado':'Copiar enlace'}</button></div>}
 <div className="invite-links-section"><div className="invite-links-section-heading"><div><h3><UserCheck size={18} aria-hidden="true"/> Solicitudes</h3><p className="form-note">Aprobá solo los accesos disponibles.</p></div><span className="invite-links-count">{requests.length}</span></div>{!requests.length&&<p className="invite-links-empty">No hay solicitudes pendientes.</p>}{requests.map(r=><article className="payment-row invite-link-row" key={r.id}><div className="invite-link-person"><ActorIdentity name={r.actor_name||r.full_name||r.email} photoUrl={r.actor_photo_url} verified={r.actor_verified===true} timestamp={r.created_at}/><p>{r.email} · {teamRoleLabels[r.role]}</p>{r.status!=='pending'&&<p role="status">Solicitud no disponible. {unavailableLabels[r.unavailableReason||'']||'Actualizá la lista para comprobar la invitación.'}</p>}</div><div className="actions invite-link-actions">{r.status==='pending'&&<button className="secondary" disabled={busy||(r.role==='owner'&&role!=='owner')} onClick={()=>act(`/api/agency/access-requests/${r.id}`,{action:'approve'},'PATCH')}>Aprobar acceso</button>}<button className="text-button" disabled={busy||(r.role==='owner'&&role!=='owner')} onClick={()=>act(`/api/agency/access-requests/${r.id}`,{action:'reject'},'PATCH')}>Rechazar</button></div></article>)}</div>
 <div className="invite-links-recent"><div className="invite-links-section-heading"><h3>Enlaces recientes</h3><span className="invite-links-count">{links.length}</span></div>{!links.length&&<p className="invite-links-empty">Todavía no creaste enlaces. Generá uno cuando necesites sumar a alguien.</p>}{links.map(l=><article className="payment-row invite-link-row" key={l.id}><div className="invite-link-person"><strong>{teamRoleLabels[l.role]} · {l.mode==='single'?'Un solo uso':'Con aprobación'}</strong><p>{l.revoked_at?'Revocado':l.used_at?'Utilizado':`Vence ${new Date(l.expires_at).toLocaleDateString('es-PY')}`} · {l.click_count} clics · {l.account_count} cuentas creadas</p><p>Creado por <ActorIdentity name={l.actor_name||l.created_by_email} photoUrl={l.actor_photo_url} verified={l.actor_verified===true}/></p>{l.joined_users?.length?<div className="invite-link-joined"><small>Usuarios que se unieron</small>{l.joined_users.map((j,i)=><p key={`${j.email}-${i}`}><ActorIdentity name={j.actor_name||j.full_name||j.email} photoUrl={j.actor_photo_url} verified={j.actor_verified===true} timestamp={j.joined_at}/></p>)}</div>:<small>Ningún usuario se unió todavía.</small>}</div><div className="actions invite-link-actions">{l.url&&<button className="secondary" disabled={busy} onClick={async()=>{try{await navigator.clipboard.writeText(l.url!);setCopied(l.url!);setTimeout(()=>setCopied(''),1800);}catch{setError('Seleccioná el enlace y copialo manualmente.');}}}><Copy size={16} aria-hidden="true"/>{copied===l.url?'Copiado':'Copiar enlace'}</button>}{!l.revoked_at&&!l.used_at&&<button className="text-button" disabled={busy} onClick={()=>act(`/api/agency/invite-links/${l.id}`,{},'DELETE')}><X size={16} aria-hidden="true"/>Revocar</button>}</div></article>)}</div></section>;
}
