"use client";
import {useEffect,useState} from 'react';
import {api,Editor} from './operations';
import {teamRoleLabels} from './team-directory';
import {Link2,UserCheck,Copy,X} from 'lucide-react';
type LinkRow={id:string;role:string;mode:string;expires_at:string;revoked_at:string|null;used_at:string|null;click_count:number;account_count:number;url:string|null;created_by_email:string;joined_users:Array<{email:string;full_name:string;joined_at:string}>};
type RequestRow={id:string;full_name:string;email:string;role:string;created_at:string;status:'pending'|'unavailable';unavailableReason:string|null};
const unavailableLabels:Record<string,string>={revoked:'El enlace fue revocado.',expired:'El enlace venció.',used:'El enlace ya fue utilizado.',organization_unavailable:'La empresa no está disponible.',existing_access:'La persona ya tiene un registro de acceso. Administralo desde Equipo.'};
export function InviteLinks({role}:{role:string}){
 const [links,setLinks]=useState<LinkRow[]>([]),[requests,setRequests]=useState<RequestRow[]>([]),[created,setCreated]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState('');
 async function load(){try{const [a,b]=await Promise.all([api<{links:LinkRow[]}>('/api/agency/invite-links'),api<{requests:RequestRow[]}>('/api/agency/access-requests')]);setLinks(a.links);setRequests(b.requests);setError('');}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar');}}
 useEffect(()=>{void load();},[]);
 async function act(path:string,data:unknown,method='POST'){setBusy(true);try{await api(path,data,method);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}}
 return <section className="panel ops-stack"><div><h2><Link2 size={20}/> Invitaciones por enlace</h2><p className="form-note">Elegí el permiso. Los enlaces vencen en 7 días y podés revocarlos. La persona verifica su correo con Google.</p></div>
 {error&&<p role="alert">{error}</p>}
 <Editor columns fields={[{key:'role',label:'Permiso del enlace',choices:Object.entries(teamRoleLabels).filter(([value])=>value!=='owner'||role==='owner').map(([value,label])=>({value,label}))},{key:'mode',label:'Tipo de invitación',choices:[{value:'single',label:'Una persona · un solo uso'},{value:'approval',label:'Varias personas · requiere aprobación'}]}]} defaults={{role:'viewer',mode:'single'}} label="Generar enlace" save={async values=>{const result=await api<{url:string}>('/api/agency/invite-links',values);setCreated(result.url);setCopied('');await load();}}/>
 {created&&<div className="ops-stack"><label>Enlace generado<input readOnly value={created} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(created);setCopied(created);setTimeout(()=>setCopied(''),1800);}catch{setError('Seleccioná el enlace y copialo manualmente.');}}}><Copy size={16}/>{copied===created?'Copiado':'Copiar enlace'}</button></div>}
 <div><h3><UserCheck size={18}/> Solicitudes por revisar · {requests.length}</h3><p className="form-note">Solo las solicitudes disponibles pueden aprobarse. Si el enlace venció o fue revocado, generá otro y pedí una nueva solicitud. No se envía un correo automático.</p>{!requests.length&&<p>No hay solicitudes pendientes.</p>}{requests.map(r=><article className="payment-row" key={r.id}><div><strong>{r.full_name}</strong><p>{r.email} · {teamRoleLabels[r.role]}</p>{r.status!=='pending'&&<p role="status">Solicitud no disponible. {unavailableLabels[r.unavailableReason||'']||'Actualizá la lista para comprobar la invitación.'}</p>}</div><div className="actions">{r.status==='pending'&&<button className="secondary" disabled={busy||(r.role==='owner'&&role!=='owner')} onClick={()=>act(`/api/agency/access-requests/${r.id}`,{action:'approve'},'PATCH')}>Aprobar acceso</button>}<button className="text-button" disabled={busy||(r.role==='owner'&&role!=='owner')} onClick={()=>act(`/api/agency/access-requests/${r.id}`,{action:'reject'},'PATCH')}>Rechazar</button></div></article>)}</div>
 <details><summary>Enlaces recientes · {links.length}</summary>{links.map(l=><div className="payment-row" key={l.id}><div><strong>{teamRoleLabels[l.role]} · {l.mode==='single'?'Un solo uso':'Con aprobación'}</strong><p>{l.revoked_at?'Revocado':l.used_at?'Utilizado':`Vence ${new Date(l.expires_at).toLocaleDateString('es-PY')}`} · {l.click_count} clics · {l.account_count} cuentas creadas</p><p>Creado por {l.created_by_email||'Sistema'}</p>{l.joined_users?.length?<div><small>Usuarios que se unieron</small>{l.joined_users.map((j,i)=><p key={`${j.email}-${i}`}>{j.full_name} · {j.email}</p>)}</div>:<small>Ningún usuario se unió todavía.</small>}</div><div className="actions">{l.url&&<button className="secondary" disabled={busy} onClick={async()=>{try{await navigator.clipboard.writeText(l.url!);setCopied(l.url!);setTimeout(()=>setCopied(''),1800);}catch{setError('Seleccioná el enlace y copialo manualmente.');}}}><Copy size={16}/>{copied===l.url?'Copiado':'Copiar enlace'}</button>}{!l.revoked_at&&!l.used_at&&<button className="text-button" disabled={busy} onClick={()=>act(`/api/agency/invite-links/${l.id}`,{},'DELETE')}><X size={16}/>Revocar</button>}</div></div>)}</details></section>;
}
