"use client";
import {ActorIdentity} from './actor-identity';
import {useEffect,useState} from 'react';
import {Bell} from 'lucide-react';
import {api,Editor} from './operations';
import {Dialog} from './dialog';
import {notify} from './feedback';
import './notifications.css';
type Notice={id:string;title:string;body:string;work_order_id:string|null;read_at:string|null;created_at:string};
type Inbox={notifications:Notice[];unread:number;next:string|null};
const error=(e:unknown)=>e instanceof Error?e.message:'No se pudieron cargar los avisos.';
export function NotificationBell({openOrder}:{openOrder:(id:string)=>void}){
 const [open,setOpen]=useState(false),[prefs,setPrefs]=useState(false),[data,setData]=useState<Inbox>({notifications:[],unread:0,next:null}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;async function refresh(){try{const d=await api<Inbox>('/api/agency/notifications');if(alive){setData(d);setMessage('');}}catch(e){if(alive)setMessage(error(e));}finally{if(alive)setLoading(false);}}
  void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},60000);return()=>{alive=false;clearInterval(timer);};
 },[open]);
 async function read(n?:Notice){setBusy(true);try{await api('/api/agency/notifications/'+(n?.id||'read-all'),{},'PATCH');setData(await api<Inbox>('/api/agency/notifications'));if(n?.work_order_id){setOpen(false);openOrder(String(n.work_order_id));}}catch(e){setMessage(error(e));}finally{setBusy(false);}}
 return <><button className="icon-button notification-trigger" aria-label={`Notificaciones${data.unread?`, ${data.unread} sin leer`:''}`} onClick={()=>setOpen(true)}><Bell size={19}/>{data.unread>0&&<span className="notification-badge">{data.unread>99?'99+':data.unread}</span>}</button>
 {open&&<Dialog title="Notificaciones" close={()=>setOpen(false)} variant="drawer"><div className="notification-actions"><button className="text-button" onClick={()=>setPrefs(true)}>Preferencias</button><button className="text-button" disabled={busy||!data.unread} onClick={()=>void read()}>Marcar todas como leídas</button></div>{message&&<p role="alert">{message}</p>}{loading?<p>Cargando avisos…</p>:!data.notifications.length?<p className="empty-copy">Estás al día. Acá verás asignaciones, comentarios y entregas pendientes. Tus propias acciones no generan avisos.</p>:<div className="notification-list">{data.notifications.map(n=><article key={n.id} className={n.read_at?'notice':'notice unread'}><b>{n.title}</b><p>{n.body}</p><time>{new Date(n.created_at).toLocaleString('es-PY')}</time><button className="text-button" disabled={busy} onClick={()=>void read(n)}>{n.work_order_id?'Ver pieza':n.read_at?'Leída':'Marcar como leída'}</button></article>)}</div>}{data.next&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await api<Inbox>('/api/agency/notifications?before='+data.next);setData(old=>({...d,notifications:[...old.notifications,...d.notifications]}));}catch(e){setMessage(error(e));}finally{setBusy(false);}}}>Ver avisos anteriores</button>}</Dialog>}
 {prefs&&<Preferences close={()=>setPrefs(false)}/>}</>;
}
function Preferences({close}:{close:()=>void}){
 const [values,setValues]=useState<Record<string,string>|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;void api<{preferences:Record<string,boolean>}>('/api/agency/notifications/preferences').then(d=>{if(alive)setValues(Object.fromEntries(Object.entries(d.preferences).map(([k,v])=>[k,String(v)])));}).catch(e=>{if(alive)setMessage(error(e));});return()=>{alive=false;};},[]);
 return <Dialog title="Preferencias de notificaciones" close={close}><p>Estas preferencias solo afectan tu usuario en esta empresa. Los correos operativos son opcionales; no cambian las invitaciones ni la recuperación de contraseña.</p>{message&&<p role="alert">{message}</p>}{values?<Editor fields={[['email_enabled','Recibir también por correo'],['assignment','Asignaciones'],['comment','Comentarios y menciones por @correo'],['due','Entregas pendientes']].map(([key,label])=>({key,label,choices:[{value:'true',label:'Sí'},{value:'false',label:'No'}]}))} defaults={values} save={async v=>{await api('/api/agency/notifications/preferences',Object.fromEntries(Object.entries(v).map(([k,val])=>[k,val==='true'])),'PATCH');close();}}/>:<p>Cargando preferencias…</p>}</Dialog>;
}

type Schedule={actor_name?:string;actor_photo_url?:string;actor_verified?:boolean;id:string;template_name:string;project_name:string;next_month:string;active:boolean};
export function MonthlySchedules({projects,templates,people}:{projects:{id:string;name:string;client_name:string}[];templates:{id:string;name:string}[];people:{value:string;label:string}[]}){
 const [open,setOpen]=useState(false),[creating,setCreating]=useState(false),[rows,setRows]=useState<Schedule[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setRows((await api<{schedules:Schedule[]}>('/api/agency/schedules')).schedules);}
 useEffect(()=>{if(open)void load().catch(e=>setMessage(error(e)));},[open]);
 return <><button className="text-button" onClick={()=>setOpen(true)}>Programar generación automática</button>{open&&<Dialog title="Producción mensual automática" close={()=>setOpen(false)}><p>Crea las piezas de la plantilla cada mes. No genera facturas ni cobros. Si la tanda ya existe, no la duplica. Podés pausar una programación en cualquier momento.</p>{message&&<p role="alert">{message}</p>}<button className="secondary" onClick={()=>setCreating(v=>!v)}>{creating?'Cancelar nueva programación':'Nueva programación'}</button>{creating&&<Editor fields={[{key:'template_id',label:'Plantilla',choices:templates.map(t=>({value:String(t.id),label:t.name}))},{key:'project_id',label:'Proyecto',choices:projects.map(p=>({value:String(p.id),label:p.client_name+' · '+p.name}))},{key:'next_month',label:'Primer mes (AAAA-MM)'},{key:'assigned_user_id',label:'Responsable',choices:people,optional:true}]} defaults={{template_id:'',project_id:'',next_month:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Asuncion',year:'numeric',month:'2-digit'}).format(new Date()).slice(0,7),assigned_user_id:''}} save={async v=>{if(!/^\d{4}-\d{2}$/.test(v.next_month))throw Error('Ingresá el mes como AAAA-MM.');await api('/api/agency/schedules',{...v,next_month:v.next_month+'-01'});await load();setCreating(false);}}/>}{rows.map(r=><article className="notice" key={r.id}><b>{r.template_name} · {r.project_name}</b>{r.actor_name&&<p>Programado por <ActorIdentity name={r.actor_name} photoUrl={r.actor_photo_url} verified={r.actor_verified===true}/></p>}<p>{r.active?'Activa':'Pausada'} · Próximo mes {r.next_month.slice(0,7)}</p><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/api/agency/schedules/'+r.id,{active:!r.active},'PATCH');await load();}catch(e){notify({tone:'error',message:error(e)});}finally{setBusy(false);}}}>{r.active?'Pausar':'Reactivar'}</button></article>)}{!rows.length&&!creating&&<p className="empty-copy">Todavía no hay programaciones activas.</p>}</Dialog>}</>;
}
