'use client';

import { DndContext, DragEndEvent, useDraggable, useDroppable } from '@dnd-kit/core';
import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { BarChart3, BriefcaseBusiness, CalendarDays, ChevronDown, FileText, FolderKanban, LayoutDashboard, Link as LinkIcon, LogOut, Plus, Search, Settings, Users, WalletCards, X } from 'lucide-react';

const core = process.env.NEXT_PUBLIC_CORE_API_URL || 'https://admin.scaleparaguay.com';
const statuses = [
  { id: 'blocked', label: 'Bloqueado', tone: 'red' }, { id: 'to_record', label: 'Por grabar', tone: 'yellow' },
  { id: 'recorded', label: 'Grabado', tone: 'teal' }, { id: 'editing', label: 'Editando', tone: 'purple' },
  { id: 'review', label: 'Revisión', tone: 'blue' }, { id: 'approved', label: 'Aprobado', tone: 'green' },
] as const;
type Status = (typeof statuses)[number]['id'];
const nav = [['Resumen', LayoutDashboard], ['Clientes', Users], ['Proyectos', FolderKanban], ['Presupuestos', FileText], ['Pagos', WalletCards], ['Equipo', BriefcaseBusiness]] as const;
type Client = { id: string; name: string; email: string | null; phone: string | null; active: boolean };
type Project = { id: string; name: string; client_id: string; client_name: string; drive_url: string | null; status: string; work_order_count: number };
type WorkOrder = { id: string; title: string; project_id: string; project_name: string; client_name: string; status: Status; description: string | null; drive_url: string | null };
type User = { email: string; role: string; organization_name: string; organization_slug: string };
type Summary = { active_clients: number; active_projects: number; open_orders: number };
type ModalKind = 'client' | 'project' | 'order' | null;

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${core}${path}`, { ...init, credentials: 'include', headers: { ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...init.headers } });
  const data = await response.json().catch(() => ({})) as T & { error?: string };
  if (!response.ok) throw new Error(data.error || 'No se pudo completar la acción.');
  return data;
}
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  return createPortal(<div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event => event.stopPropagation()}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={18}/></button></div>{children}</section></div>, document.body);
}
function DraggableOrder({ order }: { order: WorkOrder }) {
  const draggable = useDraggable({ id: order.id }); const style = draggable.transform ? { transform: `translate3d(${draggable.transform.x}px, ${draggable.transform.y}px, 0)` } : undefined;
  return <article ref={draggable.setNodeRef} style={style} {...draggable.listeners} {...draggable.attributes} className={`work-card ${draggable.isDragging ? 'dragging' : ''}`}><div className="card-top"><b>{order.title}</b><span>⋮⋮</span></div><p>{order.client_name} · {order.project_name}</p><div className="card-meta">{order.drive_url ? <a href={order.drive_url} target="_blank" rel="noreferrer" onPointerDown={event => event.stopPropagation()}><LinkIcon size={12}/> Drive</a> : <span>Sin enlace</span>}<span>{order.description || 'Arrastrá para mover'}</span></div></article>;
}
function KanbanColumn({ status, orders }: { status: (typeof statuses)[number]; orders: WorkOrder[] }) {
  const droppable = useDroppable({ id: `status-${status.id}` });
  return <section ref={droppable.setNodeRef} className={`column ${droppable.isOver ? 'drop-over' : ''}`}><div className="column-title"><span className={`dot ${status.tone}`}/><b>{status.label}</b><em>{orders.length}</em></div>{orders.map(order => <DraggableOrder key={order.id} order={order}/>)}</section>;
}

const clientSchema = z.object({ name: z.string().trim().min(2, 'Escribí el nombre del cliente.'), email: z.string().email('Email inválido.').or(z.literal('')), phone: z.string().max(40).optional() });
type ClientValues = z.infer<typeof clientSchema>;
function ClientForm({ done }: { done: (client: Client) => void }) {
  const form = useForm<ClientValues>({ resolver: zodResolver(clientSchema), defaultValues: { name: '', email: '', phone: '' } }); const [error, setError] = useState('');
  async function submit(values: ClientValues) { try { const data = await request<{ client: Client }>('/api/agency/clients', { method: 'POST', body: JSON.stringify(values) }); done(data.client); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar.'); } }
  return <form className="form-stack" noValidate onSubmit={form.handleSubmit(submit)}><label>Nombre<input {...form.register('name')} autoFocus />{form.formState.errors.name && <small className="error">{form.formState.errors.name.message}</small>}</label><label>Email<input type="email" {...form.register('email')} />{form.formState.errors.email && <small className="error">{form.formState.errors.email.message}</small>}</label><label>Teléfono<input {...form.register('phone')} /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? 'Guardando…' : 'Crear cliente'}</button></form>;
}
const projectSchema = z.object({ name: z.string().trim().min(2, 'Escribí el nombre del proyecto.'), clientId: z.string().min(1, 'Elegí un cliente.'), driveUrl: z.string().url('Pegá un enlace válido de Drive.').or(z.literal('')) });
type ProjectValues = z.infer<typeof projectSchema>;
function ProjectForm({ clients, done }: { clients: Client[]; done: (project: Project) => void }) {
  const form = useForm<ProjectValues>({ resolver: zodResolver(projectSchema), defaultValues: { name: '', clientId: '', driveUrl: '' } }); const [error, setError] = useState('');
  async function submit(values: ProjectValues) { try { const data = await request<{ project: Project }>('/api/agency/projects', { method: 'POST', body: JSON.stringify(values) }); done(data.project); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar.'); } }
  return <form className="form-stack" noValidate onSubmit={form.handleSubmit(submit)}><label>Nombre del proyecto<input {...form.register('name')} autoFocus />{form.formState.errors.name && <small className="error">{form.formState.errors.name.message}</small>}</label><fieldset><legend>Cliente</legend><div className="choice-list">{clients.map(client => <button type="button" className={form.watch('clientId') === client.id ? 'choice active' : 'choice'} onClick={() => form.setValue('clientId', client.id, { shouldValidate: true })} key={client.id}>{client.name}</button>)}</div>{form.formState.errors.clientId && <small className="error">{form.formState.errors.clientId.message}</small>}</fieldset><label>Carpeta de Google Drive<input placeholder="https://drive.google.com/..." {...form.register('driveUrl')} />{form.formState.errors.driveUrl && <small className="error">{form.formState.errors.driveUrl.message}</small>}</label>{error && <p className="error">{error}</p>}<button className="primary" disabled={!clients.length || form.formState.isSubmitting}>{form.formState.isSubmitting ? 'Guardando…' : 'Crear proyecto'}</button>{!clients.length && <p className="form-note">Primero creá un cliente.</p>}</form>;
}
const orderSchema = z.object({ title: z.string().trim().min(2, 'Escribí qué hay que hacer.'), projectId: z.string().min(1, 'Elegí un proyecto.'), status: z.enum(['blocked','to_record','recorded','editing','review','approved']), driveUrl: z.string().url('Pegá un enlace válido de Drive.').or(z.literal('')), description: z.string().max(500).optional() });
type OrderValues = z.infer<typeof orderSchema>;
function OrderForm({ projects, done }: { projects: Project[]; done: (order: WorkOrder) => void }) {
  const form = useForm<OrderValues>({ resolver: zodResolver(orderSchema), defaultValues: { title: '', projectId: '', status: 'to_record', driveUrl: '', description: '' } }); const [error, setError] = useState('');
  async function submit(values: OrderValues) { try { const data = await request<{ workOrder: WorkOrder }>('/api/agency/work-orders', { method: 'POST', body: JSON.stringify(values) }); done(data.workOrder); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo guardar.'); } }
  return <form className="form-stack" noValidate onSubmit={form.handleSubmit(submit)}><label>Orden de trabajo<input {...form.register('title')} autoFocus />{form.formState.errors.title && <small className="error">{form.formState.errors.title.message}</small>}</label><fieldset><legend>Proyecto</legend><div className="choice-list">{projects.map(project => <button type="button" className={form.watch('projectId') === project.id ? 'choice active' : 'choice'} onClick={() => form.setValue('projectId', project.id, { shouldValidate: true })} key={project.id}>{project.client_name} · {project.name}</button>)}</div>{form.formState.errors.projectId && <small className="error">{form.formState.errors.projectId.message}</small>}</fieldset><fieldset><legend>Estado inicial</legend><div className="choice-list compact">{statuses.map(status => <button type="button" className={form.watch('status') === status.id ? 'choice active' : 'choice'} onClick={() => form.setValue('status', status.id)} key={status.id}>{status.label}</button>)}</div></fieldset><label>Enlace de Drive<input placeholder="https://drive.google.com/..." {...form.register('driveUrl')} /></label><label>Notas<textarea {...form.register('description')} /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={!projects.length || form.formState.isSubmitting}>{form.formState.isSubmitting ? 'Guardando…' : 'Crear orden'}</button>{!projects.length && <p className="form-note">Primero creá un proyecto.</p>}</form>;
}

export default function Home() {
  const [signedIn, setSignedIn] = useState(false); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [active, setActive] = useState('Resumen'); const [toast, setToast] = useState(''); const [modal, setModal] = useState<ModalKind>(null); const [user, setUser] = useState<User | null>(null); const [clients, setClients] = useState<Client[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [orders, setOrders] = useState<WorkOrder[]>([]); const [summary, setSummary] = useState<Summary>({ active_clients: 0, active_projects: 0, open_orders: 0 });
  async function load() { const [clientData, projectData, orderData, summaryData] = await Promise.all([request<{ clients: Client[] }>('/api/agency/clients'), request<{ projects: Project[] }>('/api/agency/projects'), request<{ workOrders: WorkOrder[] }>('/api/agency/work-orders'), request<{ summary: Summary }>('/api/agency/summary')]); setClients(clientData.clients); setProjects(projectData.projects); setOrders(orderData.workOrders); setSummary(summaryData.summary); }
  useEffect(() => { request<{ user: User }>('/api/auth/me').then(data => { setUser(data.user); setSignedIn(true); return load(); }).catch(() => setSignedIn(false)).finally(() => setLoading(false)); }, []);
  async function login(event: React.FormEvent) { event.preventDefault(); setToast(''); try { await request('/api/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); const data = await request<{ user: User }>('/api/auth/me'); setUser(data.user); setSignedIn(true); await load(); } catch (cause) { setToast(cause instanceof Error ? cause.message : 'No se pudo iniciar sesión.'); } }
  async function logout() { await request('/api/auth/logout', { method: 'POST' }).catch(() => undefined); setSignedIn(false); setUser(null); }
  async function onDragEnd(event: DragEndEvent) { const id = String(event.active.id); const target = String(event.over?.id || ''); if (!target.startsWith('status-')) return; const status = target.replace('status-', '') as Status; const current = orders.find(order => order.id === id); if (!current || current.status === status) return; const previous = orders; setOrders(items => items.map(order => order.id === id ? { ...order, status } : order)); try { await request(`/api/agency/work-orders/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); } catch (cause) { setOrders(previous); setToast(cause instanceof Error ? cause.message : 'No se pudo mover la orden.'); } }
  const close = () => setModal(null);
  if (loading) return <div className="loading-page">Cargando Scale OS…</div>;
  if (!signedIn) return <div className="login-page"><div className="login-card"><div className="brand login-brand"><span className="brand-mark">S</span><div>scale<span>OS</span><small>OPERACIONES</small></div></div><p className="eyebrow">PANEL INTERNO</p><h1>Entrá a Scale OS</h1><p className="login-copy">Clientes, proyectos y operación en un solo lugar.</p><form noValidate onSubmit={login}><label>Email<input value={email} onChange={event => setEmail(event.target.value)} type="email" placeholder="Tu email" required /></label><label>Contraseña<input value={password} onChange={event => setPassword(event.target.value)} type="password" placeholder="••••••••" required /></label><button className="primary login-button">Iniciar sesión</button>{toast && <p className="error">{toast}</p>}</form></div></div>;
  const firstName = user?.email.split('@')[0] || 'U';
  return <main className="shell"><aside><div className="brand"><span className="brand-mark">S</span><div>scale<span>OS</span><small>OPERACIONES</small></div></div><div className="workspace">{user?.organization_name || 'Organización'} <ChevronDown size={15}/></div><nav>{nav.map(([label, Icon]) => <button key={label} className={active === label ? 'active' : ''} onClick={() => setActive(label)}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-bottom"><button><BarChart3 size={18}/>Reportes</button><button><Settings size={18}/>Configuración</button><button className="user" onClick={logout}><div className="avatar">{firstName[0].toUpperCase()}</div><div><b>{firstName}</b><small>{user?.role}</small></div><LogOut size={16}/></button></div></aside><section className="content"><header><div><p className="eyebrow">ORGANIZACIÓN · {user?.organization_slug}</p><h1>{active}</h1></div><div className="header-actions"><button className="icon-button" aria-label="Buscar"><Search size={19}/></button><button className="primary" onClick={() => setModal(active === 'Clientes' ? 'client' : active === 'Proyectos' ? 'project' : 'order')}><Plus size={18}/> Crear nuevo</button></div></header>
    {active === 'Resumen' && <><section className="metrics"><article className="metric gold"><span>Clientes activos</span><strong>{summary.active_clients}</strong><small>Base actual de la agencia</small></article><article className="metric violet"><span>Proyectos activos</span><strong>{summary.active_projects}</strong><small>Con trabajo en curso</small></article><article className="metric blue"><span>Órdenes abiertas</span><strong>{summary.open_orders}</strong><small>Seguimiento diario</small></article><article className="metric green"><span>Empresa</span><strong>1</strong><small>{user?.organization_name}</small></article></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">OPERACIÓN DIARIA</p><h2>Tablero de producción</h2></div><button className="text-button" onClick={() => setActive('Proyectos')}>Ver proyectos →</button></div><DndContext onDragEnd={onDragEnd}><div className="kanban">{statuses.map(status => <KanbanColumn key={status.id} status={status} orders={orders.filter(order => order.status === status.id)}/>)}</div></DndContext><p className="board-note">Arrastrá una orden de una columna a otra para actualizar su estado.</p></section></>}
    {active === 'Clientes' && <section className="panel directory"><div className="panel-heading"><div><p className="eyebrow">BASE COMERCIAL</p><h2>Clientes de {user?.organization_name}</h2></div><button className="primary" onClick={() => setModal('client')}><Plus size={16}/> Cliente</button></div><div className="client-list">{clients.length ? clients.map((client, index) => <div className="client-row" key={client.id}><div className={`client-avatar ${['green','yellow','purple','blue'][index % 4]}`}>{client.name[0]}</div><div><b>{client.name}</b><small>{client.email || 'Sin email registrado'}</small></div><span>{client.phone || 'Sin teléfono'}</span></div>) : <p className="empty-copy">Todavía no hay clientes. Creá el primero para empezar.</p>}</div></section>}
    {active === 'Proyectos' && <section className="panel directory"><div className="panel-heading"><div><p className="eyebrow">OPERACIÓN</p><h2>Proyectos y enlaces</h2></div><button className="primary" onClick={() => setModal('project')}><Plus size={16}/> Proyecto</button></div><div className="project-grid">{projects.length ? projects.map(project => <article className="project-card" key={project.id}><p className="eyebrow">{project.client_name}</p><h3>{project.name}</h3><p>{project.work_order_count} órdenes de trabajo</p>{project.drive_url ? <a href={project.drive_url} target="_blank" rel="noreferrer"><LinkIcon size={14}/> Abrir Drive</a> : <span>Sin enlace de Drive</span>}</article>) : <p className="empty-copy">Creá un proyecto después de cargar un cliente.</p>}</div></section>}
    {['Presupuestos','Pagos','Equipo'].includes(active) && <section className="empty-state"><div className="empty-icon"><CalendarDays size={30}/></div><h2>{active}</h2><p>Este módulo se habilita en la siguiente etapa, conectado al mismo núcleo de datos.</p></section>}{toast && <button className="toast" onClick={() => setToast('')}>{toast}</button>}</section>{modal === 'client' && <Modal title="Nuevo cliente" onClose={close}><ClientForm done={client => { setClients(current => [client, ...current]); setSummary(current => ({ ...current, active_clients: current.active_clients + 1 })); close(); }}/></Modal>}{modal === 'project' && <Modal title="Nuevo proyecto" onClose={close}><ProjectForm clients={clients} done={async () => { await load(); close(); }}/></Modal>}{modal === 'order' && <Modal title="Nueva orden de trabajo" onClose={close}><OrderForm projects={projects} done={async () => { await load(); close(); }}/></Modal>}</main>;
}
