"use client";
import {useEffect,useState} from 'react';
import {api,Dialog,Editor} from './operations';
import {ActorIdentity} from './actor-identity';
import {SaveActions} from './save-actions';
import './studio-workspace.css';
import {Pencil,X} from 'lucide-react';
import {SelectCustom} from './profile-controls';

type Person={id:string;name:string;photo_url?:string|null};
type Project={id:string;name:string;client_name?:string};
type StudioSpace={id:string;name:string;scenario:string;notes:string;active:boolean};
type StudioReservation={id:string;space_id:string;space_name:string;space_scenario?:string;project_id:string|null;project_name:string|null;title:string;production_type:ProductionType;starts_at:string;ends_at:string;status:'reserved'|'cancelled';notes:string;created_by_user_id:string;responsible_members:Person[];version:number;actor_name?:string;actor_photo_url?:string;actor_verified?:boolean};
type Context={user_id:string;role:string;time_zone:string;can_manage:boolean;can_reserve:boolean;members:Person[];projects:Project[]};
type ProductionType='video'|'podcast'|'ads'|'fotografia'|'streaming'|'otro';
const types:{value:ProductionType;label:string}[]=[{value:'video',label:'Video / Reels'},{value:'podcast',label:'Podcast'},{value:'ads',label:'Ads'},{value:'fotografia',label:'Foto'},{value:'streaming',label:'Streaming'},{value:'otro',label:'Otro'}];
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'No se pudo completar la operación';
const zone='America/Asuncion';
const dateTime=(value:string)=>new Intl.DateTimeFormat('es-PY',{timeZone:zone,weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
function localTime(value:string|Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const part=(type:string)=>parts.find(item=>item.type===type)!.value;return `${part('year')}-${part('month')}-${part('day')}T${part('hour')}:${part('minute')}`;}
function utcTime(value:string){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(value))throw Error('Completá fecha y hora');const base=new Date(value+'Z').getTime();if(!Number.isFinite(base))throw Error('Fecha inválida');let candidate=base;for(let index=0;index<3;index++)candidate+=base-new Date(localTime(new Date(candidate))+'Z').getTime();if(localTime(new Date(candidate))!==value)throw Error('Esa hora no existe en Asunción');return new Date(candidate).toISOString();}
function monthRange(month:string){const [year,currentMonth]=month.split('-').map(Number),next=new Date(Date.UTC(year,currentMonth,1)).toISOString().slice(0,7);return {from:utcTime(`${month}-01T00:00`),to:utcTime(`${next}-01T00:00`)};}

export function StudioWorkspace({role}:{role:string}){return ['owner','admin','management','production','finance','editor','viewer'].includes(role)?<StudioPanel/>:null;}
function StudioPanel(){
 const [context,setContext]=useState<Context|null>(null),[spaces,setSpaces]=useState<StudioSpace[]>([]),[reservations,setReservations]=useState<StudioReservation[]>([]),[month,setMonth]=useState(()=>localTime(new Date()).slice(0,7));
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[editSpace,setEditSpace]=useState<StudioSpace|'new'|null>(null),[editReservation,setEditReservation]=useState<StudioReservation|'new'|null>(null),[cancel,setCancel]=useState<StudioReservation|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const {from,to}=monthRange(month);setLoading(true);Promise.all([api<Context>('/api/agency/studio-context'),api<{spaces:StudioSpace[]}>('/api/agency/studio-spaces'),api<{reservations:StudioReservation[]}>(`/api/agency/studio-reservations?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`)]).then(([current,spaceData,reservationData])=>{if(!active)return;setContext(current);setSpaces(spaceData.spaces);setReservations(reservationData.reservations);setError('');}).catch(reason=>{if(active)setError(errorMessage(reason));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[month,refresh]);
 const saved=(message:string)=>{setNotice(message);setEditSpace(null);setEditReservation(null);setCancel(null);setRefresh(value=>value+1);};
 if(loading)return <section className="panel" aria-busy="true"><h2>Estudio y reservas</h2><p role="status">Cargando espacios y calendario…</p></section>;
 if(error)return <section className="panel"><h2>Estudio y reservas</h2><p className="error" role="alert">{error}</p><button className="secondary" onClick={()=>setRefresh(value=>value+1)}>Reintentar</button></section>;
 const activeSpaces=spaces.filter(space=>space.active);
 return <div className="studio-workspace ops-stack"><section className="panel"><div className="panel-heading"><div><h2>Estudio y reservas</h2><p className="form-note">Espacios, escenarios y franjas de producción. No reserva ni retira equipos.</p></div><div className="inline-actions">{context?.can_manage&&<button className="secondary" onClick={()=>setEditSpace('new')}>Agregar espacio</button>}{context?.can_reserve&&<button className="primary" disabled={!activeSpaces.length} onClick={()=>setEditReservation('new')}>Nueva reserva</button>}</div></div>{notice&&<p role="status" className="success">{notice}</p>}
  {!spaces.length?<p className="empty-copy">Todavía no hay espacios. Un responsable puede crear el set, cabina o escenario antes de reservar.</p>:<div className="studio-spaces">{spaces.map(space=><article className="studio-space" key={space.id}><div><h3>{space.name}</h3><p>{space.scenario||'Escenario sin especificar'}</p>{space.notes&&<small>{space.notes}</small>}</div><div>{space.active?<span className="studio-state">Disponible</span>:<span className="studio-state muted">Inactivo</span>}{context?.can_manage&&<button className="text-button" onClick={()=>setEditSpace(space)}><Pencil size={14}/>Editar</button>}</div></article>)}</div>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>Calendario del estudio</h2><p className="form-note">Horario de Asunción. Una reserva activa bloquea únicamente su espacio.</p></div><label className="studio-month">Mes<input type="month" value={month} onChange={event=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(event.target.value))setMonth(event.target.value);}}/></label></div><StudioCalendar month={month} reservations={reservations}/><div className="studio-reservation-list">{reservations.map(reservation=><article className="studio-reservation" key={reservation.id}><div className="studio-reservation-identity"><h3>{reservation.title}</h3><small>{reservation.space_name}{reservation.space_scenario?` · ${reservation.space_scenario}`:''} · {types.find(type=>type.value===reservation.production_type)?.label||reservation.production_type}</small></div><span className="studio-reservation-schedule">{dateTime(reservation.starts_at)} → {dateTime(reservation.ends_at)}</span><span className="studio-reservation-project">{reservation.project_name||'Sin proyecto vinculado'}</span><span className="studio-members"><span>Responsables:</span>{reservation.responsible_members.map(person=><ActorIdentity key={person.id} name={person.name} photoUrl={person.photo_url} verified/>)}</span><span className={reservation.status==='reserved'?'studio-state':'studio-state muted'}>{reservation.status==='reserved'?'Reservada':'Cancelada'}</span>{context&&(context.can_manage||context.can_reserve&&String(reservation.created_by_user_id)===String(context.user_id))&&reservation.status==='reserved'&&<div className="inline-actions studio-reservation-actions"><button className="icon-button" type="button" title="Editar reserva" aria-label={`Editar reserva: ${reservation.title}`} onClick={()=>setEditReservation(reservation)}><Pencil size={16}/></button><button className="icon-button warn" type="button" title="Cancelar reserva" aria-label={`Cancelar reserva: ${reservation.title}`} onClick={()=>setCancel(reservation)}><X size={16}/></button></div>}{reservation.actor_name&&<p className="form-note studio-reservation-note">Creada por <ActorIdentity name={reservation.actor_name} photoUrl={reservation.actor_photo_url} verified={reservation.actor_verified===true}/></p>}{reservation.notes&&<p className="form-note studio-reservation-note">{reservation.notes}</p>}</article>)}</div>{!reservations.length&&<p className="empty-copy">No hay reservas en este mes.</p>}</section>
 {editSpace&&context?.can_manage&&<Dialog title={editSpace==='new'?'Nuevo espacio de estudio':'Editar espacio'} close={()=>setEditSpace(null)}><Editor closeOnSave fields={[{key:'name',label:'Nombre del espacio'},{key:'scenario',label:'Escenario o fondo',optional:true},{key:'active',label:'Disponibilidad',choices:[{value:'true',label:'Disponible para reservar'},{value:'false',label:'Inactivo'}]},{key:'notes',label:'Notas',type:'textarea',optional:true}]} defaults={editSpace==='new'?{name:'',scenario:'',active:'true',notes:''}:{name:editSpace.name,scenario:editSpace.scenario,active:String(editSpace.active),notes:editSpace.notes}} save={async values=>{await api(`/api/agency/studio-spaces${editSpace==='new'?'':`/${editSpace.id}`}`,{...values,active:values.active==='true'},editSpace==='new'?'POST':'PATCH');saved('Espacio guardado.');}}/></Dialog>}
 {editReservation&&context?.can_reserve&&<Dialog title={editReservation==='new'?'Nueva reserva de estudio':'Editar reserva de estudio'} close={()=>setEditReservation(null)}><StudioReservationForm context={context} spaces={spaces} reservations={reservations} record={editReservation==='new'?null:editReservation} done={()=>saved('Reserva guardada.')} /></Dialog>}
 {cancel&&<Dialog title="Cancelar reserva de estudio" busy={busy} close={()=>{if(!busy)setCancel(null);}}><p>Se libera el espacio para esa franja. No afecta equipos ni otras reservas.</p><SaveActions pending={busy}><button className="primary" disabled={busy} onClick={async()=>{if(busy)return;setBusy(true);try{await api(`/api/agency/studio-reservations/${cancel.id}/cancel`,{expected_version:cancel.version});saved('Reserva cancelada.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}}>{busy?'Cancelando…':'Confirmar cancelación'}</button></SaveActions></Dialog>}
 </div>;
}
function StudioReservationForm({context,spaces,reservations,record,done}:{context:Context;spaces:StudioSpace[];reservations:StudioReservation[];record:StudioReservation|null;done:()=>void}){
 const [title,setTitle]=useState(record?.title||''),[space,setSpace]=useState(String(record?.space_id||'')),[project,setProject]=useState(String(record?.project_id||'')),[productionType,setProductionType]=useState<ProductionType>(record?.production_type||'video'),[startsAt,setStartsAt]=useState(record?localTime(record.starts_at):''),[endsAt,setEndsAt]=useState(record?localTime(record.ends_at):''),[members,setMembers]=useState<string[]>(record?.responsible_members.map(person=>String(person.id))||(context.role==='production'?[String(context.user_id)]:[])),[notes,setNotes]=useState(record?.notes||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const toggle=(id:string)=>setMembers(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
 return <form className="studio-form-grid" onSubmit={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{if(!members.length)throw Error('Elegí al menos un responsable');if(!space)throw Error('Elegí un espacio');const starts=utcTime(startsAt),ends=utcTime(endsAt);if(ends<=starts)throw Error('La hora de cierre debe ser posterior al inicio');const conflict=reservations.find(item=>item.status==='reserved'&&item.space_id===space&&String(item.id)!==String(record?.id||'')&&item.starts_at<ends&&item.ends_at>starts);if(conflict)throw Error(`El espacio ${conflict.space_name} ya está reservado de ${dateTime(conflict.starts_at)} a ${dateTime(conflict.ends_at)} (${conflict.title}).`);await api(`/api/agency/studio-reservations${record?`/${record.id}`:''}`,{title,space_id:space,project_id:project||null,production_type:productionType,starts_at:starts,ends_at:ends,responsible_user_ids:members,notes,...(record?{expected_version:record.version}:{})},record?'PATCH':'POST');done();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}}>
 <label className="studio-wide">Nombre de la reserva<input value={title} onChange={event=>setTitle(event.target.value)} required minLength={2} maxLength={160} placeholder="Grabación de campaña · cliente"/></label>
 <label><SelectCustom label="Espacio" choices={[{value:'',label:'Elegí un espacio'},...spaces.filter(item=>item.active||String(item.id)===String(record?.space_id)).map(item=>({value:String(item.id),label:item.scenario?item.name+' · '+item.scenario:item.name}))]} value={space} onChange={setSpace}/></label>
 <label><SelectCustom label="Tipo de producción" choices={types} value={productionType} onChange={value=>setProductionType(value as ProductionType)}/></label>
 <label className="studio-wide"><SelectCustom label="Proyecto vinculado · Opcional" choices={[{value:'',label:'Sin proyecto vinculado'},...context.projects.map(item=>({value:String(item.id),label:item.client_name?item.client_name+' · '+item.name:item.name}))]} value={project} onChange={setProject}/></label>
 <label>Desde · Asunción<input type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)} required/></label><label>Hasta · Asunción<input type="datetime-local" value={endsAt} min={startsAt||undefined} onChange={event=>setEndsAt(event.target.value)} required/></label>
 <fieldset className="studio-wide"><legend>Responsables · {members.length}</legend><div className="studio-member-options">{context.members.map(person=><label key={person.id} className="studio-member-option"><input type="checkbox" checked={members.includes(String(person.id))} onChange={()=>toggle(String(person.id))}/><ActorIdentity name={person.name} photoUrl={person.photo_url} verified/></label>)}</div></fieldset>
 <label className="studio-wide">Notas · Opcional<textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={2000}/></label><p className="form-note studio-wide">El sistema impide reservas que se superpongan en el mismo espacio. Reservar un estudio no bloquea inventario.</p>{error&&<p className="error studio-wide" role="alert">{error}</p>}<SaveActions pending={busy}><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar reserva'}</button></SaveActions>
 </form>;
}
function StudioCalendar({month,reservations}:{month:string;reservations:StudioReservation[]}){const [year,currentMonth]=month.split('-').map(Number),days=new Date(Date.UTC(year,currentMonth,0)).getUTCDate(),offset=(new Date(Date.UTC(year,currentMonth-1,1)).getUTCDay()+6)%7;return <div className="studio-calendar" aria-label="Calendario mensual del estudio"><div className="studio-weekdays" aria-hidden="true">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(day=><span key={day}>{day}</span>)}</div><div className="studio-calendar-grid">{Array.from({length:offset},(_,index)=><div className="studio-calendar-blank" key={`blank-${index}`}/>)}{Array.from({length:days},(_,index)=>{const day=`${month}-${String(index+1).padStart(2,'0')}`,start=utcTime(day+'T00:00'),next=new Date(Date.UTC(year,currentMonth-1,index+2)).toISOString().slice(0,10),end=utcTime(next+'T00:00');const rows=reservations.filter(item=>item.status==='reserved'&&item.starts_at<end&&item.ends_at>start);return <div className="studio-calendar-day" key={day}><time dateTime={day}>{index+1}</time>{rows.map(item=><div className="studio-calendar-event" key={item.id}><b>{item.space_name}</b><span>{item.title}</span></div>)}</div>;})}</div></div>;}
