"use client";
import {currencyChoices} from "./currencies";
import {ClientReviewControl} from './daily-controls';
import {ProjectPresence} from './presence';
import {clientStatuses} from './client-status';
import {ClientAppearance,ClientIdentity} from './client-identity';
import {useEffect,useState} from 'react';
import {DndContext,useDraggable,useDroppable,useSensor,useSensors,PointerSensor,KeyboardSensor,DragEndEvent} from '@dnd-kit/core';
import {GripVertical,Plus} from 'lucide-react';
import {api,Dialog,Editor,Field,money} from './operations';
import {QuoteComposer} from './quote-composer';
import {RemoveRecord} from './archive-controls';
type Row={id:string;[key:string]:unknown};
const str=(r:Row,k:string)=>String(r[k]??'');
const err=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar';
const currencies=currencyChoices;
const stages=[{value:'lead',label:'Nuevo lead'},{value:'contacted',label:'Contactado'},{value:'proposal',label:'Propuesta'},{value:'negotiation',label:'Negociación'},{value:'won',label:'Ganado'},{value:'lost',label:'Perdido'}];
const probabilities:Record<string,number>={lead:10,contacted:25,proposal:50,negotiation:75,won:100,lost:0};
function LeadCard({row,edit,role,refresh}: {row:Row;edit:()=>void;role:string;refresh:()=>Promise<void>}){const drag=useDraggable({id:String(row.id)});return <article className="ops-card" ref={drag.setNodeRef} style={{opacity:drag.isDragging?.4:1}}><div className="panel-heading"><b>{str(row,'name')}</b><button className="icon-button" aria-label={`Mover ${str(row,'name')}`} {...drag.attributes} {...drag.listeners}><GripVertical size={16}/></button></div><strong>{money(str(row,'amount'),str(row,'currency'))}</strong><p>Probabilidad: {str(row,'probability')}%</p><button className="text-button" onClick={edit}>Ver oportunidad</button><RemoveRecord kind="leads" id={row.id} name={str(row,'name')} role={role} done={refresh}/></article>;}
function LeadColumn({stage,rows,edit,role,refresh}:{stage:typeof stages[number];rows:Row[];edit:(r:Row)=>void;role:string;refresh:()=>Promise<void>}){const drop=useDroppable({id:`stage-${stage.value}`});return <section ref={drop.setNodeRef} className={`suite-column ${drop.isOver?'suite-over':''}`}><h3>{stage.label} · {rows.length}</h3>{currencies.filter(c=>rows.some(r=>r.currency===c.value)).map(c=><small key={c.value}>{money(rows.filter(r=>r.currency===c.value).reduce((s,r)=>s+Number(r.amount)*Number(r.probability)/100,0),c.value)} ponderado</small>)}{rows.map(r=><LeadCard key={r.id} row={r} edit={()=>edit(r)} role={role} refresh={refresh}/>)}</section>;}
export function CatalogWorkspace({kind,role}:{kind:'leads'|'inventory'|'plans';role:string}){
 const [rows,setRows]=useState<Row[]>([]),[members,setMembers]=useState<Row[]>([]),[edit,setEdit]=useState<Row|'new'|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor));
 const canEdit=kind==='inventory'?['owner','admin','management','production','finance'].includes(role):['owner','admin','management','finance','sales'].includes(role);
 async function load(){const d=await api<{records:Row[]}>(`/api/agency/${kind}`);setRows(d.records);if(kind==='inventory'){const m=await api<{members:Row[]}>('/api/agency/custodians');setMembers(m.members);}}
 useEffect(()=>{void load().catch(e=>setError(err(e)));},[kind]);
 const row=edit&&edit!=='new'?edit:null;
 const fields:Field[]=kind==='leads'?[
  {key:'name',label:'Empresa o prospecto'},{key:'email',label:'Correo',type:'email',optional:true},{key:'phone',label:'Teléfono',optional:true},{key:'stage',label:'Etapa',choices:stages},{key:'amount',label:'Valor de la oportunidad',type:'money'},{key:'currency',label:'Moneda',choices:currencies},{key:'probability',label:'Probabilidad (%)',type:'number'},{key:'notes',label:'Próximo paso y notas',type:'textarea',optional:true}
 ]:[{key:'name',label:'Equipo'},{key:'category',label:'Categoría',choices:['Cámara','Lente','Audio','Iluminación','Computación','Accesorio','Otro'].map(v=>({value:v,label:v}))},{key:'serial_number',label:'Número de serie',optional:true},{key:'custodian_user_id',label:'Responsable',optional:true,choices:[{value:'',label:'Sin asignar'},...members.map(m=>({value:String(m.id),label:str(m,'email')}))]},{key:'value',label:'Valor del equipo',type:'money'},{key:'currency',label:'Moneda',choices:currencies},{key:'status',label:'Estado',choices:[{value:'available',label:'Disponible'},{value:'in_use',label:'En uso'},{value:'maintenance',label:'Mantenimiento'},{value:'retired',label:'Dado de baja'}]},{key:'acquired_on',label:'Fecha de adquisición',type:'date',optional:true},{key:'notes',label:'Notas',type:'textarea',optional:true}];
 const defaults=Object.fromEntries(fields.map(f=>[f.key,row?str(row,f.key):({currency:'PYG',stage:'lead',amount:'0',probability:'10',value:'0',status:'available',category:'Cámara'} as Record<string,string>)[f.key]||'']));
 async function move(e:DragEndEvent){const stage=String(e.over?.id||'').replace('stage-','');if(!canEdit||busy||!stages.some(s=>s.value===stage))return;setBusy(true);try{await api(`/api/agency/leads/${e.active.id}`,{stage,probability:probabilities[stage]},'PATCH');await load();}catch(e){setError(err(e));}finally{setBusy(false);}}
 return <div className="ops-stack"><section className="panel"><div className="panel-heading"><h2>{{leads:'Pipeline de ventas',inventory:'Inventario y patrimonio',plans:'Planes reutilizables'}[kind]}</h2>{canEdit&&<button className="primary" onClick={()=>setEdit('new')}><Plus size={16}/>Agregar</button>}</div>{error&&<p className="error" role="alert">{error}</p>}
 {kind==='leads'?<DndContext sensors={sensors} onDragEnd={move}><div className="suite-board">{stages.map(stage=><LeadColumn key={stage.value} stage={stage} rows={rows.filter(r=>r.stage===stage.value)} edit={setEdit} role={role} refresh={load}/>)}</div></DndContext>:<div className="ops-grid">{rows.map(r=><article className="ops-card" key={r.id}><h3>{str(r,'name')}</h3>{kind==='inventory'?<><p>{str(r,'category')} · {str(r,'status')}</p><strong>{money(str(r,'value'),str(r,'currency'))}</strong><p>Serie: {str(r,'serial_number')||'—'}</p></>:<p>{Array.isArray(r.items)?r.items.length:0} ítems · {str(r,'currency')}{r.active===false?' · Archivado':''}</p>}{canEdit&&<button className="text-button" onClick={()=>setEdit(r)}>Editar</button>}<RemoveRecord kind={kind} id={r.id} name={str(r,'name')} role={role} done={load}/></article>)}</div>}
 {!rows.length&&<p className="empty-copy">Todavía no hay registros.</p>}</section>
 {edit&&canEdit&&<Dialog title={row?'Editar registro':'Nuevo registro'} close={()=>setEdit(null)}>{kind==='plans'?<QuoteComposer mode="plan" record={row} done={async()=>{setEdit(null);await load();}}/>:<><Editor columns fields={fields} defaults={defaults} save={async values=>{await api(`/api/agency/${kind}${row?`/${row.id}`:''}`,values,row?'PATCH':'POST');setEdit(null);await load();}}/>{kind==='leads'&&row&&!row.client_id&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/api/agency/leads/${row.id}/convert`,{});setEdit(null);await load();}catch(e){setError(err(e));}finally{setBusy(false);}}}>Ganado: convertir a cliente</button>}</>}</Dialog>}
 </div>;
}
export function MemberActions({member,currentEmail,role,refresh}:{member:{id:string;email:string;role:string;active?:boolean};currentEmail:string;role:string;refresh:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 if(member.email===currentEmail||member.role==='owner'&&role!=='owner')return <small>{member.active===false?'Suspendido':'Activo'}</small>;
 return <><RemoveRecord kind="members" id={member.id} name={member.email} role={role} done={refresh}/><button className="text-button" onClick={()=>setOpen(true)}>Permisos · {member.active===false?'Suspendido':'Activo'}</button>{open&&<Dialog title={member.email} close={()=>setOpen(false)}><p className="form-note">Cambiar permisos o suspender cierra las sesiones de esta persona en esta empresa.</p><Editor fields={[{key:'role',label:'Permiso',choices:[...(role==='owner'?['owner']:[]),'admin','management','finance','sales','production','editor','viewer'].map(v=>({value:v,label:({owner:'Dueño',admin:'Administrador',management:'Gerencia',finance:'Finanzas',sales:'Ventas',production:'Producción',editor:'Editor',viewer:'Solo lectura'} as Record<string,string>)[v]}))},{key:'active',label:'Acceso',choices:[{value:'true',label:'Activo'},{value:'false',label:'Suspendido'}]}]} defaults={{role:member.role,active:String(member.active!==false)}} save={async v=>{await api(`/api/agency/members/${member.id}`,{role:v.role,active:v.active==='true'},'PATCH');await refresh();setOpen(false);}}/>{member.active!==false&&<button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const d=await api<{emailSent:boolean}>(`/api/agency/members/${member.id}/resend`,{});setNotice(d.emailSent?'Invitación enviada.':'El proveedor no pudo enviar el correo.');}catch(e){setNotice(err(e));}finally{setBusy(false);}}}>Reenviar invitación</button>}{notice&&<p role="status">{notice}</p>}</Dialog>}</>;
}
export function RecordEditor({kind,recordId,name,refresh,role}:{kind:'clients'|'projects'|'work-orders';recordId:string;name?:string;refresh:()=>Promise<void>;role:string}){
 const [record,setRecord]=useState<Row|null>(null),[members,setMembers]=useState<Row[]>([]),[error,setError]=useState('');
 const permitted=kind==='clients'?['owner','admin','management','sales']:kind==='projects'?['owner','admin','management','production']:['owner','admin','management','production','editor'];
 async function open(){try{setRecord((await api<{record:Row}>(`/api/agency/${kind}/${recordId}`)).record);if(kind==='work-orders')setMembers((await api<{members:Row[]}>('/api/agency/custodians')).members);}catch(e){setError(err(e));}}
 if(!permitted.includes(role))return null;
 const fields:Field[]=kind==='clients'?[{key:'name',label:'Nombre'},{key:'legal_name',label:'Razón social',optional:true},{key:'tax_id',label:'RUC',optional:true},{key:'email',label:'Correo',type:'email',optional:true},{key:'phone',label:'Teléfono',optional:true},{key:'lifecycle_status',label:'Estado del servicio',choices:clientStatuses},{key:'notes',label:'Notas',type:'textarea',optional:true}]:kind==='projects'?[{key:'name',label:'Proyecto'},{key:'status',label:'Estado',choices:[{value:'active',label:'Activo'},{value:'paused',label:'Pausado'},{value:'completed',label:'Completado'},{value:'cancelled',label:'Cancelado'}]},{key:'drive_url',label:'Carpeta de Drive',type:'url',optional:true,wide:true},{key:'start_date',label:'Inicio',type:'date',optional:true},{key:'due_date',label:'Entrega',type:'date',optional:true},{key:'approval_levels',label:'Niveles de aprobación',choices:[1,2,3].map(n=>({value:String(n),label:String(n)}))}]:[{key:'title',label:'Pieza o tarea'},{key:'due_date',label:'Entrega',type:'date',optional:true},{key:'assigned_user_id',label:'Responsable',optional:true,choices:[{value:'',label:'Sin asignar'},...members.map(m=>({value:String(m.id),label:str(m,'email')}))]},{key:'drive_url',label:'Archivo de Drive',type:'url',optional:true},{key:'estimated_hours',label:'Horas estimadas',type:'number',optional:true},{key:'actual_hours',label:'Horas reales',type:'number',optional:true},{key:'description',label:'Brief y notas',type:'textarea',optional:true}];
 return <><button className="text-button" onClick={open}>Editar detalles</button><RemoveRecord kind={kind} id={recordId} name={name||`Registro #${recordId}`} role={role} done={refresh}/>{kind==='work-orders'&&['owner','admin','management','production'].includes(role)&&<ClientReviewControl orderId={recordId}/>}{error&&<small className="error">{error}</small>}{record&&<Dialog title={name||"Detalles"} close={()=>setRecord(null)}>{kind==='clients'?<ClientAppearance id={recordId} name={str(record,'name')} logo={str(record,'logo_url')} color={str(record,'color_key')} refresh={async()=>{await refresh();await open();}}/>:<ClientIdentity name={str(record,'client_name')} logo={str(record,'client_logo_url')} color={str(record,'client_color_key')}/>}{kind==='projects'&&<ProjectPresence projectId={recordId}/>}<Editor columns fields={fields} defaults={Object.fromEntries(fields.map(f=>[f.key,str(record,f.key)]))} save={async v=>{await api(`/api/agency/${kind}/${recordId}`,v,'PATCH');await refresh();setRecord(null);}}/>{kind==='work-orders'&&['owner','admin','management','production'].includes(role)&&['review','approved'].includes(str(record,'status'))&&<button className="secondary" onClick={async()=>{try{await api(`/api/agency/work-orders/${recordId}/${record.status==='review'?'approve':'publish'}`,{});await refresh();await open();}catch(e){setError(err(e));}}}>{record.status==='review'?`Aprobar siguiente nivel (completados: ${str(record,'approval_step')})`:'Marcar publicado'}</button>}{error&&<p className="error">{error}</p>}</Dialog>}</>;
}
export function BudgetActions({id,refresh}:{id:string;refresh:()=>Promise<void>}){const [record,setRecord]=useState<Row|null>(null),[error,setError]=useState(''),[publicUrl,setPublicUrl]=useState('');return <><button className="text-button" onClick={async()=>{try{const d=await api<{budget:Row;items:unknown[]}>(`/api/agency/budgets/${id}`);setRecord({...d.budget,items:d.items});}catch(e){setError(err(e));}}}>Abrir presupuesto</button>{error&&<p className="error">{error}</p>}{record&&<Dialog title={str(record,'number')} close={()=>setRecord(null)}><div className="inline-actions"><a className="secondary" href={`/core-api/api/agency/budgets/${id}/pdf`} target="_blank" rel="noreferrer">Descargar PDF</a><button className="secondary" onClick={async()=>{try{setPublicUrl((await api<{url:string}>(`/api/agency/budgets/${id}/share`,{})).url);await refresh();}catch(e){setError(err(e));}}}>Habilitar enlace público</button><button className="text-button" onClick={async()=>{try{await api(`/api/agency/budgets/${id}/revoke`,{});setPublicUrl('');await refresh();}catch(e){setError(err(e));}}}>Desactivar enlace</button></div>{publicUrl&&<p><a href={publicUrl} target="_blank" rel="noreferrer">{publicUrl}</a></p>}{error&&<p className="error">{error}</p>}{record.status==='accepted'?<><p>Aceptado por {str(record,'accepted_by')}. El contenido está protegido.</p><button className="primary" onClick={async()=>{try{await api(`/api/agency/budgets/${id}/invoice`,{});setError('Factura creada o recuperada. La encontrás en Pagos.');}catch(e){setError(err(e));}}}>Crear factura</button></>:<QuoteComposer mode="budget" record={record} done={async()=>{await refresh();setRecord(null);}}/>}</Dialog>}</>;}
export function FinancialDashboard({role}:{role:string}){
 const [data,setData]=useState<Record<string,Row[]>|null>(null),[error,setError]=useState('');const allowed=['owner','admin','finance'].includes(role);
 useEffect(()=>{if(allowed)void api<Record<string,Row[]>>('/api/agency/dashboard').then(setData).catch(e=>setError(err(e)));},[allowed]);
 if(!allowed)return null;return <section className="panel"><h2>Finanzas y alertas</h2>{error&&<p className="error">{error}</p>}<div className="ops-grid">{[['cash','Disponible en cuentas'],['receivables','Por cobrar'],['collections','Cobrado este mes'],['inventory','Valor del inventario']].map(([key,label])=><article className="ops-card" key={key}><p>{label}</p>{data?.[key]?.length?data[key].map((r,i)=><b key={i}>{money(str(r,'total'),str(r,'currency'))}</b>):<span>Sin movimientos</span>}</article>)}</div>{data?.alerts?.map(r=><p key={`${str(r,'type')}-${r.id}`}>Pendiente vencido: {str(r,'name')} · {str(r,'due')}</p>)}</section>;
}
export function ActivityWorkspace(){const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState('');useEffect(()=>{void api<{records:Row[]}>('/api/agency/activity').then(d=>setRows(d.records)).catch(e=>setError(err(e)));},[]);return <section className="panel"><h2>Últimos 100 cambios</h2><p className="form-note">Historial registrado por el servidor para esta empresa.</p>{error&&<p className="error">{error}</p>}{rows.map(r=><div className="payment-row" key={r.id}><div><b>{str(r,'table_name').replace('agency_','')} · {str(r,'operation')}</b><small>Registro {str(r,'record_id')} · Usuario {str(r,'actor')||'No registrado (histórico)'}</small></div><time>{new Date(str(r,'created_at')).toLocaleString('es-PY')}</time></div>)}</section>;}
export function SettingsWorkspace(){const [settings,setSettings]=useState<Row|null>(null),[rates,setRates]=useState<Row[]>([]),[notice,setNotice]=useState('');useEffect(()=>{void Promise.all([api<{settings:Row}>('/api/agency/settings'),api<{records:Row[]}>('/api/agency/exchange-rates')]).then(([s,r])=>{setSettings(s.settings);setRates(r.records);}).catch(e=>setNotice(err(e)));},[]);return <div className="ops-stack"><section className="panel"><h2>Datos de la empresa</h2>{notice&&<p role="status">{notice}</p>}{settings&&<Editor columns fields={[{key:'name',label:'Nombre de la empresa'},{key:'legal_name',label:'Razón social',optional:true},{key:'tax_id',label:'RUC',optional:true},{key:'phone',label:'Teléfono',optional:true},{key:'address',label:'Dirección',optional:true,wide:true}]} defaults={Object.fromEntries(['name','legal_name','tax_id','phone','address'].map(k=>[k,str(settings,k)]))} save={async v=>{await api('/api/agency/settings',{...v,onboarding_completed:true},'PATCH');setNotice('Datos guardados.');}}/>}</section><section className="panel"><h2>Cotización USD / PYG</h2><p className="form-note">Valor de referencia por fecha. No modifica saldos ni convierte movimientos anteriores.</p><Editor columns fields={[{key:'rate_date',label:'Fecha',type:'date'},{key:'usd_to_pyg',label:'Guaraníes por dólar',type:'number'}]} key={rates.length} defaults={{rate_date:new Date().toISOString().slice(0,10),usd_to_pyg:rates[0]?str(rates[0],'usd_to_pyg'):''}} save={async v=>{await api('/api/agency/exchange-rates',v);setRates((await api<{records:Row[]}>('/api/agency/exchange-rates')).records);}}/>{rates.map((r,i)=><p key={i}>{str(r,'rate_date')} · {str(r,'usd_to_pyg')} Gs./USD</p>)}</section><section className="panel"><h2>Integraciones externas</h2><p>Google: acceso por invitación. Drive: enlaces a carpetas y archivos.</p><p>WhatsApp, Instagram y automatizaciones de mensajes: pendientes de conexión y permisos de Meta. No se envían mensajes desde este panel todavía.</p></section></div>;}
