'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {clientPortalApiUrl,portalApi} from '../../../client-portal-api';
import {listDateFull} from '../../../list-format';
import '../../portal.css';
type Detail={delivery:{id:number;title:string;summary:string;asset_name:string;version:number;project_name:string;client_name:string;due_date?:string|null;due_time?:string|null};links:{id:number;label:string;url:string}[];comments:{id:number;body:string;created_at:string;author_name:string}[];decision:{decision:string}|null};
type ActivityEntry={kind:'decision'|'comment'|'download'|'version';at:string;version:number|null;actor_name:string|null;summary:string};
const activityLabels:Record<ActivityEntry['kind'],string>={decision:'Decisión',comment:'Comentario',download:'Descarga',version:'Nueva versión'};
export default function ClientDelivery(){
 const params=useParams<{id:string}>(),[data,setData]=useState<Detail|null>(null),[activity,setActivity]=useState<ActivityEntry[]|null>(null),[comment,setComment]=useState(''),[review,setReview]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>portalApi<Detail>('/deliveries/'+encodeURIComponent(params.id),undefined,'GET').then(setData).catch(e=>{if((e as {status?:number}).status===401)window.location.assign('/cliente/ingresar');else setError(e instanceof Error?e.message:'No se pudo cargar la entrega');});
 const loadActivity=()=>portalApi<{activity:ActivityEntry[]}>('/deliveries/'+encodeURIComponent(params.id)+'/activity',undefined,'GET').then(result=>setActivity(result.activity)).catch(()=>{});
 useEffect(()=>{void load();void loadActivity();},[params.id]);
   async function sendComment(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{await portalApi('/deliveries/'+params.id+'/comments',{body:comment});setComment('');await load();await loadActivity();}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar el comentario');}finally{setBusy(false);}}
   async function decide(decision:'approved'|'changes_requested'){if(busy)return;setBusy(true);setError('');try{await portalApi('/deliveries/'+params.id+'/decision',{decision,comment:review});setReview('');await load();await loadActivity();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar tu decisión');}finally{setBusy(false);}}
 if(!data)return <main className="client-portal"><section className="client-portal-card narrow"><p>{error||'Cargando entrega…'}</p></section></main>;
 const {delivery}=data;return <main className="client-portal"><section className="client-portal-card"><header><div><p className="portal-status">{delivery.client_name} · {delivery.project_name}</p><h1>{delivery.title}</h1><p className="portal-muted">Versión {delivery.version}{delivery.due_date&&listDateFull(delivery.due_date,delivery.due_time)?<> · Entrega <span className="portal-date">{listDateFull(delivery.due_date,delivery.due_time)}</span></>:null}</p></div><Link className="button" href="/cliente/entregas">Volver</Link></header>{delivery.summary&&<p>{delivery.summary}</p>}<p><a className="button" href={clientPortalApiUrl('/deliveries/'+encodeURIComponent(String(delivery.id))+'/download')} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" aria-label={`Abrir ${delivery.asset_name} en una pestaña nueva`}>{delivery.asset_name} <span aria-hidden="true">↗</span></a></p>{data.links.length?<section className="delivery"><h2>Archivos de esta entrega</h2>{data.links.map(link=><p key={link.id}><a href={link.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{link.label} <span aria-hidden="true">↗</span></a></p>)}</section>:null}<section className="delivery"><h2>Tu revisión</h2>{data.decision&&<p className="portal-status">Decisión registrada: {data.decision.decision==='approved'?'Aprobada':'Cambios solicitados'}</p>}<label>Comentario para la agencia<textarea value={review} onChange={event=>setReview(event.target.value)} maxLength={2000} placeholder="Opcional al aprobar; obligatorio si pedís cambios."/></label><div className="delivery-actions"><button disabled={busy} onClick={()=>void decide('approved')}>Aprobar entrega</button><button className="secondary" disabled={busy} onClick={()=>void decide('changes_requested')}>Pedir cambios</button></div></section><section><h2>Comentarios</h2><form onSubmit={sendComment}><label>Nuevo comentario<textarea value={comment} onChange={event=>setComment(event.target.value)} maxLength={2000} required/></label><button disabled={busy}>{busy?'Enviando…':'Publicar comentario'}</button></form>{data.comments.map(item=><article className="delivery" key={item.id}><strong>{item.author_name}</strong><small>{listDateFull(item.created_at)}</small><p>{item.body}</p></article>)}</section><section className="delivery"><h2>Actividad de la entrega</h2>{activity===null?<p className="portal-muted">Cargando actividad…</p>:activity.length?<ul className="delivery-activity">{activity.map((entry,index)=><li key={index}><span className="portal-status">{activityLabels[entry.kind]}</span>{entry.version!==null?` · versión ${entry.version}`:''}{entry.actor_name?` · ${entry.actor_name}`:''}<small>{listDateFull(entry.at)}</small><p>{entry.summary}</p></li>)}</ul>:<p className="portal-muted">Todavía no hay actividad registrada para esta entrega.</p>}</section>{error&&<p className="error" role="alert">{error}</p>}</section></main>;
}
