'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {clientPortalApiUrl,portalApi} from '../../../client-portal-api';
import '../../portal.css';
type Detail={delivery:{id:number;title:string;summary:string;asset_name:string;version:number;project_name:string;client_name:string};comments:{id:number;body:string;created_at:string;author_name:string}[];decision:{decision:string}|null};
export default function ClientDelivery(){
 const params=useParams<{id:string}>(),[data,setData]=useState<Detail|null>(null),[comment,setComment]=useState(''),[review,setReview]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>portalApi<Detail>('/deliveries/'+encodeURIComponent(params.id),undefined,'GET').then(setData).catch(e=>{if((e as {status?:number}).status===401)window.location.assign('/cliente/ingresar');else setError(e instanceof Error?e.message:'No se pudo cargar la entrega');});
 useEffect(()=>{void load();},[params.id]);
 async function sendComment(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await portalApi('/deliveries/'+params.id+'/comments',{body:comment});setComment('');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar el comentario');}finally{setBusy(false);}}
 async function decide(decision:'approved'|'changes_requested'){setBusy(true);setError('');try{await portalApi('/deliveries/'+params.id+'/decision',{decision,comment:review});setReview('');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar tu decisión');}finally{setBusy(false);}}
 if(!data)return <main className="client-portal"><section className="client-portal-card narrow"><p>{error||'Cargando entrega…'}</p></section></main>;
 const {delivery}=data;return <main className="client-portal"><section className="client-portal-card"><header><div><p className="portal-status">{delivery.client_name} · {delivery.project_name}</p><h1>{delivery.title}</h1><p className="portal-muted">Versión {delivery.version}</p></div><Link className="button" href="/cliente/entregas">Volver</Link></header>{delivery.summary&&<p>{delivery.summary}</p>}<p><a className="button" href={clientPortalApiUrl('/deliveries/'+encodeURIComponent(String(delivery.id))+'/download')} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" aria-label={`Abrir ${delivery.asset_name} en una pestaña nueva`}>{delivery.asset_name} <span aria-hidden="true">↗</span></a></p><section className="delivery"><h2>Tu revisión</h2>{data.decision&&<p className="portal-status">Decisión registrada: {data.decision.decision==='approved'?'Aprobada':'Cambios solicitados'}</p>}<label>Comentario para la agencia<textarea value={review} onChange={event=>setReview(event.target.value)} maxLength={2000} placeholder="Opcional al aprobar; obligatorio si pedís cambios."/></label><div className="delivery-actions"><button disabled={busy} onClick={()=>void decide('approved')}>Aprobar entrega</button><button className="secondary" disabled={busy} onClick={()=>void decide('changes_requested')}>Pedir cambios</button></div></section><section><h2>Comentarios</h2><form onSubmit={sendComment}><label>Nuevo comentario<textarea value={comment} onChange={event=>setComment(event.target.value)} maxLength={2000} required/></label><button disabled={busy}>{busy?'Enviando…':'Publicar comentario'}</button></form>{data.comments.map(item=><article className="delivery" key={item.id}><strong>{item.author_name}</strong><small>{new Date(item.created_at).toLocaleString('es-PY')}</small><p>{item.body}</p></article>)}</section>{error&&<p className="error" role="alert">{error}</p>}</section></main>;
}
